-- ============================================================
-- V010_70 — Parámetros previsionales AFP / ONP por vigencia
-- Spec: TUO SPP D.S. 054-97-EF · Ley 19990 · SBS Res. 8514-2012
--
-- Defensa:
--   - Idempotente. Tablespace heredado de INDECI_EMPLEADO (evita ORA-00959).
--   - TODO el DML contra tablas nuevas va en EXECUTE IMMEDIATE (evita ORA-00942
--     en compilacion: Oracle valida SQL estatico en parse time, no en runtime).
-- ============================================================

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;
    v_ts    VARCHAR2(30);

    PROCEDURE crear_tabla_si_falta(p_nombre VARCHAR2, p_ddl VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = UPPER(p_nombre);
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_nombre || ' -> creada en ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_nombre || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE crear_indice_si_falta(p_nombre VARCHAR2, p_ddl VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = UPPER(p_nombre);
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_nombre || ' -> creado en ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_nombre || ' ya existe. Sin cambios.');
        END IF;
    END;

BEGIN
    -- Detectar tablespace real del schema
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    DBMS_OUTPUT.PUT_LINE('Tablespace detectado: ' || v_ts);

    -- ── 1. Catalogo AFP ─────────────────────────────────────
    crear_tabla_si_falta(
        'INDECI_AFP',
        'CREATE TABLE GESTIONRRHH.INDECI_AFP ('
        || 'ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
        || 'CODIGO     VARCHAR2(10)  NOT NULL,'
        || 'NOMBRE     VARCHAR2(100) NOT NULL,'
        || 'ACTIVO     NUMBER(1)     DEFAULT 1 NOT NULL,'
        || 'CREATED_AT TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,'
        || 'CONSTRAINT INDECI_AFP_CODIGO_UK UNIQUE (CODIGO),'
        || 'CONSTRAINT INDECI_AFP_ACTIVO_CK CHECK (ACTIVO IN (0,1))'
        || ')'
    );

    -- ── 2. Parametros AFP por vigencia ──────────────────────
    crear_tabla_si_falta(
        'INDECI_AFP_PARAMETRO_VIGENCIA',
        'CREATE TABLE GESTIONRRHH.INDECI_AFP_PARAMETRO_VIGENCIA ('
        || 'ID                       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
        || 'AFP_ID                   NUMBER        NOT NULL,'
        || 'PERIODO_INICIO           CHAR(6)       NOT NULL,'
        || 'PERIODO_FIN              CHAR(6),'
        || 'APORTE_OBLIGATORIO_PCT   NUMBER(6,4)   NOT NULL,'
        || 'COMISION_FLUJO_PCT       NUMBER(6,4)   DEFAULT 0 NOT NULL,'
        || 'COMISION_SALDO_ANUAL_PCT NUMBER(6,4)   DEFAULT 0 NOT NULL,'
        || 'PRIMA_SEGURO_PCT         NUMBER(6,4)   NOT NULL,'
        || 'REMUNERACION_MAXIMA_ASEG NUMBER(10,2)  NOT NULL,'
        || 'FUENTE_OFICIAL           VARCHAR2(200) NOT NULL,'
        || 'URL_FUENTE_OFICIAL       VARCHAR2(500),'
        || 'FECHA_PUBLICACION        DATE,'
        || 'OBSERVACION              VARCHAR2(500),'
        || 'ESTADO                   VARCHAR2(20)  DEFAULT ''VIGENTE'' NOT NULL,'
        || 'BLOQUEADO_POR_PLANILLA   NUMBER(1)     DEFAULT 0 NOT NULL,'
        || 'CREADO_POR               VARCHAR2(100) NOT NULL,'
        || 'CREADO_EN                TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,'
        || 'MODIFICADO_POR           VARCHAR2(100),'
        || 'MODIFICADO_EN            TIMESTAMP,'
        || 'CONSTRAINT INDECI_AFP_PV_AFP_FK     FOREIGN KEY (AFP_ID) REFERENCES GESTIONRRHH.INDECI_AFP(ID),'
        || 'CONSTRAINT INDECI_AFP_PV_ESTADO_CK  CHECK (ESTADO IN (''VIGENTE'',''PROGRAMADO'',''CERRADO'',''INACTIVO'')),'
        || 'CONSTRAINT INDECI_AFP_PV_BLOQUEO_CK CHECK (BLOQUEADO_POR_PLANILLA IN (0,1))'
        || ')'
    );

    crear_indice_si_falta(
        'INDECI_AFP_PV_AFP_ESTADO_IDX',
        'CREATE INDEX INDECI_AFP_PV_AFP_ESTADO_IDX ON GESTIONRRHH.INDECI_AFP_PARAMETRO_VIGENCIA(AFP_ID,ESTADO)'
    );
    crear_indice_si_falta(
        'INDECI_AFP_PV_PERIODO_IDX',
        'CREATE INDEX INDECI_AFP_PV_PERIODO_IDX ON GESTIONRRHH.INDECI_AFP_PARAMETRO_VIGENCIA(PERIODO_INICIO,PERIODO_FIN)'
    );

    -- ── 3. Parametros ONP por vigencia ──────────────────────
    crear_tabla_si_falta(
        'INDECI_ONP_PARAMETRO_VIGENCIA',
        'CREATE TABLE GESTIONRRHH.INDECI_ONP_PARAMETRO_VIGENCIA ('
        || 'ID                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
        || 'PERIODO_INICIO         CHAR(6)       NOT NULL,'
        || 'PERIODO_FIN            CHAR(6),'
        || 'APORTE_ONP_PCT         NUMBER(6,4)   NOT NULL,'
        || 'FUENTE_OFICIAL         VARCHAR2(200) NOT NULL,'
        || 'URL_FUENTE_OFICIAL     VARCHAR2(500),'
        || 'FECHA_PUBLICACION      DATE,'
        || 'OBSERVACION            VARCHAR2(500),'
        || 'ESTADO                 VARCHAR2(20)  DEFAULT ''VIGENTE'' NOT NULL,'
        || 'BLOQUEADO_POR_PLANILLA NUMBER(1)     DEFAULT 0 NOT NULL,'
        || 'CREADO_POR             VARCHAR2(100) NOT NULL,'
        || 'CREADO_EN              TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,'
        || 'MODIFICADO_POR         VARCHAR2(100),'
        || 'MODIFICADO_EN          TIMESTAMP,'
        || 'CONSTRAINT INDECI_ONP_PV_ESTADO_CK  CHECK (ESTADO IN (''VIGENTE'',''PROGRAMADO'',''CERRADO'',''INACTIVO'')),'
        || 'CONSTRAINT INDECI_ONP_PV_BLOQUEO_CK CHECK (BLOQUEADO_POR_PLANILLA IN (0,1))'
        || ')'
    );

    crear_indice_si_falta(
        'INDECI_ONP_PV_ESTADO_IDX',
        'CREATE INDEX INDECI_ONP_PV_ESTADO_IDX ON GESTIONRRHH.INDECI_ONP_PARAMETRO_VIGENCIA(ESTADO)'
    );
    crear_indice_si_falta(
        'INDECI_ONP_PV_PERIODO_IDX',
        'CREATE INDEX INDECI_ONP_PV_PERIODO_IDX ON GESTIONRRHH.INDECI_ONP_PARAMETRO_VIGENCIA(PERIODO_INICIO,PERIODO_FIN)'
    );

    -- ── 4. Log de auditoria ─────────────────────────────────
    crear_tabla_si_falta(
        'INDECI_PREVISIONAL_LOG',
        'CREATE TABLE GESTIONRRHH.INDECI_PREVISIONAL_LOG ('
        || 'ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
        || 'TIPO             VARCHAR2(10)  NOT NULL,'
        || 'AFP_ID           NUMBER,'
        || 'AFP_NOMBRE       VARCHAR2(100),'
        || 'ACCION           VARCHAR2(20)  NOT NULL,'
        || 'DESCRIPCION      VARCHAR2(500) NOT NULL,'
        || 'PERIODO_AFECTADO CHAR(6),'
        || 'USUARIO          VARCHAR2(100) NOT NULL,'
        || 'FECHA            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,'
        || 'CONSTRAINT INDECI_PREV_LOG_TIPO_CK   CHECK (TIPO   IN (''AFP'',''ONP'')),'
        || 'CONSTRAINT INDECI_PREV_LOG_ACCION_CK CHECK (ACCION IN (''CREAR'',''EDITAR'',''CERRAR'',''DUPLICAR''))'
        || ')'
    );

    crear_indice_si_falta(
        'INDECI_PREV_LOG_FECHA_IDX',
        'CREATE INDEX INDECI_PREV_LOG_FECHA_IDX ON GESTIONRRHH.INDECI_PREVISIONAL_LOG(FECHA)'
    );
    crear_indice_si_falta(
        'INDECI_PREV_LOG_TIPO_IDX',
        'CREATE INDEX INDECI_PREV_LOG_TIPO_IDX ON GESTIONRRHH.INDECI_PREVISIONAL_LOG(TIPO)'
    );

    -- ── 5. Seeds AFP catalogo (EXECUTE IMMEDIATE — tablas nuevas) ─
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM GESTIONRRHH.INDECI_AFP' INTO v_count;
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'INSERT INTO GESTIONRRHH.INDECI_AFP (CODIGO,NOMBRE,ACTIVO) VALUES (''HABITAT'',''AFP Habitat'',1)';
        EXECUTE IMMEDIATE 'INSERT INTO GESTIONRRHH.INDECI_AFP (CODIGO,NOMBRE,ACTIVO) VALUES (''INTEGRA'',''AFP Integra'',1)';
        EXECUTE IMMEDIATE 'INSERT INTO GESTIONRRHH.INDECI_AFP (CODIGO,NOMBRE,ACTIVO) VALUES (''PROFUTURO'',''AFP Profuturo'',1)';
        EXECUTE IMMEDIATE 'INSERT INTO GESTIONRRHH.INDECI_AFP (CODIGO,NOMBRE,ACTIVO) VALUES (''PRIMA'',''AFP Prima'',1)';
        DBMS_OUTPUT.PUT_LINE('Seeds AFP catalogo -> 4 filas insertadas.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('INDECI_AFP ya tiene datos. Seeds omitidos.');
    END IF;

    -- ── 6. Seeds AFP parametros vigentes 2026 (EXECUTE IMMEDIATE) ─
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM GESTIONRRHH.INDECI_AFP_PARAMETRO_VIGENCIA' INTO v_count;
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'INSERT INTO GESTIONRRHH.INDECI_AFP_PARAMETRO_VIGENCIA '
            || '(AFP_ID,PERIODO_INICIO,PERIODO_FIN,APORTE_OBLIGATORIO_PCT,COMISION_FLUJO_PCT,'
            || 'COMISION_SALDO_ANUAL_PCT,PRIMA_SEGURO_PCT,REMUNERACION_MAXIMA_ASEG,'
            || 'FUENTE_OFICIAL,ESTADO,CREADO_POR) '
            || 'VALUES ((SELECT ID FROM GESTIONRRHH.INDECI_AFP WHERE CODIGO=''HABITAT''),'
            || '''202601'',NULL,10.0000,0.3800,0.0000,1.7400,12537.00,'
            || '''SBS - Circular AFP-163-2025'',''VIGENTE'',''SISTEMA'')';

        EXECUTE IMMEDIATE
            'INSERT INTO GESTIONRRHH.INDECI_AFP_PARAMETRO_VIGENCIA '
            || '(AFP_ID,PERIODO_INICIO,PERIODO_FIN,APORTE_OBLIGATORIO_PCT,COMISION_FLUJO_PCT,'
            || 'COMISION_SALDO_ANUAL_PCT,PRIMA_SEGURO_PCT,REMUNERACION_MAXIMA_ASEG,'
            || 'FUENTE_OFICIAL,ESTADO,CREADO_POR) '
            || 'VALUES ((SELECT ID FROM GESTIONRRHH.INDECI_AFP WHERE CODIGO=''INTEGRA''),'
            || '''202601'',NULL,10.0000,0.6700,0.0000,1.7400,12537.00,'
            || '''SBS - Circular AFP-163-2025'',''VIGENTE'',''SISTEMA'')';

        EXECUTE IMMEDIATE
            'INSERT INTO GESTIONRRHH.INDECI_AFP_PARAMETRO_VIGENCIA '
            || '(AFP_ID,PERIODO_INICIO,PERIODO_FIN,APORTE_OBLIGATORIO_PCT,COMISION_FLUJO_PCT,'
            || 'COMISION_SALDO_ANUAL_PCT,PRIMA_SEGURO_PCT,REMUNERACION_MAXIMA_ASEG,'
            || 'FUENTE_OFICIAL,ESTADO,CREADO_POR) '
            || 'VALUES ((SELECT ID FROM GESTIONRRHH.INDECI_AFP WHERE CODIGO=''PROFUTURO''),'
            || '''202601'',NULL,10.0000,0.8700,0.0000,1.7400,12537.00,'
            || '''SBS - Circular AFP-163-2025'',''VIGENTE'',''SISTEMA'')';

        EXECUTE IMMEDIATE
            'INSERT INTO GESTIONRRHH.INDECI_AFP_PARAMETRO_VIGENCIA '
            || '(AFP_ID,PERIODO_INICIO,PERIODO_FIN,APORTE_OBLIGATORIO_PCT,COMISION_FLUJO_PCT,'
            || 'COMISION_SALDO_ANUAL_PCT,PRIMA_SEGURO_PCT,REMUNERACION_MAXIMA_ASEG,'
            || 'FUENTE_OFICIAL,ESTADO,CREADO_POR) '
            || 'VALUES ((SELECT ID FROM GESTIONRRHH.INDECI_AFP WHERE CODIGO=''PRIMA''),'
            || '''202601'',NULL,10.0000,0.1800,1.2500,1.7400,12537.00,'
            || '''SBS - Circular AFP-163-2025'',''VIGENTE'',''SISTEMA'')';

        DBMS_OUTPUT.PUT_LINE('Seeds AFP parametros -> 4 filas insertadas.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('INDECI_AFP_PARAMETRO_VIGENCIA ya tiene datos. Seeds omitidos.');
    END IF;

    -- ── 7. Seed ONP vigente (EXECUTE IMMEDIATE) ─────────────
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM GESTIONRRHH.INDECI_ONP_PARAMETRO_VIGENCIA' INTO v_count;
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'INSERT INTO GESTIONRRHH.INDECI_ONP_PARAMETRO_VIGENCIA '
            || '(PERIODO_INICIO,PERIODO_FIN,APORTE_ONP_PCT,FUENTE_OFICIAL,OBSERVACION,ESTADO,CREADO_POR) '
            || 'VALUES (''199301'',NULL,13.0000,'
            || '''Ley 19990 Art. 7 - D.S. 011-74-TR'','
            || '''Tasa historica. Vigente sin modificacion desde enero 1993.'''
            || ',''VIGENTE'',''SISTEMA'')';
        DBMS_OUTPUT.PUT_LINE('Seed ONP -> 1 fila insertada.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('INDECI_ONP_PARAMETRO_VIGENCIA ya tiene datos. Seed omitido.');
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('V010_70 finalizado correctamente.');

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR en V010_70: ' || SQLERRM);
        RAISE;
END;
/
