-- ============================================================================
-- Spec 010 / V010_10 — 4 tablas nuevas v2 (SPEC §10.3)
--
-- Habilita los módulos M03 (encargatura), M07 (descuento voluntario),
-- M13 (conciliación AIRHSP) y M14 (abono bancos + ticket MCPP).
--
-- TABLAS:
--   1. INDECI_EMPLEADO_ENCARGATURA   — titular ↔ reemplazante (Excel cols E/F)
--   2. INDECI_DESCUENTO_VOLUNTARIO   — 12 tipos SISPER (§6.4)
--   3. INDECI_CONCILIACION_AIRHSP    — monto sistema vs monto AIRHSP (M13)
--   4. INDECI_ABONO_BANCO            — archivo bancos + ticket MCPP (M14)
--
-- DECISIONES DE DISEÑO (alineadas con Etapa 1):
--   - Naming INDECI_* (no TBL_*) — coherencia local del schema.
--   - PKs IDENTITY (no SEQUENCE) — coherencia local.
--   - FKs: apuntan a INDECI_MOVIMIENTO_PLANILLA.ID (cabecera mensual) y a
--     INDECI_PERIODO_PLANILLA.ID (opción a confirmada por el usuario).
--   - Sin ON DELETE CASCADE: bajas son lógicas (ESTADO='INACTIVO'/'CULMINADO').
--   - CONCILIACION_AIRHSP.DIFERENCIA es columna VIRTUAL (Oracle 11g+):
--     se mantiene siempre = MONTO_SISTEMA - MONTO_AIRHSP, sin riesgo de drift.
--   - Sin USUARIO_CREO/USUARIO_MODIFICO: la auditoría sigue centralizada en
--     AuditoriaAspect (D.L. 1451).
--   - Sin seed: las filas las cargará el operador o V010_11 (sólo
--     descuento_voluntario recibe seed estructural allí).
--
-- DEFENSA EN PROFUNDIDAD:
--   - Procedimientos add_table_if_missing / add_index_if_missing.
--   - Re-ejecución segura: si todo existe, imprime "Sin cambios".
--   - Solo metadata + indices; sin tocar datos existentes.
--
-- Ejecutar en esquema GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;

    PROCEDURE add_table_if_missing(
        p_table_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO v_exists
          FROM ALL_TABLES
         WHERE OWNER      = 'GESTIONRRHH'
           AND TABLE_NAME = p_table_name;

        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl;
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' -> creada.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(
        p_index_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO v_exists
          FROM ALL_INDEXES
         WHERE OWNER      = 'GESTIONRRHH'
           AND INDEX_NAME = p_index_name;

        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl;
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' -> creado.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    -- ==================================================================
    -- 1) INDECI_EMPLEADO_ENCARGATURA
    -- ==================================================================
    add_table_if_missing(
        'INDECI_EMPLEADO_ENCARGATURA',
        'CREATE TABLE GESTIONRRHH.INDECI_EMPLEADO_ENCARGATURA ('
        ||   'ID                    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        ||   'EMPLEADO_TITULAR_ID   NUMBER NOT NULL,'
        ||   'EMPLEADO_ENCARG_ID    NUMBER NOT NULL,'
        ||   'FECHA_INICIO          DATE   NOT NULL,'
        ||   'FECHA_FIN             DATE,'
        ||   'RESOLUCION            VARCHAR2(50 CHAR),'
        ||   'ESTADO                VARCHAR2(10 CHAR) DEFAULT ''ACTIVO'' NOT NULL,'
        ||   'CREATED_AT            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CONSTRAINT INDECI_EMPL_ENCARG_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_EMPL_ENCARG_TIT_FK FOREIGN KEY (EMPLEADO_TITULAR_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_EMPLEADO (ID),'
        ||   'CONSTRAINT INDECI_EMPL_ENCARG_ENC_FK FOREIGN KEY (EMPLEADO_ENCARG_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_EMPLEADO (ID),'
        ||   'CONSTRAINT INDECI_EMPL_ENCARG_ESTADO_CK '
        ||     'CHECK (ESTADO IN (''ACTIVO'', ''CULMINADO'')),'
        ||   'CONSTRAINT INDECI_EMPL_ENCARG_FECHAS_CK '
        ||     'CHECK (FECHA_FIN IS NULL OR FECHA_FIN >= FECHA_INICIO),'
        ||   'CONSTRAINT INDECI_EMPL_ENCARG_DISTINTO_CK '
        ||     'CHECK (EMPLEADO_TITULAR_ID <> EMPLEADO_ENCARG_ID)'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_EMPL_ENCARG_TIT',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_EMPL_ENCARG_TIT '
        || 'ON GESTIONRRHH.INDECI_EMPLEADO_ENCARGATURA (EMPLEADO_TITULAR_ID, ESTADO)'
    );
    add_index_if_missing(
        'IX_INDECI_EMPL_ENCARG_ENC',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_EMPL_ENCARG_ENC '
        || 'ON GESTIONRRHH.INDECI_EMPLEADO_ENCARGATURA (EMPLEADO_ENCARG_ID, ESTADO)'
    );

    -- ==================================================================
    -- 2) INDECI_DESCUENTO_VOLUNTARIO
    -- ==================================================================
    add_table_if_missing(
        'INDECI_DESCUENTO_VOLUNTARIO',
        'CREATE TABLE GESTIONRRHH.INDECI_DESCUENTO_VOLUNTARIO ('
        ||   'ID                     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        ||   'EMPLEADO_ID            NUMBER NOT NULL,'
        ||   'CODIGO_SISPER          VARCHAR2(10 CHAR) NOT NULL,'
        ||   'CONCEPTO_PLANILLA_ID   NUMBER NOT NULL,'
        ||   'MONTO_MENSUAL          NUMBER(12,2) NOT NULL,'
        ||   'FECHA_INICIO           DATE NOT NULL,'
        ||   'FECHA_FIN              DATE,'
        ||   'ESTADO                 VARCHAR2(10 CHAR) DEFAULT ''ACTIVO'' NOT NULL,'
        ||   'CREATED_AT             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CONSTRAINT INDECI_DESC_VOL_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_DESC_VOL_EMP_FK FOREIGN KEY (EMPLEADO_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_EMPLEADO (ID),'
        ||   'CONSTRAINT INDECI_DESC_VOL_CON_FK FOREIGN KEY (CONCEPTO_PLANILLA_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_CONCEPTO_PLANILLA (ID),'
        ||   'CONSTRAINT INDECI_DESC_VOL_ESTADO_CK '
        ||     'CHECK (ESTADO IN (''ACTIVO'', ''INACTIVO'')),'
        ||   'CONSTRAINT INDECI_DESC_VOL_MONTO_CK '
        ||     'CHECK (MONTO_MENSUAL >= 0),'
        ||   'CONSTRAINT INDECI_DESC_VOL_FECHAS_CK '
        ||     'CHECK (FECHA_FIN IS NULL OR FECHA_FIN >= FECHA_INICIO)'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_DESC_VOL_EMP_ESTADO',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_DESC_VOL_EMP_ESTADO '
        || 'ON GESTIONRRHH.INDECI_DESCUENTO_VOLUNTARIO (EMPLEADO_ID, ESTADO)'
    );
    add_index_if_missing(
        'IX_INDECI_DESC_VOL_CON',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_DESC_VOL_CON '
        || 'ON GESTIONRRHH.INDECI_DESCUENTO_VOLUNTARIO (CONCEPTO_PLANILLA_ID)'
    );

    -- ==================================================================
    -- 3) INDECI_CONCILIACION_AIRHSP (M13)
    -- ==================================================================
    add_table_if_missing(
        'INDECI_CONCILIACION_AIRHSP',
        'CREATE TABLE GESTIONRRHH.INDECI_CONCILIACION_AIRHSP ('
        ||   'ID                      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        ||   'EMPLEADO_ID             NUMBER NOT NULL,'
        ||   'MOVIMIENTO_PLANILLA_ID  NUMBER NOT NULL,'
        ||   'PERIODO_PLANILLA_ID     NUMBER NOT NULL,'
        ||   'MONTO_SISTEMA           NUMBER(12,2) NOT NULL,'
        ||   'MONTO_AIRHSP            NUMBER(12,2) NOT NULL,'
        ||   'DIFERENCIA              NUMBER(12,2) GENERATED ALWAYS AS '
        ||                            '(MONTO_SISTEMA - MONTO_AIRHSP) VIRTUAL,'
        ||   'ESTADO                  VARCHAR2(15 CHAR) DEFAULT ''PENDIENTE'' NOT NULL,'
        ||   'JUSTIFICACION           VARCHAR2(500 CHAR),'
        ||   'USUARIO_REVISA          NUMBER,'
        ||   'FECHA_REVISION          DATE,'
        ||   'CREATED_AT              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CONSTRAINT INDECI_CONC_AIRHSP_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_CONC_AIRHSP_EMP_FK FOREIGN KEY (EMPLEADO_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_EMPLEADO (ID),'
        ||   'CONSTRAINT INDECI_CONC_AIRHSP_MOV_FK FOREIGN KEY (MOVIMIENTO_PLANILLA_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_MOVIMIENTO_PLANILLA (ID),'
        ||   'CONSTRAINT INDECI_CONC_AIRHSP_PER_FK FOREIGN KEY (PERIODO_PLANILLA_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_PERIODO_PLANILLA (ID),'
        ||   'CONSTRAINT INDECI_CONC_AIRHSP_ESTADO_CK '
        ||     'CHECK (ESTADO IN (''PENDIENTE'', ''CONCILIADO'', ''JUSTIFICADO'', ''RECHAZADO'')),'
        ||   'CONSTRAINT INDECI_CONC_AIRHSP_UK '
        ||     'UNIQUE (MOVIMIENTO_PLANILLA_ID, EMPLEADO_ID)'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_CONC_AIRHSP_PER_EST',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_CONC_AIRHSP_PER_EST '
        || 'ON GESTIONRRHH.INDECI_CONCILIACION_AIRHSP (PERIODO_PLANILLA_ID, ESTADO)'
    );
    add_index_if_missing(
        'IX_INDECI_CONC_AIRHSP_EMP',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_CONC_AIRHSP_EMP '
        || 'ON GESTIONRRHH.INDECI_CONCILIACION_AIRHSP (EMPLEADO_ID)'
    );

    -- ==================================================================
    -- 4) INDECI_ABONO_BANCO (M14)
    -- ==================================================================
    add_table_if_missing(
        'INDECI_ABONO_BANCO',
        'CREATE TABLE GESTIONRRHH.INDECI_ABONO_BANCO ('
        ||   'ID                      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        ||   'MOVIMIENTO_PLANILLA_ID  NUMBER NOT NULL,'
        ||   'EMPLEADO_ID             NUMBER NOT NULL,'
        ||   'BANCO                   VARCHAR2(30 CHAR) NOT NULL,'
        ||   'NRO_CUENTA              VARCHAR2(30 CHAR),'
        ||   'CCI                     VARCHAR2(20 CHAR),'
        ||   'META                    VARCHAR2(10 CHAR),'
        ||   'MONTO_NETO              NUMBER(12,2) NOT NULL,'
        ||   'ESTADO                  VARCHAR2(15 CHAR) DEFAULT ''PENDIENTE'' NOT NULL,'
        ||   'NRO_TICKET_MCPP         VARCHAR2(20 CHAR),'
        ||   'FECHA_PROCESADO         DATE,'
        ||   'CREATED_AT              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CONSTRAINT INDECI_ABONO_BANCO_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_ABONO_BANCO_MOV_FK FOREIGN KEY (MOVIMIENTO_PLANILLA_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_MOVIMIENTO_PLANILLA (ID),'
        ||   'CONSTRAINT INDECI_ABONO_BANCO_EMP_FK FOREIGN KEY (EMPLEADO_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_EMPLEADO (ID),'
        ||   'CONSTRAINT INDECI_ABONO_BANCO_ESTADO_CK '
        ||     'CHECK (ESTADO IN (''PENDIENTE'', ''PROCESADO'', ''RECHAZADO'')),'
        ||   'CONSTRAINT INDECI_ABONO_BANCO_MONTO_CK '
        ||     'CHECK (MONTO_NETO >= 0),'
        ||   'CONSTRAINT INDECI_ABONO_BANCO_UK '
        ||     'UNIQUE (MOVIMIENTO_PLANILLA_ID, EMPLEADO_ID)'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_ABONO_MOV_BANCO',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_ABONO_MOV_BANCO '
        || 'ON GESTIONRRHH.INDECI_ABONO_BANCO (MOVIMIENTO_PLANILLA_ID, BANCO)'
    );
    add_index_if_missing(
        'IX_INDECI_ABONO_BANCO_ESTADO',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_ABONO_BANCO_ESTADO '
        || 'ON GESTIONRRHH.INDECI_ABONO_BANCO (BANCO, ESTADO)'
    );

    -- ==================================================================
    -- COMMENTS por tabla y columnas críticas (idempotente — Oracle sobrescribe)
    -- ==================================================================
    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_EMPLEADO_ENCARGATURA IS '
        || '''SPEC §10.3 — Relación titular ↔ reemplazante (Excel cols E/F). '
        || 'Un titular puede tener varios encargados a lo largo del tiempo.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_ENCARGATURA.EMPLEADO_TITULAR_ID IS '
        || '''Empleado en su cargo original (titular de la plaza).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_ENCARGATURA.EMPLEADO_ENCARG_ID IS '
        || '''Empleado que cubre temporalmente al titular.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_ENCARGATURA.ESTADO IS '
        || '''ACTIVO | CULMINADO — baja lógica al finalizar la encargatura.''';

    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_DESCUENTO_VOLUNTARIO IS '
        || '''SPEC §10.3 / §6.4 — Descuentos voluntarios del empleado (12 tipos SISPER). '
        || 'Alimentado por V010_11 (seed estructural) y por mantenimiento del operador.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_DESCUENTO_VOLUNTARIO.CODIGO_SISPER IS '
        || '''Código SISPER del descuento (ej: ''''735'''', ''''722''''). Espejo de INDECI_CONCEPTO_PLANILLA.CODIGO_SISPER.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_DESCUENTO_VOLUNTARIO.MONTO_MENSUAL IS '
        || '''Monto fijo descontado cada planilla mientras esté ACTIVO y dentro del rango FECHA_INICIO..FECHA_FIN.''';

    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_CONCILIACION_AIRHSP IS '
        || '''SPEC §10.3 / M13 — Conciliación monto sistema vs monto AIRHSP por empleado y movimiento. '
        || 'PANTALLA-06 lo consume; planilla no avanza si hay PENDIENTE / RECHAZADO.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_CONCILIACION_AIRHSP.MONTO_SISTEMA IS '
        || '''Monto calculado por el motor de planilla (Etapa 1+).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_CONCILIACION_AIRHSP.MONTO_AIRHSP IS '
        || '''Monto vigente en AIRHSP (de INDECI_EMPLEADO.AIRHSP_MONTO o equivalente).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_CONCILIACION_AIRHSP.DIFERENCIA IS '
        || '''Columna VIRTUAL = MONTO_SISTEMA - MONTO_AIRHSP. Nunca puede divergir.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_CONCILIACION_AIRHSP.ESTADO IS '
        || '''PENDIENTE | CONCILIADO | JUSTIFICADO | RECHAZADO — flujo de revisión en PANTALLA-06.''';

    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_ABONO_BANCO IS '
        || '''SPEC §10.3 / M14 — Filas que alimentan el archivo de carga bancaria y el ticket MCPP. '
        || 'PANTALLA-07 expone resumen por banco + descarga TXT.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_ABONO_BANCO.BANCO IS '
        || '''BCP | BBVA | SCOTIABANK | BANBIF | INTERBANK | B.NACION — valores libres por ahora (sin FK a catálogo).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_ABONO_BANCO.NRO_TICKET_MCPP IS '
        || '''Número de ticket MCPP ingresado por Tesorería al confirmar pago. Cambia ESTADO a PROCESADO.''';

    DBMS_OUTPUT.PUT_LINE('V010_10 finalizado.');

    -- Reporte final
    SELECT COUNT(*) INTO v_count
      FROM ALL_TABLES
     WHERE OWNER      = 'GESTIONRRHH'
       AND TABLE_NAME IN (
           'INDECI_EMPLEADO_ENCARGATURA',
           'INDECI_DESCUENTO_VOLUNTARIO',
           'INDECI_CONCILIACION_AIRHSP',
           'INDECI_ABONO_BANCO');
    DBMS_OUTPUT.PUT_LINE('Tablas v2 presentes ahora en GESTIONRRHH: ' || v_count || ' / 4.');
END;
/
