-- ============================================================================
-- Spec 010 / V010_111 — INDECI_EMPLEADO_OTROS_INGRESOS
-- Tabla para registrar ingresos de quinta categoría obtenidos de otros empleadores
-- y retenciones efectuadas, necesario para calcular IR5TA de servidores que
-- laboran en más de una entidad pública o privada.
-- Ejecutar en esquema GESTIONRRHH / Oracle.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;
    v_ts VARCHAR2(30);
BEGIN
    -- Determinar un tablespace válido existente en el esquema
    SELECT MAX(tablespace_name) INTO v_ts FROM all_tables WHERE owner = 'GESTIONRRHH' AND tablespace_name IS NOT NULL;
    IF v_ts IS NULL THEN 
        v_ts := 'USERS'; 
    END IF;

    SELECT count(*) INTO v_count FROM all_tables WHERE owner = 'GESTIONRRHH' AND table_name = 'INDECI_EMPLEADO_OTROS_INGRESOS';
    
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
        'CREATE TABLE GESTIONRRHH.INDECI_EMPLEADO_OTROS_INGRESOS (
            ID                   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            EMPLEADO_ID          NUMBER             NOT NULL,
            ANIO_FISCAL          NUMBER(4)          NOT NULL,
            MONTO_INGRESOS       NUMBER(18,6)       NOT NULL,
            MONTO_RETENCIONES    NUMBER(18,6)       NOT NULL,
            ACTIVO               NUMBER(1)          DEFAULT 1 NOT NULL,
            CREATED_AT           TIMESTAMP          DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT INDECI_EMP_OTROS_ING_UK
                UNIQUE (EMPLEADO_ID, ANIO_FISCAL, ACTIVO),
            CONSTRAINT INDECI_EMP_OTROS_ING_FK
                FOREIGN KEY (EMPLEADO_ID) REFERENCES GESTIONRRHH.INDECI_EMPLEADO(ID),
            CONSTRAINT INDECI_EMP_OTROS_ING_M_CK
                CHECK (MONTO_INGRESOS >= 0 AND MONTO_RETENCIONES >= 0 AND MONTO_RETENCIONES <= MONTO_INGRESOS),
            CONSTRAINT INDECI_EMP_OTROS_ING_ACT_CK
                CHECK (ACTIVO IN (0, 1))
        ) TABLESPACE ' || v_ts;
        
        DBMS_OUTPUT.PUT_LINE('Tabla INDECI_EMPLEADO_OTROS_INGRESOS creada en tablespace: ' || v_ts);

        EXECUTE IMMEDIATE 'CREATE INDEX GESTIONRRHH.IX_INDECI_EMP_OTROS_ING_EMP ON GESTIONRRHH.INDECI_EMPLEADO_OTROS_INGRESOS (EMPLEADO_ID) TABLESPACE ' || v_ts;
        
        EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_EMPLEADO_OTROS_INGRESOS IS ''Registra los ingresos y retenciones de quinta categoría que el empleado recibe de otros empleadores en un año fiscal.''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_OTROS_INGRESOS.EMPLEADO_ID IS ''FK al empleado principal.''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_OTROS_INGRESOS.ANIO_FISCAL IS ''Año fiscal al que corresponde el registro.''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_OTROS_INGRESOS.MONTO_INGRESOS IS ''Suma total de remuneraciones percibidas de otros empleadores en el año.''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_OTROS_INGRESOS.MONTO_RETENCIONES IS ''Suma total de retenciones de 5ta categoría efectuadas por otros empleadores en el año.''';
    ELSE
        DBMS_OUTPUT.PUT_LINE('La tabla INDECI_EMPLEADO_OTROS_INGRESOS ya existe.');
    END IF;
END;
/

-- ============================================================================
-- Seed de Parámetros: IR5TA_FACTOR_DEDUCCION
-- ============================================================================
MERGE INTO GESTIONRRHH.INDECI_PARAMETRO_REMUNERATIVO d
USING (
    SELECT 'IR5TA_FACTOR_DEDUCCION' AS CODIGO_PARAMETRO,
           2026                     AS ANIO_FISCAL,
           NULL                     AS REGIMEN_LABORAL_ID,
           7.000000                 AS VALOR_NUMERICO,
           NULL                     AS UNIDAD
      FROM DUAL
) s
ON (
    d.CODIGO_PARAMETRO = s.CODIGO_PARAMETRO
    AND d.ANIO_FISCAL  = s.ANIO_FISCAL
    AND d.REGIMEN_LABORAL_ID IS NULL
)
WHEN NOT MATCHED THEN INSERT (
    CODIGO_PARAMETRO, ANIO_FISCAL, REGIMEN_LABORAL_ID, VALOR_NUMERICO, UNIDAD, FECHA_VIG_INI, ACTIVO
) VALUES (
    s.CODIGO_PARAMETRO, s.ANIO_FISCAL, s.REGIMEN_LABORAL_ID, s.VALOR_NUMERICO, s.UNIDAD, DATE '2026-01-01', 1
);

COMMIT;
