-- ============================================================================
-- F2.1 / V010_43 — INDECI_TIPO_EVENTO + INDECI_EMPLEADO_EVENTO
--
-- OBJETIVO:
--   Modelar eventos del período que afectan la planilla del empleado:
--   maternidad, enfermedad, licencias, lactancia, paternidad, cese, reintegro,
--   permiso personal, feriado compensable. Hoy el motor solo descuenta días
--   por FALTA (de AsistenciaCabecera) — con F2 también restará días por
--   eventos según el flag AFECTA_DIAS_LABORADOS del tipo.
--
--   Subsidios (maternidad/enfermedad) se calculan en F2.4
--   (SubsidioCalculadorService) usando el promedio de los últimos 12 meses
--   y la diferencia INDECI vs EsSalud.
--
-- DECISIONES DE DISEÑO:
--   - INDECI_TIPO_EVENTO catálogo, con flags por tipo:
--       AFECTA_DIAS_LABORADOS  S/N — resta del default 30 (motor PASO 3)
--       AFECTA_BASE_AFP        S/N — afecta base pensión
--       AFECTA_BASE_ESSALUD    S/N — afecta base ESSALUD
--       GENERA_SUBSIDIO        S/N — dispara SubsidioCalculadorService
--       REQUIERE_ADJUNTO       S/N — Legajo+FTP en F2.6
--       PERMITE_SOLAPE         S/N — lactancia parcial puede solapar maternidad
--   - INDECI_EMPLEADO_EVENTO transaccional:
--       PERIODO VARCHAR2(6) (YYYYMM) coherente con resto del schema.
--       DIAS_AFECTOS derivado por default (fechaFin-fechaInicio+1) pero el
--           usuario puede sobrescribir (días no laborables, casos especiales).
--       SUSTENTO_LEGAJO_DOC_ID FK a INDECI_LEGAJO_DOCUMENTO (V010_35), nullable
--           — el motor no exige adjunto; el service lo exigirá según
--           TipoEvento.requiereAdjunto.
--       ESTADO REGISTRADO|VALIDADO|RECHAZADO — flujo de aprobación queda en UI.
--   - UK por (EMPLEADO_ID, TIPO_EVENTO_ID, FECHA_INICIO) — evita duplicados
--       exactos. Solape de fechas se valida en la app (más flexible).
--   - Tablespace explícito vía INDECI_EMPLEADO (patrón establecido).
--
-- IDEMPOTENTE. Schema NO hardcodeado. Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

-- ----------------------------------------------------------------------------
-- 1) Tablas nuevas con tablespace explícito.
-- ----------------------------------------------------------------------------
DECLARE
    v_ts VARCHAR2(30);
    PROCEDURE add_table_if_missing(
        p_table_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_TABLES
         WHERE TABLE_NAME = p_table_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    add_table_if_missing(
        'INDECI_TIPO_EVENTO',
        'CREATE TABLE INDECI_TIPO_EVENTO ('
        ||   'ID                       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,'
        ||   'CODIGO                   VARCHAR2(30 CHAR) NOT NULL,'
        ||   'NOMBRE                   VARCHAR2(100 CHAR) NOT NULL,'
        ||   'AFECTA_DIAS_LABORADOS    VARCHAR2(1 CHAR) DEFAULT ''N'' NOT NULL,'
        ||   'AFECTA_BASE_AFP          VARCHAR2(1 CHAR) DEFAULT ''S'' NOT NULL,'
        ||   'AFECTA_BASE_ESSALUD      VARCHAR2(1 CHAR) DEFAULT ''S'' NOT NULL,'
        ||   'GENERA_SUBSIDIO          VARCHAR2(1 CHAR) DEFAULT ''N'' NOT NULL,'
        ||   'REQUIERE_ADJUNTO         VARCHAR2(1 CHAR) DEFAULT ''N'' NOT NULL,'
        ||   'PERMITE_SOLAPE           VARCHAR2(1 CHAR) DEFAULT ''N'' NOT NULL,'
        ||   'CODIGO_PLAME_SUNAT       VARCHAR2(6 CHAR),'
        ||   'ORDEN_VISUAL             NUMBER(3) DEFAULT 100 NOT NULL,'
        ||   'ACTIVO                   NUMBER(1) DEFAULT 1 NOT NULL,'
        ||   'CREATED_AT               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CONSTRAINT INDECI_TIPO_EVENTO_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_TIPO_EVENTO_CODIGO_UK UNIQUE (CODIGO),'
        ||   'CONSTRAINT INDECI_TIPO_EVENTO_AFEC_DIAS_CK CHECK (AFECTA_DIAS_LABORADOS IN (''S'',''N'')),'
        ||   'CONSTRAINT INDECI_TIPO_EVENTO_AFEC_AFP_CK  CHECK (AFECTA_BASE_AFP IN (''S'',''N'')),'
        ||   'CONSTRAINT INDECI_TIPO_EVENTO_AFEC_ESS_CK  CHECK (AFECTA_BASE_ESSALUD IN (''S'',''N'')),'
        ||   'CONSTRAINT INDECI_TIPO_EVENTO_SUBS_CK      CHECK (GENERA_SUBSIDIO IN (''S'',''N'')),'
        ||   'CONSTRAINT INDECI_TIPO_EVENTO_ADJ_CK       CHECK (REQUIERE_ADJUNTO IN (''S'',''N'')),'
        ||   'CONSTRAINT INDECI_TIPO_EVENTO_SOLAPE_CK    CHECK (PERMITE_SOLAPE IN (''S'',''N'')),'
        ||   'CONSTRAINT INDECI_TIPO_EVENTO_ACTIVO_CK    CHECK (ACTIVO IN (0,1))'
        || ')'
    );

    add_table_if_missing(
        'INDECI_EMPLEADO_EVENTO',
        'CREATE TABLE INDECI_EMPLEADO_EVENTO ('
        ||   'ID                       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,'
        ||   'EMPLEADO_ID              NUMBER(10) NOT NULL,'
        ||   'TIPO_EVENTO_ID           NUMBER(10) NOT NULL,'
        ||   'PERIODO                  VARCHAR2(6 CHAR),'
        ||   'FECHA_INICIO             DATE NOT NULL,'
        ||   'FECHA_FIN                DATE NOT NULL,'
        ||   'DIAS_AFECTOS             NUMBER(3),'
        ||   'SUSTENTO_LEGAJO_DOC_ID   NUMBER(10),'
        ||   'OBSERVACION              VARCHAR2(500 CHAR),'
        ||   'ESTADO                   VARCHAR2(20 CHAR) DEFAULT ''REGISTRADO'' NOT NULL,'
        ||   'ACTIVO                   NUMBER(1) DEFAULT 1 NOT NULL,'
        ||   'CREATED_AT               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CREATED_BY               VARCHAR2(60 CHAR),'
        ||   'CONSTRAINT INDECI_EMP_EVENTO_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT FK_EMP_EVENTO_EMPLEADO '
        ||      'FOREIGN KEY (EMPLEADO_ID) REFERENCES INDECI_EMPLEADO (ID),'
        ||   'CONSTRAINT FK_EMP_EVENTO_TIPO '
        ||      'FOREIGN KEY (TIPO_EVENTO_ID) REFERENCES INDECI_TIPO_EVENTO (ID),'
        ||   'CONSTRAINT FK_EMP_EVENTO_LEGAJO '
        ||      'FOREIGN KEY (SUSTENTO_LEGAJO_DOC_ID) REFERENCES INDECI_LEGAJO_DOCUMENTO (ID),'
        ||   'CONSTRAINT INDECI_EMP_EVENTO_ACTIVO_CK CHECK (ACTIVO IN (0,1)),'
        ||   'CONSTRAINT INDECI_EMP_EVENTO_FECHAS_CK CHECK (FECHA_FIN >= FECHA_INICIO),'
        ||   'CONSTRAINT INDECI_EMP_EVENTO_ESTADO_CK '
        ||      'CHECK (ESTADO IN (''REGISTRADO'',''VALIDADO'',''RECHAZADO''))'
        || ')'
    );

    EXECUTE IMMEDIATE 'COMMENT ON TABLE INDECI_TIPO_EVENTO IS '
        || '''F2.1 — Catálogo de tipos de evento del período (maternidad, licencias, cese, etc.) con flags que controlan el motor de planilla.''';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE INDECI_EMPLEADO_EVENTO IS '
        || '''F2.1 — Eventos del período del empleado. El motor PASO 3 consume AFECTA_DIAS_LABORADOS; F2.4 SubsidioCalculadorService consume GENERA_SUBSIDIO.''';
END;
/

-- ----------------------------------------------------------------------------
-- 2) UK INDECI_EMP_EVENTO_UK — (EMPLEADO_ID, TIPO_EVENTO_ID, FECHA_INICIO).
--    Patrón CREATE UNIQUE INDEX + ADD CONSTRAINT USING INDEX
--    (ver V010_39 — evita ORA-00959 por default tablespace).
-- ----------------------------------------------------------------------------
DECLARE
    v_ts                VARCHAR2(30);
    v_constraint_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_constraint_exists
      FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_NAME = 'INDECI_EMP_EVENTO_UK';

    IF v_constraint_exists > 0 THEN
        DBMS_OUTPUT.PUT_LINE('INDECI_EMP_EVENTO_UK ya existe. Sin cambios.');
        RETURN;
    END IF;

    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    BEGIN
        EXECUTE IMMEDIATE 'DROP INDEX INDECI_EMP_EVENTO_UK';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -1418 THEN NULL; ELSE RAISE; END IF;
    END;

    EXECUTE IMMEDIATE
        'CREATE UNIQUE INDEX INDECI_EMP_EVENTO_UK '
        || 'ON INDECI_EMPLEADO_EVENTO (EMPLEADO_ID, TIPO_EVENTO_ID, FECHA_INICIO) '
        || 'TABLESPACE ' || v_ts;
    EXECUTE IMMEDIATE
        'ALTER TABLE INDECI_EMPLEADO_EVENTO '
        || 'ADD CONSTRAINT INDECI_EMP_EVENTO_UK '
        || 'UNIQUE (EMPLEADO_ID, TIPO_EVENTO_ID, FECHA_INICIO) '
        || 'USING INDEX INDECI_EMP_EVENTO_UK';
    DBMS_OUTPUT.PUT_LINE('INDECI_EMP_EVENTO_UK -> creado en TBS ' || v_ts);
END;
/

-- ----------------------------------------------------------------------------
-- 3) Índices de soporte para queries del motor y del repo.
-- ----------------------------------------------------------------------------
DECLARE
    v_ts VARCHAR2(30);
    PROCEDURE add_ix_if_missing(
        p_index_name VARCHAR2,
        p_table_name VARCHAR2,
        p_columns    VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_INDEXES
         WHERE INDEX_NAME = p_index_name;
        IF v_exists > 0 THEN
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' ya existe. Sin cambios.');
            RETURN;
        END IF;
        EXECUTE IMMEDIATE
            'CREATE INDEX ' || p_index_name
            || ' ON ' || p_table_name || ' ' || p_columns
            || ' TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE(p_index_name || ' -> creado en TBS ' || v_ts);
    END;
BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    -- Motor PASO 3: busca eventos vigentes por empleado + período activos.
    add_ix_if_missing(
        'INDECI_EMP_EVENTO_EMP_PER_IX',
        'INDECI_EMPLEADO_EVENTO',
        '(EMPLEADO_ID, PERIODO, ACTIVO)'
    );
    -- Repo: listar eventos por empleado (timeline).
    add_ix_if_missing(
        'INDECI_EMP_EVENTO_EMP_IX',
        'INDECI_EMPLEADO_EVENTO',
        '(EMPLEADO_ID, ACTIVO)'
    );
    -- Solape: búsqueda por rango de fechas para validador no-solape.
    add_ix_if_missing(
        'INDECI_EMP_EVENTO_FECHAS_IX',
        'INDECI_EMPLEADO_EVENTO',
        '(EMPLEADO_ID, FECHA_INICIO, FECHA_FIN, ACTIVO)'
    );
END;
/

-- ----------------------------------------------------------------------------
-- 4) Seed catálogo INDECI_TIPO_EVENTO (idempotente, MERGE).
--    Flags por tipo según normativa peruana:
--
--    AFECTA_DIAS_LAB: ¿resta del default 30 que cuenta el motor?
--      MATERNIDAD/ENFERMEDAD: S (no labora durante el descanso, días subsidiados)
--      LICENCIA_GOCE: N (con goce → laborado fiscal, no descuenta)
--      LICENCIA_SIN_GOCE: S
--      LACTANCIA: N (es 1 hora diaria, no día completo)
--      PATERNIDAD: N (licencia con goce de haber)
--      CESE: S (días desde fechaCese hasta fin de mes no laborados)
--      REINTEGRO: N (es un "+ días", lo maneja F1.4 INDECI_EMPLEADO_REINTEGRO)
--      FERIADO_COMPENSABLE: N (es día compensado)
--      PERMISO_PERSONAL: S
--      FALTA_INJUSTIFICADA: S (alternativa a AsistenciaCabecera.diasFalta)
--
--    AFECTA_BASE_AFP / AFECTA_BASE_ESSALUD: S por default (la base se mantiene
--      durante eventos remunerados). Maternidad/enfermedad: el SUBSIDIO no afecta
--      base — pero esto se maneja en F2.4 (SubsidioCalculadorService), no aquí.
--
--    GENERA_SUBSIDIO: solo MATERNIDAD y ENFERMEDAD.
--
--    REQUIERE_ADJUNTO: maternidad, enfermedad, licencias, suspensión, cese
--      (siempre hay constancia/certificado).
--
--    PERMITE_SOLAPE: solo LACTANCIA (parcial puede solapar maternidad).
-- ----------------------------------------------------------------------------
MERGE INTO INDECI_TIPO_EVENTO d
USING (
    SELECT 'MATERNIDAD'           AS CODIGO, 'Subsidio por Maternidad'        AS NOMBRE,
           'S' AS AFECTA_DIAS_LABORADOS, 'S' AS AFECTA_BASE_AFP, 'S' AS AFECTA_BASE_ESSALUD,
           'S' AS GENERA_SUBSIDIO, 'S' AS REQUIERE_ADJUNTO, 'N' AS PERMITE_SOLAPE,
           10  AS ORDEN_VISUAL FROM DUAL UNION ALL
    SELECT 'ENFERMEDAD',           'Subsidio por Enfermedad',
           'S','S','S','S','S','N', 20 FROM DUAL UNION ALL
    SELECT 'LICENCIA_GOCE',        'Licencia con goce de haber',
           'N','S','S','N','S','N', 30 FROM DUAL UNION ALL
    SELECT 'LICENCIA_SIN_GOCE',    'Licencia sin goce de haber',
           'S','N','N','N','S','N', 40 FROM DUAL UNION ALL
    SELECT 'LACTANCIA',            'Permiso de Lactancia (Ley 27240)',
           'N','S','S','N','N','S', 50 FROM DUAL UNION ALL
    SELECT 'PATERNIDAD',           'Licencia por Paternidad (Ley 29409)',
           'N','S','S','N','S','N', 60 FROM DUAL UNION ALL
    SELECT 'CESE',                 'Cese laboral',
           'S','N','N','N','S','N', 70 FROM DUAL UNION ALL
    SELECT 'REINTEGRO',            'Reintegro por días (informativo)',
           'N','S','S','N','N','N', 80 FROM DUAL UNION ALL
    SELECT 'FERIADO_COMPENSABLE',  'Feriado compensable',
           'N','S','S','N','N','N', 90 FROM DUAL UNION ALL
    SELECT 'PERMISO_PERSONAL',     'Permiso personal sin goce',
           'S','N','N','N','S','N', 100 FROM DUAL
) s
ON (d.CODIGO = s.CODIGO)
WHEN NOT MATCHED THEN
    INSERT (CODIGO, NOMBRE,
            AFECTA_DIAS_LABORADOS, AFECTA_BASE_AFP, AFECTA_BASE_ESSALUD,
            GENERA_SUBSIDIO, REQUIERE_ADJUNTO, PERMITE_SOLAPE,
            ORDEN_VISUAL, ACTIVO, CREATED_AT)
    VALUES (s.CODIGO, s.NOMBRE,
            s.AFECTA_DIAS_LABORADOS, s.AFECTA_BASE_AFP, s.AFECTA_BASE_ESSALUD,
            s.GENERA_SUBSIDIO, s.REQUIERE_ADJUNTO, s.PERMITE_SOLAPE,
            s.ORDEN_VISUAL, 1, SYSTIMESTAMP);

COMMIT;

-- ----------------------------------------------------------------------------
-- 5) Verificación rápida.
-- ----------------------------------------------------------------------------
DECLARE
    v_tipos       NUMBER;
    v_eventos     NUMBER;
    v_uk_existe   NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_tipos
      FROM INDECI_TIPO_EVENTO
     WHERE ACTIVO = 1;
    SELECT COUNT(*) INTO v_eventos
      FROM INDECI_EMPLEADO_EVENTO;
    SELECT COUNT(*) INTO v_uk_existe
      FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_NAME = 'INDECI_EMP_EVENTO_UK';

    DBMS_OUTPUT.PUT_LINE('---');
    DBMS_OUTPUT.PUT_LINE('Tipos de evento activos     : ' || v_tipos     || ' (esperado 10)');
    DBMS_OUTPUT.PUT_LINE('INDECI_EMPLEADO_EVENTO filas: ' || v_eventos   || ' (esperado 0 fresh install)');
    DBMS_OUTPUT.PUT_LINE('UK INDECI_EMP_EVENTO_UK     : ' || v_uk_existe || ' (esperado 1)');
    DBMS_OUTPUT.PUT_LINE('V010_43 listo.');
END;
/
