-- ============================================================================
-- FASE 2 / V010_55 — Snapshot de trazabilidad del cálculo de planilla
--
-- Guarda, por (EMPLEADO_ID, PERIODO, REGLA), los PARÁMETROS y MAGNITUDES que el
-- motor usó para obtener una retención/cálculo, de modo que la pantalla de
-- explicación pueda responder "¿cómo se obtuvo S/ X?" sin recalcular y la
-- auditoría (D.L. 1451) tenga reproducibilidad.
--
-- REGLA: clasifica el bloque del motor que generó la fila.
--   GENERAL   -> contexto del cálculo (UIT, base reconocida, régimen, año).
--   IR4TA_CAS -> retención 4ta CAS (tributo SUNAT 3042). FASE 1.
--   IR5TA     -> retención 5ta (FASE 3, futura).
--   SUBSIDIO  -> base reconocida EsSalud / tope 45% UIT (FASE 4, futura).
--
-- PARAMETROS_JSON (CLOB): payload flexible con los valores específicos de la
-- regla (uit, sieteUit, tasa, baseInafecta, divisor, retenidoAcum, topeSubsidio,
-- constancia, etc.). Las columnas tipadas (BASE_CALCULO/RESULTADO/FORMULA) son
-- las comunes que la UI muestra siempre.
--
-- DECISIONES DE DISEÑO (alineadas con V010_48):
--   - Naming INDECI_*; PK IDENTITY; constraints INDECI_*_PK/FK/CK.
--   - TABLESPACE explícito heredado de INDECI_EMPLEADO (evita ORA-00959 cuando
--     el default tablespace del schema no existe). Misma técnica que V010_48.
--   - Reproducibilidad: al regenerar, el motor DESACTIVA (ACTIVO=0) las filas
--     previas del par (EMPLEADO_ID, PERIODO) e inserta nuevas. Sólo lectura
--     desde ExplicacionPlanillaService.
--
-- DEFENSA EN PROFUNDIDAD: idempotente (no falla si la tabla ya existe).
-- Ejecutar en esquema GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_ts VARCHAR2(30);

    PROCEDURE add_table_if_missing(p_table VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(p_idx VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_INDEXES WHERE INDEX_NAME = p_idx;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_idx || ' -> creado en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_idx || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    -- Tablespace ancla: el de INDECI_EMPLEADO (tabla que sabemos que existe).
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    add_table_if_missing(
        'INDECI_CALCULO_SNAPSHOT',
        'CREATE TABLE INDECI_CALCULO_SNAPSHOT ('
        || 'ID                     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'EMPLEADO_ID            NUMBER NOT NULL,'
        || 'PERIODO                VARCHAR2(7 CHAR) NOT NULL,'
        || 'MOVIMIENTO_PLANILLA_ID NUMBER,'
        || 'REGLA                  VARCHAR2(20 CHAR) NOT NULL,'
        || 'BASE_CALCULO           NUMBER(18,2),'
        || 'RESULTADO              NUMBER(18,2),'
        || 'FORMULA                VARCHAR2(500 CHAR),'
        || 'PARAMETROS_JSON        CLOB,'
        || 'VERSION_PARAMETROS     VARCHAR2(20 CHAR),'
        || 'ACTIVO                 NUMBER(1) DEFAULT 1 NOT NULL,'
        || 'CREATED_AT             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        || 'CREATED_BY             VARCHAR2(50 CHAR),'
        || 'CONSTRAINT INDECI_CALC_SNAPSHOT_PK PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_CALC_SNAPSHOT_EMP_FK FOREIGN KEY (EMPLEADO_ID) '
        ||   'REFERENCES INDECI_EMPLEADO (ID),'
        || 'CONSTRAINT INDECI_CALC_SNAPSHOT_REGLA_CK '
        ||   'CHECK (REGLA IN (''GENERAL'', ''IR4TA_CAS'', ''IR5TA'', ''SUBSIDIO'')),'
        || 'CONSTRAINT INDECI_CALC_SNAPSHOT_ACTIVO_CK '
        ||   'CHECK (ACTIVO IN (0, 1))'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_CALC_SNAP_EMP_PER',
        'CREATE INDEX IX_INDECI_CALC_SNAP_EMP_PER '
        || 'ON INDECI_CALCULO_SNAPSHOT (EMPLEADO_ID, PERIODO, ACTIVO)'
    );
    add_index_if_missing(
        'IX_INDECI_CALC_SNAP_MOV',
        'CREATE INDEX IX_INDECI_CALC_SNAP_MOV '
        || 'ON INDECI_CALCULO_SNAPSHOT (MOVIMIENTO_PLANILLA_ID)'
    );

    -- ==================================================================
    -- COMMENTS
    -- ==================================================================
    EXECUTE IMMEDIATE 'COMMENT ON TABLE INDECI_CALCULO_SNAPSHOT IS '
        || '''FASE2 — Snapshot de trazabilidad: parámetros y magnitudes usados por el motor '
        || 'por (empleado, periodo, regla). Reproducible: al regenerar se desactivan los previos.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN INDECI_CALCULO_SNAPSHOT.REGLA IS '
        || '''GENERAL | IR4TA_CAS | IR5TA | SUBSIDIO — bloque del motor que originó la fila.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN INDECI_CALCULO_SNAPSHOT.PARAMETROS_JSON IS '
        || '''Payload JSON con los valores específicos de la regla (uit, tasa, baseInafecta, divisor, etc.).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN INDECI_CALCULO_SNAPSHOT.VERSION_PARAMETROS IS '
        || '''Versión de los parámetros usados (típicamente el año fiscal de vigencia).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN INDECI_CALCULO_SNAPSHOT.ACTIVO IS '
        || '''1 = snapshot vigente; 0 = reemplazado por una regeneración posterior.''';

    DBMS_OUTPUT.PUT_LINE('V010_55 finalizado.');
END;
/
