-- ============================================================================
-- F0.3 / V010_35 — INDECI_LEGAJO_CATEGORIA + SUBCATEGORIA + DOCUMENTO
--                  (Estabilización post-pull 2026-05-31 — soporte de entities
--                   LegajoCategoria, LegajoSubcategoria, LegajoDocumento.
--                   Preparación para F2 Eventos del Período con adjuntos.)
--
-- CONTEXTO:
--   El pull reciente trajo las 3 entities + repos del módulo Legajo (gestión
--   documental). El módulo se usará en F2 para asociar documentos sustentos
--   a Eventos del Período (subsidios médicos, papeletas, certificados).
--   Sin estas tablas, ningún endpoint del Legajo funciona.
--
-- DECISIONES DE DISEÑO:
--   - PK IDENTITY (consistente con el schema).
--   - CATEGORIA → SUBCATEGORIA jerárquico (1:N).
--   - DOCUMENTO con FKs a CATEGORIA + SUBCATEGORIA + EMPLEADO. CATEGORIA es
--     obligatoria; SUBCATEGORIA es opcional (un documento puede vivir solo
--     en su categoría).
--   - RUTA_ARCHIVO: ruta resuelta por FtpService (basePath + carpeta +
--     nombreArchivo). NO almacenamos el binario.
--   - VERSION_DOC permite control de versiones (default 1).
--   - ORIGEN: texto libre para identificar de dónde viene el doc
--     ("EVENTO", "ASISTENCIA", "MANUAL", "IMPORTACION", etc.).
--   - REFERENCIA_ID: id del registro fuente (ej. EmpleadoEvento.id si
--     ORIGEN='EVENTO'). No es FK porque puede apuntar a distintas tablas.
--   - Seeds: 5 categorías base que cubren los flujos conocidos.
--     RRHH puede ampliar por UI.
--
--   - NO se hardcodea el nombre del schema. Las tablas se crean en el schema del
--     usuario conectado y los lookups idempotentes usan USER_* (no ALL_* con OWNER).
--
-- IDEMPOTENTE: ejecutar varias veces no rompe. Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

-- ----------------------------------------------------------------------------
-- 1) Tablas (idempotente).
-- ----------------------------------------------------------------------------
-- Tablas heredan el TABLESPACE de INDECI_EMPLEADO (ancla estable que sabemos
-- existe en el schema). Evita ORA-00959 cuando el default tablespace del
-- usuario está vacío o roto.
DECLARE
    v_ts VARCHAR2(30);
    PROCEDURE add_table_if_missing(
        p_table_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_TABLES
         WHERE TABLE_NAME = p_table_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';
    add_table_if_missing(
        'INDECI_LEGAJO_CATEGORIA',
        'CREATE TABLE INDECI_LEGAJO_CATEGORIA ('
        ||   'ID            NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,'
        ||   'NOMBRE        VARCHAR2(100 CHAR) NOT NULL,'
        ||   'ORDEN_VISUAL  NUMBER(3) DEFAULT 100 NOT NULL,'
        ||   'ACTIVO        NUMBER(1) DEFAULT 1 NOT NULL,'
        ||   'CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CONSTRAINT INDECI_LEGAJO_CAT_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_LEGAJO_CAT_NOMBRE_UK UNIQUE (NOMBRE),'
        ||   'CONSTRAINT INDECI_LEGAJO_CAT_ACTIVO_CK CHECK (ACTIVO IN (0, 1))'
        || ')'
    );

    add_table_if_missing(
        'INDECI_LEGAJO_SUBCATEGORIA',
        'CREATE TABLE INDECI_LEGAJO_SUBCATEGORIA ('
        ||   'ID            NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,'
        ||   'CATEGORIA_ID  NUMBER(10) NOT NULL,'
        ||   'NOMBRE        VARCHAR2(100 CHAR) NOT NULL,'
        ||   'ORDEN_VISUAL  NUMBER(3) DEFAULT 100 NOT NULL,'
        ||   'ACTIVO        NUMBER(1) DEFAULT 1 NOT NULL,'
        ||   'CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CONSTRAINT INDECI_LEGAJO_SUBCAT_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_LEGAJO_SUBCAT_CAT_FK FOREIGN KEY (CATEGORIA_ID) '
        ||      'REFERENCES INDECI_LEGAJO_CATEGORIA (ID),'
        ||   'CONSTRAINT INDECI_LEGAJO_SUBCAT_NOMBRE_UK UNIQUE (CATEGORIA_ID, NOMBRE),'
        ||   'CONSTRAINT INDECI_LEGAJO_SUBCAT_ACTIVO_CK CHECK (ACTIVO IN (0, 1))'
        || ')'
    );

    add_table_if_missing(
        'INDECI_LEGAJO_DOCUMENTO',
        'CREATE TABLE INDECI_LEGAJO_DOCUMENTO ('
        ||   'ID                NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,'
        ||   'EMPLEADO_ID       NUMBER(10) NOT NULL,'
        ||   'CATEGORIA_ID      NUMBER(10) NOT NULL,'
        ||   'SUBCATEGORIA_ID   NUMBER(10),'
        ||   'NOMBRE_DOCUMENTO  VARCHAR2(200 CHAR) NOT NULL,'
        ||   'NOMBRE_ARCHIVO    VARCHAR2(200 CHAR),'
        ||   'RUTA_ARCHIVO      VARCHAR2(500 CHAR),'
        ||   'EXTENSION         VARCHAR2(10 CHAR),'
        ||   'PESO_ARCHIVO      NUMBER(12),'
        ||   'FECHA_DOCUMENTO   DATE,'
        ||   'OBSERVACION       VARCHAR2(500 CHAR),'
        ||   'ORIGEN            VARCHAR2(30 CHAR),'
        ||   'REFERENCIA_ID     NUMBER(10),'
        ||   'VERSION_DOC       NUMBER(3) DEFAULT 1 NOT NULL,'
        ||   'ACTIVO            NUMBER(1) DEFAULT 1 NOT NULL,'
        ||   'CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CREATED_BY        VARCHAR2(60 CHAR),'
        ||   'CONSTRAINT INDECI_LEGAJO_DOC_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_LEGAJO_DOC_EMP_FK FOREIGN KEY (EMPLEADO_ID) '
        ||      'REFERENCES INDECI_EMPLEADO (ID),'
        ||   'CONSTRAINT INDECI_LEGAJO_DOC_CAT_FK FOREIGN KEY (CATEGORIA_ID) '
        ||      'REFERENCES INDECI_LEGAJO_CATEGORIA (ID),'
        ||   'CONSTRAINT INDECI_LEGAJO_DOC_SUBCAT_FK FOREIGN KEY (SUBCATEGORIA_ID) '
        ||      'REFERENCES INDECI_LEGAJO_SUBCATEGORIA (ID),'
        ||   'CONSTRAINT INDECI_LEGAJO_DOC_ACTIVO_CK CHECK (ACTIVO IN (0, 1))'
        || ')'
    );

    EXECUTE IMMEDIATE 'COMMENT ON TABLE INDECI_LEGAJO_CATEGORIA IS '
        || '''F0.3 — Categorías de documentos del legajo del empleado. Pull 2026-05-31 / F2 Eventos.''';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE INDECI_LEGAJO_SUBCATEGORIA IS '
        || '''F0.3 — Subcategorías del legajo (jerárquico bajo CATEGORIA).''';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE INDECI_LEGAJO_DOCUMENTO IS '
        || '''F0.3 — Documentos del legajo del empleado (binarios viven en FTP, esto es metadata).''';

    DBMS_OUTPUT.PUT_LINE('V010_35 tablas listas.');
END;
/

-- ----------------------------------------------------------------------------
-- 2) Índices para las queries de los repos.
--    LegajoDocumentoRepository.findByEmpleadoIdAndActivoOrderByCreatedAtDesc
--    LegajoDocumentoRepository.findByEmpleadoIdAndCategoriaIdAndActivo...
--    LegajoDocumentoRepository.findByEmpleadoIdAndSubcategoriaIdAndActivo...
--    LegajoSubcategoriaRepository.findByCategoriaIdAndActivoOrderBy...
-- ----------------------------------------------------------------------------
-- El índice hereda el TABLESPACE de la tabla padre (USER_TABLES.TABLESPACE_NAME).
-- Esto evita ORA-00959 cuando el default tablespace del usuario no existe o no
-- tiene cuota.
DECLARE
    PROCEDURE add_index_if_missing(
        p_index_name VARCHAR2,
        p_table_name VARCHAR2,
        p_columns    VARCHAR2   -- e.g. '(EMPLEADO_ID, ACTIVO)'
    ) IS
        v_exists NUMBER;
        v_ts     VARCHAR2(30);
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_INDEXES
         WHERE INDEX_NAME = p_index_name;
        IF v_exists > 0 THEN
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' ya existe. Sin cambios.');
            RETURN;
        END IF;

        SELECT TABLESPACE_NAME INTO v_ts
          FROM USER_TABLES
         WHERE TABLE_NAME = p_table_name;

        EXECUTE IMMEDIATE
            'CREATE INDEX ' || p_index_name
            || ' ON ' || p_table_name || ' ' || p_columns
            || ' TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE(p_index_name || ' -> creado en TBS ' || v_ts);
    END;
BEGIN
    add_index_if_missing(
        'INDECI_LEGAJO_DOC_EMP_IX',
        'INDECI_LEGAJO_DOCUMENTO',
        '(EMPLEADO_ID, ACTIVO)'
    );
    add_index_if_missing(
        'INDECI_LEGAJO_DOC_CAT_IX',
        'INDECI_LEGAJO_DOCUMENTO',
        '(EMPLEADO_ID, CATEGORIA_ID, ACTIVO)'
    );
    add_index_if_missing(
        'INDECI_LEGAJO_DOC_SUBCAT_IX',
        'INDECI_LEGAJO_DOCUMENTO',
        '(SUBCATEGORIA_ID, ACTIVO)'
    );
    add_index_if_missing(
        'INDECI_LEGAJO_SUBCAT_CAT_IX',
        'INDECI_LEGAJO_SUBCATEGORIA',
        '(CATEGORIA_ID, ACTIVO)'
    );
    DBMS_OUTPUT.PUT_LINE('V010_35 índices listos.');
END;
/

-- ----------------------------------------------------------------------------
-- 3) Seed categorías base (idempotente). RRHH puede ampliar.
-- ----------------------------------------------------------------------------
MERGE INTO INDECI_LEGAJO_CATEGORIA d
USING (
    SELECT 'Contrato'          AS NOMBRE, 10  AS ORDEN_VISUAL FROM DUAL UNION ALL
    SELECT 'Documento de identidad' AS NOMBRE, 20  AS ORDEN_VISUAL FROM DUAL UNION ALL
    SELECT 'Certificados'      AS NOMBRE, 30  AS ORDEN_VISUAL FROM DUAL UNION ALL
    SELECT 'Subsidios'         AS NOMBRE, 40  AS ORDEN_VISUAL FROM DUAL UNION ALL
    SELECT 'Permisos y licencias' AS NOMBRE, 50  AS ORDEN_VISUAL FROM DUAL UNION ALL
    SELECT 'Resoluciones'      AS NOMBRE, 60  AS ORDEN_VISUAL FROM DUAL UNION ALL
    SELECT 'Otros'             AS NOMBRE, 99  AS ORDEN_VISUAL FROM DUAL
) s
ON (d.NOMBRE = s.NOMBRE)
WHEN NOT MATCHED THEN
    INSERT (NOMBRE, ORDEN_VISUAL, ACTIVO, CREATED_AT)
    VALUES (s.NOMBRE, s.ORDEN_VISUAL, 1, SYSTIMESTAMP);

-- ----------------------------------------------------------------------------
-- 4) Seed subcategorías base (idempotente). Se siembran solo las imprescindibles
--    para F2 (Eventos del Período).
-- ----------------------------------------------------------------------------
MERGE INTO INDECI_LEGAJO_SUBCATEGORIA d
USING (
    -- bajo Subsidios
    SELECT (SELECT ID FROM INDECI_LEGAJO_CATEGORIA WHERE NOMBRE='Subsidios') AS CATEGORIA_ID,
           'Maternidad' AS NOMBRE, 10 AS ORDEN_VISUAL FROM DUAL UNION ALL
    SELECT (SELECT ID FROM INDECI_LEGAJO_CATEGORIA WHERE NOMBRE='Subsidios') AS CATEGORIA_ID,
           'Enfermedad' AS NOMBRE, 20 AS ORDEN_VISUAL FROM DUAL UNION ALL
    SELECT (SELECT ID FROM INDECI_LEGAJO_CATEGORIA WHERE NOMBRE='Subsidios') AS CATEGORIA_ID,
           'Lactancia'  AS NOMBRE, 30 AS ORDEN_VISUAL FROM DUAL UNION ALL
    -- bajo Permisos y licencias
    SELECT (SELECT ID FROM INDECI_LEGAJO_CATEGORIA WHERE NOMBRE='Permisos y licencias') AS CATEGORIA_ID,
           'Licencia con goce'    AS NOMBRE, 10 AS ORDEN_VISUAL FROM DUAL UNION ALL
    SELECT (SELECT ID FROM INDECI_LEGAJO_CATEGORIA WHERE NOMBRE='Permisos y licencias') AS CATEGORIA_ID,
           'Licencia sin goce'    AS NOMBRE, 20 AS ORDEN_VISUAL FROM DUAL UNION ALL
    SELECT (SELECT ID FROM INDECI_LEGAJO_CATEGORIA WHERE NOMBRE='Permisos y licencias') AS CATEGORIA_ID,
           'Permiso personal'     AS NOMBRE, 30 AS ORDEN_VISUAL FROM DUAL UNION ALL
    SELECT (SELECT ID FROM INDECI_LEGAJO_CATEGORIA WHERE NOMBRE='Permisos y licencias') AS CATEGORIA_ID,
           'Paternidad'           AS NOMBRE, 40 AS ORDEN_VISUAL FROM DUAL UNION ALL
    -- bajo Certificados
    SELECT (SELECT ID FROM INDECI_LEGAJO_CATEGORIA WHERE NOMBRE='Certificados') AS CATEGORIA_ID,
           'Médico'   AS NOMBRE, 10 AS ORDEN_VISUAL FROM DUAL UNION ALL
    SELECT (SELECT ID FROM INDECI_LEGAJO_CATEGORIA WHERE NOMBRE='Certificados') AS CATEGORIA_ID,
           'Estudios' AS NOMBRE, 20 AS ORDEN_VISUAL FROM DUAL
) s
ON (d.CATEGORIA_ID = s.CATEGORIA_ID AND d.NOMBRE = s.NOMBRE)
WHEN NOT MATCHED THEN
    INSERT (CATEGORIA_ID, NOMBRE, ORDEN_VISUAL, ACTIVO, CREATED_AT)
    VALUES (s.CATEGORIA_ID, s.NOMBRE, s.ORDEN_VISUAL, 1, SYSTIMESTAMP);

COMMIT;
