-- ============================================================================
-- Spec 013 / B3 / V010_30 — Suspensiones/licencias + catálogo SUNAT (Tabla 21)
--                          (Etapa 3 · B3 · M09 — fuente del archivo .snl)
--
-- TABLAS:
--   1. INDECI_CAT_SUSPENSION_SUNAT — catálogo Tabla 21 SUNAT (PK natural = código).
--   2. INDECI_SUSPENSION           — eventos de suspensión por empleado y período.
--
-- DECISIONES DE DISEÑO (alineadas con V010_10):
--   - Naming INDECI_*; INDECI_SUSPENSION con PK IDENTITY (transaccional);
--     el catálogo usa PK natural COD_SUSPENSION (código estable SUNAT 01,02,03…).
--   - TIPO_PLAME discrimina cómo declara SUNAT: SUBSIDIADO | NO_LABORADO_NO_SUB |
--     ESPECIAL. VA_EN_SNL='N' (ej: cód 21 Lactancia) → no va al .snl, solo .jor.
--   - COD_DESCUENTO_PLAME: si la suspensión gatilla descuento (cód 23 → 2046).
--   - Sin USUARIO_CREO: auditoría centralizada en AuditoriaAspect (D.L. 1451).
--
-- DEFENSA EN PROFUNDIDAD: idempotente. El seed del catálogo va en V010_31.
-- Ejecutar en esquema GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;

    PROCEDURE add_table_if_missing(
        p_table_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM ALL_TABLES
         WHERE OWNER = 'GESTIONRRHH' AND TABLE_NAME = p_table_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl;
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' -> creada.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(
        p_index_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM ALL_INDEXES
         WHERE OWNER = 'GESTIONRRHH' AND INDEX_NAME = p_index_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl;
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' -> creado.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    -- ==================================================================
    -- 1) INDECI_CAT_SUSPENSION_SUNAT — catálogo Tabla 21 (PK natural)
    -- ==================================================================
    add_table_if_missing(
        'INDECI_CAT_SUSPENSION_SUNAT',
        'CREATE TABLE GESTIONRRHH.INDECI_CAT_SUSPENSION_SUNAT ('
        ||   'COD_SUSPENSION       VARCHAR2(2 CHAR)   NOT NULL,'
        ||   'DESCRIPCION          VARCHAR2(100 CHAR) NOT NULL,'
        ||   'TIPO_PLAME           VARCHAR2(20 CHAR)  NOT NULL,'
        ||   'REQUIERE_CMP         VARCHAR2(1 CHAR)   DEFAULT ''N'' NOT NULL,'
        ||   'REQUIERE_RESOLUCION  VARCHAR2(1 CHAR)   DEFAULT ''N'' NOT NULL,'
        ||   'VA_EN_SNL            VARCHAR2(1 CHAR)   DEFAULT ''S'' NOT NULL,'
        ||   'COD_DESCUENTO_PLAME  VARCHAR2(6 CHAR),'
        ||   'SUSTENTO_LEGAL       VARCHAR2(200 CHAR),'
        ||   'CONSTRAINT INDECI_CAT_SUSP_PK PRIMARY KEY (COD_SUSPENSION),'
        ||   'CONSTRAINT INDECI_CAT_SUSP_TIPO_CK '
        ||     'CHECK (TIPO_PLAME IN (''SUBSIDIADO'', ''NO_LABORADO_NO_SUB'', ''ESPECIAL'')),'
        ||   'CONSTRAINT INDECI_CAT_SUSP_CMP_CK CHECK (REQUIERE_CMP IN (''S'', ''N'')),'
        ||   'CONSTRAINT INDECI_CAT_SUSP_RES_CK CHECK (REQUIERE_RESOLUCION IN (''S'', ''N'')),'
        ||   'CONSTRAINT INDECI_CAT_SUSP_SNL_CK CHECK (VA_EN_SNL IN (''S'', ''N''))'
        || ')'
    );

    -- ==================================================================
    -- 2) INDECI_SUSPENSION — eventos por empleado (fuente del .snl/.jor)
    -- ==================================================================
    add_table_if_missing(
        'INDECI_SUSPENSION',
        'CREATE TABLE GESTIONRRHH.INDECI_SUSPENSION ('
        ||   'ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        ||   'EMPLEADO_ID     NUMBER NOT NULL,'
        ||   'COD_SUSPENSION  VARCHAR2(2 CHAR) NOT NULL,'
        ||   'FECHA_INICIO    DATE NOT NULL,'
        ||   'FECHA_FIN       DATE NOT NULL,'
        ||   'DIAS_AFECTOS    NUMBER(3) NOT NULL,'
        ||   'NRO_CMP         VARCHAR2(20 CHAR),'
        ||   'NRO_RESOLUCION  VARCHAR2(50 CHAR),'
        ||   'OBSERVACION     VARCHAR2(300 CHAR),'
        ||   'ESTADO          VARCHAR2(10 CHAR) DEFAULT ''ACTIVO'' NOT NULL,'
        ||   'CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CONSTRAINT INDECI_SUSPENSION_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_SUSPENSION_EMP_FK FOREIGN KEY (EMPLEADO_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_EMPLEADO (ID),'
        ||   'CONSTRAINT INDECI_SUSPENSION_CAT_FK FOREIGN KEY (COD_SUSPENSION) '
        ||     'REFERENCES GESTIONRRHH.INDECI_CAT_SUSPENSION_SUNAT (COD_SUSPENSION),'
        ||   'CONSTRAINT INDECI_SUSPENSION_ESTADO_CK '
        ||     'CHECK (ESTADO IN (''ACTIVO'', ''ANULADO'')),'
        ||   'CONSTRAINT INDECI_SUSPENSION_DIAS_CK CHECK (DIAS_AFECTOS >= 0),'
        ||   'CONSTRAINT INDECI_SUSPENSION_FECHAS_CK CHECK (FECHA_FIN >= FECHA_INICIO)'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_SUSPENSION_EMP',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_SUSPENSION_EMP '
        || 'ON GESTIONRRHH.INDECI_SUSPENSION (EMPLEADO_ID, ESTADO)'
    );
    add_index_if_missing(
        'IX_INDECI_SUSPENSION_FECHAS',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_SUSPENSION_FECHAS '
        || 'ON GESTIONRRHH.INDECI_SUSPENSION (FECHA_INICIO, FECHA_FIN)'
    );

    -- ==================================================================
    -- COMMENTS
    -- ==================================================================
    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_CAT_SUSPENSION_SUNAT IS '
        || '''B3 / M09 — Catálogo Tabla 21 SUNAT de tipos de suspensión/licencia para el .snl.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_CAT_SUSPENSION_SUNAT.TIPO_PLAME IS '
        || '''SUBSIDIADO (EsSalud) | NO_LABORADO_NO_SUB (entidad/descuento) | ESPECIAL (solo .jor).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_CAT_SUSPENSION_SUNAT.VA_EN_SNL IS '
        || '''S/N — N (ej: cód 21 Lactancia) no se declara en el .snl, solo afecta horas en el .jor.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_CAT_SUSPENSION_SUNAT.COD_DESCUENTO_PLAME IS '
        || '''Código PLAME de descuento que gatilla la suspensión (ej: cód 23 Faltas → 2046). NULL si no aplica.''';

    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_SUSPENSION IS '
        || '''B3 / M09 — Eventos de suspensión/licencia por empleado. Fuente de los días del .snl '
        || 'y del ajuste de horas del .jor.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_SUSPENSION.DIAS_AFECTOS IS '
        || '''Días afectos declarables (derivados del rango FECHA_INICIO..FECHA_FIN según calendario).''';

    DBMS_OUTPUT.PUT_LINE('V010_30 finalizado.');

    SELECT COUNT(*) INTO v_count
      FROM ALL_TABLES
     WHERE OWNER = 'GESTIONRRHH'
       AND TABLE_NAME IN ('INDECI_CAT_SUSPENSION_SUNAT', 'INDECI_SUSPENSION');
    DBMS_OUTPUT.PUT_LINE('Tablas de suspensión presentes: ' || v_count || ' / 2.');
END;
/
