-- ============================================================================
-- FASE 1 / V010_48 — Suspensión de retención de 4ta categoría (constancia SUNAT)
--
-- Tabla histórica por empleado con vigencia por fecha. Alimenta el motor
-- (GeneradorPlanillaService.calcular4taCategoriaCAS) para poner IR4ta = 0
-- cuando hay constancia SUNAT vigente de suspensión de retenciones de 4ta.
--
-- NO confundir con INDECI_SUSPENSION (V010_30): esa es suspensión LABORAL /
-- licencia (Tabla 21 SUNAT, fuente del .snl de PLAME). Esta es TRIBUTARIA.
--
-- DECISIONES DE DISEÑO (alineadas con V010_30 / V010_34 / V010_35):
--   - Naming INDECI_*; PK IDENTITY; constraints INDECI_*_PK/FK/CK.
--   - Vigencia por fecha (FECHA_VIG_INI..FECHA_VIG_FIN) — coherente con el
--     patrón de ParametroRemunerativoService. FECHA_VIG_FIN NULL = indefinida.
--   - Auditoría primaria centralizada en AuditoriaAspect (D.L. 1451).
--     CREATED_BY/UPDATED_* quedan opcionales por requerimiento del cliente.
--   - LEGAJO_DOCUMENTO_ID: adjunto opcional del PDF de la constancia.
--   - TABLESPACE explícito heredado de INDECI_EMPLEADO (ancla estable). Evita
--     ORA-00959 cuando el default tablespace del schema (TBS_RRHH) no existe
--     en el entorno (misma técnica de V010_34/V010_35/V010_39).
--
-- DEFENSA EN PROFUNDIDAD: idempotente (no falla si la tabla ya existe).
-- Ejecutar en esquema GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_ts VARCHAR2(30);

    PROCEDURE add_table_if_missing(p_table VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(p_idx VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_INDEXES WHERE INDEX_NAME = p_idx;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_idx || ' -> creado en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_idx || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    -- Tablespace ancla: el de INDECI_EMPLEADO (tabla que sabemos que existe).
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    add_table_if_missing(
        'INDECI_SUSPENSION_4TA',
        'CREATE TABLE INDECI_SUSPENSION_4TA ('
        || 'ID                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'EMPLEADO_ID         NUMBER NOT NULL,'
        || 'NRO_CONSTANCIA      VARCHAR2(50 CHAR),'
        || 'FECHA_EMISION       DATE,'
        || 'FECHA_VIG_INI       DATE NOT NULL,'
        || 'FECHA_VIG_FIN       DATE,'
        || 'ESTADO              VARCHAR2(10 CHAR) DEFAULT ''ACTIVO'' NOT NULL,'
        || 'OBSERVACION         VARCHAR2(300 CHAR),'
        || 'LEGAJO_DOCUMENTO_ID NUMBER,'
        || 'CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        || 'CREATED_BY          VARCHAR2(50 CHAR),'
        || 'UPDATED_AT          TIMESTAMP,'
        || 'UPDATED_BY          VARCHAR2(50 CHAR),'
        || 'CONSTRAINT INDECI_SUSPENSION_4TA_PK PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_SUSPENSION_4TA_EMP_FK FOREIGN KEY (EMPLEADO_ID) '
        ||   'REFERENCES INDECI_EMPLEADO (ID),'
        || 'CONSTRAINT INDECI_SUSPENSION_4TA_LEG_FK FOREIGN KEY (LEGAJO_DOCUMENTO_ID) '
        ||   'REFERENCES INDECI_LEGAJO_DOCUMENTO (ID),'
        || 'CONSTRAINT INDECI_SUSPENSION_4TA_ESTADO_CK '
        ||   'CHECK (ESTADO IN (''ACTIVO'', ''ANULADO'')),'
        || 'CONSTRAINT INDECI_SUSPENSION_4TA_FECHAS_CK '
        ||   'CHECK (FECHA_VIG_FIN IS NULL OR FECHA_VIG_FIN >= FECHA_VIG_INI)'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_SUSP4TA_EMP',
        'CREATE INDEX IX_INDECI_SUSP4TA_EMP '
        || 'ON INDECI_SUSPENSION_4TA (EMPLEADO_ID, ESTADO)'
    );
    add_index_if_missing(
        'IX_INDECI_SUSP4TA_VIG',
        'CREATE INDEX IX_INDECI_SUSP4TA_VIG '
        || 'ON INDECI_SUSPENSION_4TA (FECHA_VIG_INI, FECHA_VIG_FIN)'
    );

    -- ==================================================================
    -- COMMENTS
    -- ==================================================================
    EXECUTE IMMEDIATE 'COMMENT ON TABLE INDECI_SUSPENSION_4TA IS '
        || '''FASE1 — Constancias SUNAT de suspensión de retención de 4ta categoría '
        || '(régimen CAS). Vigencia por fecha. NO es suspensión laboral (ver INDECI_SUSPENSION).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN INDECI_SUSPENSION_4TA.NRO_CONSTANCIA IS '
        || '''N.° de operación/constancia SUNAT de suspensión de 4ta (Excel CAS col AH).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN INDECI_SUSPENSION_4TA.FECHA_VIG_FIN IS '
        || '''NULL = vigencia indefinida; se recomienda setear (SUNAT suele renovarse anual).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN INDECI_SUSPENSION_4TA.LEGAJO_DOCUMENTO_ID IS '
        || '''FK opcional al PDF de la constancia en INDECI_LEGAJO_DOCUMENTO.''';

    DBMS_OUTPUT.PUT_LINE('V010_48 finalizado.');
END;
/
