-- V010_108__alter_planilla_tipo.sql
-- Agregar campos de descripcion y auditoria a INDECI_PLANILLA_TIPO

ALTER TABLE GESTIONRRHH.INDECI_PLANILLA_TIPO 
ADD (
    DESCRIPCION VARCHAR2(300),
    CREADO_POR VARCHAR2(50),
    CREADO_EN TIMESTAMP,
    MODIFICADO_POR VARCHAR2(50),
    MODIFICADO_EN TIMESTAMP
);

COMMENT ON COLUMN GESTIONRRHH.INDECI_PLANILLA_TIPO.DESCRIPCION IS 'Descripción operativa del tipo de planilla';
COMMENT ON COLUMN GESTIONRRHH.INDECI_PLANILLA_TIPO.CREADO_POR IS 'Usuario que creó el registro';
COMMENT ON COLUMN GESTIONRRHH.INDECI_PLANILLA_TIPO.CREADO_EN IS 'Fecha y hora de creación';
COMMENT ON COLUMN GESTIONRRHH.INDECI_PLANILLA_TIPO.MODIFICADO_POR IS 'Usuario que modificó el registro';
COMMENT ON COLUMN GESTIONRRHH.INDECI_PLANILLA_TIPO.MODIFICADO_EN IS 'Fecha y hora de última modificación';
