-- ============================================================================
-- V010_77 — Módulo de Metas Presupuestales Anuales (6 tablas)
--
-- TABLAS:
--   1. INDECI_META_PPTO_CAT      — Catálogo anual único de metas presupuestales
--   2. INDECI_META_PPTO_LOTE     — Cabecera de proceso masivo
--   3. INDECI_EMP_META_ANUAL     — Asignación anual empleado ↔ meta
--   4. INDECI_META_PPTO_EQUIV    — Equivalencias entre años fiscales
--   5. INDECI_META_PPTO_LOTE_DET — Detalle / vista previa del proceso masivo
--   6. INDECI_META_PPTO_AUD      — Auditoría específica del módulo
--
-- DECISIONES DE DISEÑO (alineadas con V010_55 / V010_74 / V010_76):
--   - Naming INDECI_*; PKs IDENTITY (BY DEFAULT ON NULL); constraints INDECI_*_PK/FK/CK.
--   - TABLESPACE heredado de INDECI_EMPLEADO (evita ORA-01950/00959).
--   - Auditoría de filas: CREADO_POR/EN + MODIFICADO_POR/EN + ANULADO_POR/EN.
--     La aplicación (service layer) gestiona esos campos. Sin triggers.
--   - Auditoría centralizada: AuditoriaAspect (TBL_LOG_AUDITORIA, D.L. 1451).
--     INDECI_META_PPTO_AUD complementa con eventos de negocio del módulo.
--   - FK a INDECI_EMPLEADO referencia columna ID (no PERSONA_ID).
--   - UK del catálogo sobre META_HASH (SHA-256 de 7 campos) evita el límite
--     de tamaño de índice Oracle para UKs sobre múltiples VARCHAR2(500).
--   - UK funcional en INDECI_EMP_META_ANUAL: 1 asignación no-ANULADA/empleado/año.
--   - UK funcional en INDECI_META_PPTO_EQUIV: 1 equivalencia activa/origen/destino.
--   - NOMBRE INTENCIONALMENTE DISTINTO de INDECI_META_PRESUPUESTAL (V010_22),
--     que es el semáforo presupuestal del período — entidad diferente.
--   - Baja lógica: ESTADO='ANULADO' + MOTIVO_ANULACION. Sin DELETE físico.
--   - Sin ON DELETE CASCADE.
--
-- INTEGRACIÓN CON PLANILLA:
--   GeneradorPlanillaService lee INDECI_EMP_META_ANUAL filtrando:
--     EMPLEADO_ID = :empId AND ANIO_FISCAL = :anio
--     AND ESTADO = 'PUBLICADO' AND ESTADO <> 'ANULADO'
--   Al cerrar período: BLOQUEADO_POR_PLANILLA = 1 (no más modificaciones).
--
-- DEFENSA EN PROFUNDIDAD: idempotente (no falla si tablas/índices ya existen).
-- Ejecutar conectado como GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

-- ============================================================================
-- BLOQUE 1 — Tablas e índices
-- ============================================================================
DECLARE
    v_ts VARCHAR2(30);

    PROCEDURE add_table_if_missing(p_table VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(p_idx VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_INDEXES WHERE INDEX_NAME = p_idx;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_idx || ' -> creado.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_idx || ' ya existe. Sin cambios.');
        END IF;
    END;

BEGIN
    -- Tablespace ancla: siempre de INDECI_EMPLEADO (tabla que sabemos que existe).
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    DBMS_OUTPUT.PUT_LINE('Tablespace detectado: ' || v_ts);

    -- ==================================================================
    -- 1) INDECI_META_PPTO_CAT — Catálogo anual único de metas
    --    UK sobre META_HASH (SHA-256 de 7 campos) en lugar de UK directo
    --    sobre 6 columnas VARCHAR2(500) para evitar ORA-01450.
    -- ==================================================================
    add_table_if_missing(
        'INDECI_META_PPTO_CAT',
        'CREATE TABLE INDECI_META_PPTO_CAT ('
        || 'ID                     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'ANIO_FISCAL            NUMBER(4)     NOT NULL,'
        || 'META_CODIGO            VARCHAR2(30)  NOT NULL,'
        || 'CENTRO_COSTO           VARCHAR2(500) NOT NULL,'
        || 'CATEGORIA_PRESUPUESTAL VARCHAR2(500) NOT NULL,'
        || 'PRODUCTO               VARCHAR2(500) NOT NULL,'
        || 'ACTIVIDAD              VARCHAR2(500) NOT NULL,'
        || 'FINALIDAD              VARCHAR2(500) NOT NULL,'
        || 'META_HASH              VARCHAR2(64)  GENERATED ALWAYS AS ('
        ||   'RAWTOHEX(STANDARD_HASH('
        ||     'TO_CHAR(ANIO_FISCAL)||''|''||META_CODIGO||''|''||CENTRO_COSTO'
        ||     '||''|''||CATEGORIA_PRESUPUESTAL||''|''||PRODUCTO'
        ||     '||''|''||ACTIVIDAD||''|''||FINALIDAD'
        ||   ',''SHA256'')))'
        || ' VIRTUAL,'
        || 'ESTADO                 VARCHAR2(20)  DEFAULT ''BORRADOR'' NOT NULL,'
        || 'ACTIVO                 NUMBER(1)     DEFAULT 1 NOT NULL,'
        || 'FUENTE                 VARCHAR2(300),'
        || 'OBSERVACION            VARCHAR2(1000),'
        || 'CREADO_POR             VARCHAR2(100) NOT NULL,'
        || 'CREADO_EN              TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,'
        || 'MODIFICADO_POR         VARCHAR2(100),'
        || 'MODIFICADO_EN          TIMESTAMP,'
        || 'ANULADO_POR            VARCHAR2(100),'
        || 'ANULADO_EN             TIMESTAMP,'
        || 'MOTIVO_ANULACION       VARCHAR2(1000),'
        || 'CONSTRAINT INDECI_META_PPTO_CAT_PK        PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_CAT_UK        UNIQUE (META_HASH),'
        || 'CONSTRAINT INDECI_META_PPTO_CAT_ESTADO_CK CHECK (ESTADO IN ('
        ||   '''BORRADOR'',''VALIDADO'',''PUBLICADO'',''CERRADO'',''ANULADO'')),'
        || 'CONSTRAINT INDECI_META_PPTO_CAT_ACTIVO_CK CHECK (ACTIVO IN (0,1)),'
        || 'CONSTRAINT INDECI_META_PPTO_CAT_ANIO_CK   CHECK (ANIO_FISCAL BETWEEN 2000 AND 2100)'
        || ')'
    );

    add_index_if_missing('IX_INDECI_META_CAT_ANIO',
        'CREATE INDEX IX_INDECI_META_CAT_ANIO '
        || 'ON INDECI_META_PPTO_CAT (ANIO_FISCAL)');
    add_index_if_missing('IX_INDECI_META_CAT_META',
        'CREATE INDEX IX_INDECI_META_CAT_META '
        || 'ON INDECI_META_PPTO_CAT (META_CODIGO)');
    add_index_if_missing('IX_INDECI_META_CAT_ESTADO',
        'CREATE INDEX IX_INDECI_META_CAT_ESTADO '
        || 'ON INDECI_META_PPTO_CAT (ANIO_FISCAL, ESTADO)');

    -- ==================================================================
    -- 2) INDECI_META_PPTO_LOTE — Cabecera de proceso masivo
    --    CODIGO_LOTE generado por la aplicación (UUID recomendado).
    -- ==================================================================
    add_table_if_missing(
        'INDECI_META_PPTO_LOTE',
        'CREATE TABLE INDECI_META_PPTO_LOTE ('
        || 'ID                   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'CODIGO_LOTE          VARCHAR2(50)  NOT NULL,'
        || 'ANIO_ORIGEN          NUMBER(4),'
        || 'ANIO_DESTINO         NUMBER(4)     NOT NULL,'
        || 'TIPO_PROCESO         VARCHAR2(40)  NOT NULL,'
        || 'ESTADO               VARCHAR2(30)  DEFAULT ''CREADO'' NOT NULL,'
        || 'TOTAL_EMPLEADOS      NUMBER        DEFAULT 0 NOT NULL,'
        || 'TOTAL_ASIGNADOS      NUMBER        DEFAULT 0 NOT NULL,'
        || 'TOTAL_OBSERVADOS     NUMBER        DEFAULT 0 NOT NULL,'
        || 'TOTAL_ERRORES        NUMBER        DEFAULT 0 NOT NULL,'
        || 'TOTAL_SIN_EQUIV      NUMBER        DEFAULT 0 NOT NULL,'
        || 'TOTAL_INACTIVOS      NUMBER        DEFAULT 0 NOT NULL,'
        || 'TOTAL_DUPLICADOS     NUMBER        DEFAULT 0 NOT NULL,'
        || 'ARCHIVO_ORIGEN       VARCHAR2(500),'
        || 'OBSERVACION          VARCHAR2(1000),'
        || 'CREADO_POR           VARCHAR2(100) NOT NULL,'
        || 'CREADO_EN            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,'
        || 'FINALIZADO_EN        TIMESTAMP,'
        || 'ANULADO_POR          VARCHAR2(100),'
        || 'ANULADO_EN           TIMESTAMP,'
        || 'MOTIVO_ANULACION     VARCHAR2(1000),'
        || 'CONSTRAINT INDECI_META_PPTO_LOTE_PK      PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_LOTE_COD_UK  UNIQUE (CODIGO_LOTE),'
        || 'CONSTRAINT INDECI_META_PPTO_LOTE_TIPO_CK CHECK (TIPO_PROCESO IN ('
        ||   '''CARGA_CATALOGO'',''COPIA_ANIO_ANTERIOR'',''APLICACION_EQUIVALENCIAS'','
        ||   '''IMPORTACION_EXCEL'',''PUBLICACION_ANUAL'',''REGULARIZACION'')),'
        || 'CONSTRAINT INDECI_META_PPTO_LOTE_EST_CK  CHECK (ESTADO IN ('
        ||   '''CREADO'',''PROCESANDO'',''VALIDADO'',''OBSERVADO'',''PUBLICADO'',''ANULADO'',''ERROR'')),'
        || 'CONSTRAINT INDECI_META_PPTO_LOTE_ANIO_CK CHECK (ANIO_DESTINO BETWEEN 2000 AND 2100)'
        || ')'
    );

    add_index_if_missing('IX_INDECI_META_LOTE_ANIO',
        'CREATE INDEX IX_INDECI_META_LOTE_ANIO '
        || 'ON INDECI_META_PPTO_LOTE (ANIO_DESTINO)');
    add_index_if_missing('IX_INDECI_META_LOTE_ESTADO',
        'CREATE INDEX IX_INDECI_META_LOTE_ESTADO '
        || 'ON INDECI_META_PPTO_LOTE (ESTADO)');
    add_index_if_missing('IX_INDECI_META_LOTE_TIPO',
        'CREATE INDEX IX_INDECI_META_LOTE_TIPO '
        || 'ON INDECI_META_PPTO_LOTE (TIPO_PROCESO, ESTADO)');

    -- ==================================================================
    -- 3) INDECI_EMP_META_ANUAL — Asignación anual empleado ↔ meta
    --    UK funcional: solo 1 asignación no-ANULADA por empleado por año.
    -- ==================================================================
    add_table_if_missing(
        'INDECI_EMP_META_ANUAL',
        'CREATE TABLE INDECI_EMP_META_ANUAL ('
        || 'ID                     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'EMPLEADO_ID            NUMBER        NOT NULL,'
        || 'ANIO_FISCAL            NUMBER(4)     NOT NULL,'
        || 'META_PPTO_CAT_ID       NUMBER        NOT NULL,'
        || 'VIGENCIA_INICIO        DATE          NOT NULL,'
        || 'VIGENCIA_FIN           DATE,'
        || 'ESTADO                 VARCHAR2(20)  DEFAULT ''BORRADOR'' NOT NULL,'
        || 'ORIGEN                 VARCHAR2(40)  DEFAULT ''MANUAL'' NOT NULL,'
        || 'LOTE_ID                NUMBER,'
        || 'BLOQUEADO_POR_PLANILLA NUMBER(1)     DEFAULT 0 NOT NULL,'
        || 'OBSERVACION            VARCHAR2(1000),'
        || 'CREADO_POR             VARCHAR2(100) NOT NULL,'
        || 'CREADO_EN              TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,'
        || 'MODIFICADO_POR         VARCHAR2(100),'
        || 'MODIFICADO_EN          TIMESTAMP,'
        || 'ANULADO_POR            VARCHAR2(100),'
        || 'ANULADO_EN             TIMESTAMP,'
        || 'MOTIVO_ANULACION       VARCHAR2(1000),'
        || 'CONSTRAINT INDECI_EMP_META_ANUAL_PK      PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_EMP_META_ANUAL_EMP_FK  FOREIGN KEY (EMPLEADO_ID) '
        ||   'REFERENCES INDECI_EMPLEADO (ID),'
        || 'CONSTRAINT INDECI_EMP_META_ANUAL_META_FK FOREIGN KEY (META_PPTO_CAT_ID) '
        ||   'REFERENCES INDECI_META_PPTO_CAT (ID),'
        || 'CONSTRAINT INDECI_EMP_META_ANUAL_LOTE_FK FOREIGN KEY (LOTE_ID) '
        ||   'REFERENCES INDECI_META_PPTO_LOTE (ID),'
        || 'CONSTRAINT INDECI_EMP_META_ANUAL_EST_CK  CHECK (ESTADO IN ('
        ||   '''BORRADOR'',''VALIDADO'',''PUBLICADO'',''CERRADO'',''ANULADO'',''OBSERVADO'')),'
        || 'CONSTRAINT INDECI_EMP_META_ANUAL_ORI_CK  CHECK (ORIGEN IN ('
        ||   '''MANUAL'',''COPIA_ANIO_ANTERIOR'',''EQUIVALENCIA'','
        ||   '''IMPORTACION_EXCEL'',''REGULARIZACION'')),'
        || 'CONSTRAINT INDECI_EMP_META_ANUAL_BLOQ_CK CHECK (BLOQUEADO_POR_PLANILLA IN (0,1)),'
        || 'CONSTRAINT INDECI_EMP_META_ANUAL_FECH_CK CHECK (VIGENCIA_FIN IS NULL OR VIGENCIA_FIN >= VIGENCIA_INICIO)'
        || ')'
    );

    add_index_if_missing('IX_INDECI_EMP_META_EMP',
        'CREATE INDEX IX_INDECI_EMP_META_EMP '
        || 'ON INDECI_EMP_META_ANUAL (EMPLEADO_ID)');
    add_index_if_missing('IX_INDECI_EMP_META_ANIO',
        'CREATE INDEX IX_INDECI_EMP_META_ANIO '
        || 'ON INDECI_EMP_META_ANUAL (ANIO_FISCAL)');
    add_index_if_missing('IX_INDECI_EMP_META_META',
        'CREATE INDEX IX_INDECI_EMP_META_META '
        || 'ON INDECI_EMP_META_ANUAL (META_PPTO_CAT_ID)');
    add_index_if_missing('IX_INDECI_EMP_META_ESTADO',
        'CREATE INDEX IX_INDECI_EMP_META_ESTADO '
        || 'ON INDECI_EMP_META_ANUAL (EMPLEADO_ID, ANIO_FISCAL, ESTADO)');
    add_index_if_missing('IX_INDECI_EMP_META_LOTE',
        'CREATE INDEX IX_INDECI_EMP_META_LOTE '
        || 'ON INDECI_EMP_META_ANUAL (LOTE_ID)');
    -- UK funcional: CASE devuelve NULL para ANULADO → no participa en unicidad
    add_index_if_missing('UK_INDECI_EMP_META_ACTIVA',
        'CREATE UNIQUE INDEX UK_INDECI_EMP_META_ACTIVA '
        || 'ON INDECI_EMP_META_ANUAL ('
        ||   'CASE WHEN ESTADO <> ''ANULADO'' THEN EMPLEADO_ID END,'
        ||   'CASE WHEN ESTADO <> ''ANULADO'' THEN ANIO_FISCAL  END'
        || ')');

    -- ==================================================================
    -- 4) INDECI_META_PPTO_EQUIV — Equivalencias entre años fiscales
    --    UK funcional: 1 equivalencia activa por (origen, año destino).
    -- ==================================================================
    add_table_if_missing(
        'INDECI_META_PPTO_EQUIV',
        'CREATE TABLE INDECI_META_PPTO_EQUIV ('
        || 'ID               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'ANIO_ORIGEN      NUMBER(4)     NOT NULL,'
        || 'META_ORIGEN_ID   NUMBER        NOT NULL,'
        || 'ANIO_DESTINO     NUMBER(4)     NOT NULL,'
        || 'META_DESTINO_ID  NUMBER        NOT NULL,'
        || 'ESTADO           VARCHAR2(20)  DEFAULT ''BORRADOR'' NOT NULL,'
        || 'ACTIVO           NUMBER(1)     DEFAULT 1 NOT NULL,'
        || 'OBSERVACION      VARCHAR2(1000),'
        || 'CREADO_POR       VARCHAR2(100) NOT NULL,'
        || 'CREADO_EN        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,'
        || 'MODIFICADO_POR   VARCHAR2(100),'
        || 'MODIFICADO_EN    TIMESTAMP,'
        || 'ANULADO_POR      VARCHAR2(100),'
        || 'ANULADO_EN       TIMESTAMP,'
        || 'MOTIVO_ANULACION VARCHAR2(1000),'
        || 'CONSTRAINT INDECI_META_PPTO_EQUIV_PK      PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_EQUIV_ORI_FK  FOREIGN KEY (META_ORIGEN_ID) '
        ||   'REFERENCES INDECI_META_PPTO_CAT (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_EQUIV_DEST_FK FOREIGN KEY (META_DESTINO_ID) '
        ||   'REFERENCES INDECI_META_PPTO_CAT (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_EQUIV_EST_CK  CHECK (ESTADO IN ('
        ||   '''BORRADOR'',''VALIDADO'',''PUBLICADO'',''ANULADO'')),'
        || 'CONSTRAINT INDECI_META_PPTO_EQUIV_ACT_CK  CHECK (ACTIVO IN (0,1)),'
        || 'CONSTRAINT INDECI_META_PPTO_EQUIV_ANIO_CK CHECK (ANIO_DESTINO > ANIO_ORIGEN)'
        || ')'
    );

    add_index_if_missing('IX_INDECI_META_EQUIV_ORI',
        'CREATE INDEX IX_INDECI_META_EQUIV_ORI '
        || 'ON INDECI_META_PPTO_EQUIV (ANIO_ORIGEN, META_ORIGEN_ID)');
    add_index_if_missing('IX_INDECI_META_EQUIV_DEST',
        'CREATE INDEX IX_INDECI_META_EQUIV_DEST '
        || 'ON INDECI_META_PPTO_EQUIV (ANIO_DESTINO, META_DESTINO_ID)');
    add_index_if_missing('IX_INDECI_META_EQUIV_ESTADO',
        'CREATE INDEX IX_INDECI_META_EQUIV_ESTADO '
        || 'ON INDECI_META_PPTO_EQUIV (ESTADO, ACTIVO)');
    -- UK funcional: 1 equivalencia ACTIVA/no-ANULADA por (origen → año destino)
    add_index_if_missing('UK_INDECI_META_EQUIV_ACT',
        'CREATE UNIQUE INDEX UK_INDECI_META_EQUIV_ACT '
        || 'ON INDECI_META_PPTO_EQUIV ('
        ||   'CASE WHEN ACTIVO = 1 AND ESTADO <> ''ANULADO'' THEN ANIO_ORIGEN    END,'
        ||   'CASE WHEN ACTIVO = 1 AND ESTADO <> ''ANULADO'' THEN META_ORIGEN_ID END,'
        ||   'CASE WHEN ACTIVO = 1 AND ESTADO <> ''ANULADO'' THEN ANIO_DESTINO   END'
        || ')');

    -- ==================================================================
    -- 5) INDECI_META_PPTO_LOTE_DET — Detalle del proceso masivo
    --    Vista previa + validación por empleado antes de publicar.
    -- ==================================================================
    add_table_if_missing(
        'INDECI_META_PPTO_LOTE_DET',
        'CREATE TABLE INDECI_META_PPTO_LOTE_DET ('
        || 'ID                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'LOTE_ID            NUMBER        NOT NULL,'
        || 'EMPLEADO_ID        NUMBER        NOT NULL,'
        || 'META_ORIGEN_ID     NUMBER,'
        || 'META_DESTINO_ID    NUMBER,'
        || 'EMP_META_ANUAL_ID  NUMBER,'
        || 'ESTADO_VALIDACION  VARCHAR2(40)  DEFAULT ''OK'' NOT NULL,'
        || 'MENSAJE_VALIDACION VARCHAR2(1000),'
        || 'ACCION_SUGERIDA    VARCHAR2(500),'
        || 'CREADO_POR         VARCHAR2(100) NOT NULL,'
        || 'CREADO_EN          TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,'
        || 'MODIFICADO_POR     VARCHAR2(100),'
        || 'MODIFICADO_EN      TIMESTAMP,'
        || 'CONSTRAINT INDECI_META_PPTO_DET_PK       PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_DET_LOTE_FK  FOREIGN KEY (LOTE_ID) '
        ||   'REFERENCES INDECI_META_PPTO_LOTE (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_DET_EMP_FK   FOREIGN KEY (EMPLEADO_ID) '
        ||   'REFERENCES INDECI_EMPLEADO (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_DET_ORI_FK   FOREIGN KEY (META_ORIGEN_ID) '
        ||   'REFERENCES INDECI_META_PPTO_CAT (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_DET_DEST_FK  FOREIGN KEY (META_DESTINO_ID) '
        ||   'REFERENCES INDECI_META_PPTO_CAT (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_DET_EM_FK    FOREIGN KEY (EMP_META_ANUAL_ID) '
        ||   'REFERENCES INDECI_EMP_META_ANUAL (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_DET_EST_CK   CHECK (ESTADO_VALIDACION IN ('
        ||   '''OK'',''OBSERVADO'',''SIN_EQUIVALENCIA'',''META_DESTINO_INACTIVA'','
        ||   '''EMPLEADO_INACTIVO'',''DUPLICADO'',''ERROR''))'
        || ')'
    );

    add_index_if_missing('IX_INDECI_META_DET_LOTE',
        'CREATE INDEX IX_INDECI_META_DET_LOTE '
        || 'ON INDECI_META_PPTO_LOTE_DET (LOTE_ID)');
    add_index_if_missing('IX_INDECI_META_DET_EMP',
        'CREATE INDEX IX_INDECI_META_DET_EMP '
        || 'ON INDECI_META_PPTO_LOTE_DET (EMPLEADO_ID)');
    add_index_if_missing('IX_INDECI_META_DET_ESTADO',
        'CREATE INDEX IX_INDECI_META_DET_ESTADO '
        || 'ON INDECI_META_PPTO_LOTE_DET (LOTE_ID, ESTADO_VALIDACION)');

    -- ==================================================================
    -- 6) INDECI_META_PPTO_AUD — Auditoría específica del módulo
    --    Complementa TBL_LOG_AUDITORIA (AuditoriaAspect). Registra
    --    eventos de negocio: publicación, bloqueo por planilla, etc.
    -- ==================================================================
    add_table_if_missing(
        'INDECI_META_PPTO_AUD',
        'CREATE TABLE INDECI_META_PPTO_AUD ('
        || 'ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'EMP_META_ID     NUMBER,'
        || 'EMPLEADO_ID     NUMBER,'
        || 'ANIO_FISCAL     NUMBER(4),'
        || 'ACCION          VARCHAR2(50)   NOT NULL,'
        || 'VALOR_ANTERIOR  CLOB,'
        || 'VALOR_NUEVO     CLOB,'
        || 'MOTIVO          VARCHAR2(1000),'
        || 'USUARIO         VARCHAR2(100)  NOT NULL,'
        || 'FECHA           TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,'
        || 'IP_SESION       VARCHAR2(100),'
        || 'CONSTRAINT INDECI_META_PPTO_AUD_PK      PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_AUD_META_FK FOREIGN KEY (EMP_META_ID) '
        ||   'REFERENCES INDECI_EMP_META_ANUAL (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_AUD_EMP_FK  FOREIGN KEY (EMPLEADO_ID) '
        ||   'REFERENCES INDECI_EMPLEADO (ID),'
        || 'CONSTRAINT INDECI_META_PPTO_AUD_ACC_CK  CHECK (ACCION IN ('
        ||   '''CREAR_META'',''EDITAR_META'',''ANULAR_META'',''IMPORTAR_CATALOGO'','
        ||   '''CREAR_ASIGNACION'',''EDITAR_ASIGNACION'',''COPIAR_ANIO_ANTERIOR'','
        ||   '''APLICAR_EQUIVALENCIA'',''IMPORTAR_EXCEL'',''VALIDAR_ASIGNACION'','
        ||   '''PUBLICAR_ASIGNACION'',''ANULAR_ASIGNACION'',''BLOQUEAR_POR_PLANILLA''))'
        || ')'
    );

    add_index_if_missing('IX_INDECI_META_AUD_EMP',
        'CREATE INDEX IX_INDECI_META_AUD_EMP '
        || 'ON INDECI_META_PPTO_AUD (EMPLEADO_ID)');
    add_index_if_missing('IX_INDECI_META_AUD_ANIO',
        'CREATE INDEX IX_INDECI_META_AUD_ANIO '
        || 'ON INDECI_META_PPTO_AUD (ANIO_FISCAL, ACCION)');
    add_index_if_missing('IX_INDECI_META_AUD_FECHA',
        'CREATE INDEX IX_INDECI_META_AUD_FECHA '
        || 'ON INDECI_META_PPTO_AUD (FECHA)');

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('V010_77 tablas e indices completados.');

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR V010_77: ' || SQLERRM);
        RAISE;
END;
/

-- ============================================================================
-- BLOQUE 2 — Comentarios (idempotente: Oracle sobrescribe si ya existen)
-- ============================================================================
BEGIN
    EXECUTE IMMEDIATE
        'COMMENT ON TABLE INDECI_META_PPTO_CAT IS '
        || '''Catálogo anual único de metas presupuestales INDECI. '
        || 'Una fila por combinación única (ANIO+META_CODIGO+CENTRO_COSTO+CATEGORIA+PRODUCTO+ACTIVIDAD+FINALIDAD). '
        || 'Unicidad garantizada por META_HASH (SHA-256 sobre 7 campos). '
        || 'DISTINTO de INDECI_META_PRESUPUESTAL (V010_22), que es el semáforo presupuestal del período.''';

    EXECUTE IMMEDIATE
        'COMMENT ON COLUMN INDECI_META_PPTO_CAT.META_HASH IS '
        || '''Columna VIRTUAL. RAWTOHEX(STANDARD_HASH(7 campos, SHA256)). '
        || 'Soporte para INDECI_META_PPTO_CAT_UK. No persistida, calculada siempre.''';

    EXECUTE IMMEDIATE
        'COMMENT ON COLUMN INDECI_META_PPTO_CAT.ESTADO IS '
        || '''Ciclo: BORRADOR → VALIDADO → PUBLICADO → CERRADO (terminal) / ANULADO (terminal). '
        || 'Solo PUBLICADO y CERRADO pueden usarse desde INDECI_EMP_META_ANUAL.''';

    EXECUTE IMMEDIATE
        'COMMENT ON TABLE INDECI_META_PPTO_LOTE IS '
        || '''Cabecera de proceso masivo de asignación anual de metas presupuestales. '
        || 'CODIGO_LOTE generado por la aplicación (UUID recomendado). '
        || 'Los TOTAL_* los actualiza el service al finalizar el proceso.''';

    EXECUTE IMMEDIATE
        'COMMENT ON COLUMN INDECI_META_PPTO_LOTE.TIPO_PROCESO IS '
        || '''CARGA_CATALOGO | COPIA_ANIO_ANTERIOR | APLICACION_EQUIVALENCIAS '
        || '| IMPORTACION_EXCEL | PUBLICACION_ANUAL | REGULARIZACION.''';

    EXECUTE IMMEDIATE
        'COMMENT ON TABLE INDECI_EMP_META_ANUAL IS '
        || '''Asignación anual de meta presupuestal a cada trabajador. '
        || 'UK_INDECI_EMP_META_ACTIVA garantiza 1 sola asignación no-ANULADA por empleado y año. '
        || 'La planilla lee filtrando ESTADO=PUBLICADO. '
        || 'Al cerrar período: BLOQUEADO_POR_PLANILLA=1 → sin modificaciones posteriores.''';

    EXECUTE IMMEDIATE
        'COMMENT ON COLUMN INDECI_EMP_META_ANUAL.META_PPTO_CAT_ID IS '
        || '''FK a INDECI_META_PPTO_CAT (catálogo anual). '
        || 'Antes de asignar, la meta debe estar en estado PUBLICADO o CERRADO.''';

    EXECUTE IMMEDIATE
        'COMMENT ON COLUMN INDECI_EMP_META_ANUAL.BLOQUEADO_POR_PLANILLA IS '
        || '''0=editable, 1=bloqueado. '
        || 'Seteado a 1 por GeneradorPlanillaService al usar la asignación en un período cerrado.''';

    EXECUTE IMMEDIATE
        'COMMENT ON TABLE INDECI_META_PPTO_EQUIV IS '
        || '''Equivalencias de metas presupuestales entre años fiscales (A→B). '
        || 'UK_INDECI_META_EQUIV_ACT garantiza 1 sola equivalencia activa y no-anulada '
        || 'por (META_ORIGEN_ID, ANIO_DESTINO). Solo se puede tener una ruta de equivalencia activa por meta.''';

    EXECUTE IMMEDIATE
        'COMMENT ON TABLE INDECI_META_PPTO_LOTE_DET IS '
        || '''Detalle de validación por empleado dentro de un proceso masivo (lote). '
        || 'Permite vista previa, corrección de observaciones y auditoría antes de publicar. '
        || 'ESTADO_VALIDACION: OK | OBSERVADO | SIN_EQUIVALENCIA | META_DESTINO_INACTIVA '
        || '| EMPLEADO_INACTIVO | DUPLICADO | ERROR.''';

    EXECUTE IMMEDIATE
        'COMMENT ON TABLE INDECI_META_PPTO_AUD IS '
        || '''Auditoría específica del módulo de metas presupuestales. '
        || 'Complementa TBL_LOG_AUDITORIA (AuditoriaAspect, D.L. 1451). '
        || 'Registra eventos de negocio con valores anterior/nuevo en JSON (CLOB).''';

    DBMS_OUTPUT.PUT_LINE('V010_77 comentarios aplicados.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('AVISO comentarios V010_77: ' || SQLERRM);
END;
/

-- ============================================================================
-- BLOQUE 3 — Vista operativa (opcional — comentada)
-- Descomenta solo si el proyecto decide usarla en lugar de joins en JPA.
-- ============================================================================
/*
CREATE OR REPLACE VIEW VW_INDECI_EMP_META_ANUAL AS
SELECT
    ema.ID,
    ema.EMPLEADO_ID,
    e.CODIGO_INTERNO,
    ema.ANIO_FISCAL,
    ema.ESTADO            AS ESTADO_ASIGNACION,
    ema.ORIGEN,
    ema.BLOQUEADO_POR_PLANILLA,
    ema.VIGENCIA_INICIO,
    ema.VIGENCIA_FIN,
    cat.ID                AS META_PPTO_CAT_ID,
    cat.META_CODIGO,
    cat.CENTRO_COSTO,
    cat.CATEGORIA_PRESUPUESTAL,
    cat.PRODUCTO,
    cat.ACTIVIDAD,
    cat.FINALIDAD,
    cat.ESTADO            AS ESTADO_META,
    ema.CREADO_POR,
    ema.CREADO_EN,
    ema.MODIFICADO_POR,
    ema.MODIFICADO_EN
FROM INDECI_EMP_META_ANUAL ema
JOIN INDECI_EMPLEADO e
    ON e.ID = ema.EMPLEADO_ID
JOIN INDECI_META_PPTO_CAT cat
    ON cat.ID = ema.META_PPTO_CAT_ID;
*/

-- ============================================================================
-- BLOQUE 4 — Verificación final
-- ============================================================================
SELECT TABLE_NAME
  FROM USER_TABLES
 WHERE TABLE_NAME IN (
       'INDECI_META_PPTO_CAT',
       'INDECI_META_PPTO_LOTE',
       'INDECI_EMP_META_ANUAL',
       'INDECI_META_PPTO_EQUIV',
       'INDECI_META_PPTO_LOTE_DET',
       'INDECI_META_PPTO_AUD'
       )
 ORDER BY TABLE_NAME;

SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS
  FROM USER_INDEXES
 WHERE TABLE_NAME IN (
       'INDECI_META_PPTO_CAT',
       'INDECI_META_PPTO_LOTE',
       'INDECI_EMP_META_ANUAL',
       'INDECI_META_PPTO_EQUIV',
       'INDECI_META_PPTO_LOTE_DET',
       'INDECI_META_PPTO_AUD'
       )
 ORDER BY TABLE_NAME, INDEX_NAME;
