-- ============================================================================
-- P0 / V010_57 - Trazabilidad de subsidios por evento
--
-- Registra por trabajador y evento medico la distribucion de dias asumidos por
-- entidad y EsSalud, los codigos PLAME aplicables y el pago diferencial CAS.
--
-- Idempotente. Ejecutar en esquema GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_exists NUMBER;
    v_ts     VARCHAR2(30);
BEGIN
    -- Tablespace ancla: el de INDECI_EMPLEADO (evita ORA-00959 cuando el
    -- default del schema, TBS_RRHH, no existe). Mismo patrón que V010_48/55/56.
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    SELECT COUNT(*) INTO v_exists
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_SUBSIDIO_EVENTO_CALCULO';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE INDECI_SUBSIDIO_EVENTO_CALCULO ('
            || 'ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,'
            || 'EMPLEADO_ID NUMBER(10) NOT NULL,'
            || 'EMPLEADO_EVENTO_ID NUMBER(10) NOT NULL,'
            || 'MOVIMIENTO_PLANILLA_ID NUMBER(10),'
            || 'PERIODO VARCHAR2(6 CHAR),'
            || 'ANIO_CALENDARIO NUMBER(4) NOT NULL,'
            || 'TIPO_SUBSIDIO VARCHAR2(20 CHAR) NOT NULL,'
            || 'FECHA_INICIO_DESCANSO DATE NOT NULL,'
            || 'FECHA_FIN_DESCANSO DATE NOT NULL,'
            || 'DIAS_DESCANSO NUMBER(4) NOT NULL,'
            || 'DIAS_ACUMULADOS_PREVIOS NUMBER(4) DEFAULT 0 NOT NULL,'
            || 'DIAS_A_CARGO_ENTIDAD NUMBER(4) DEFAULT 0 NOT NULL,'
            || 'DIAS_SUBSIDIO_ESSALUD NUMBER(4) DEFAULT 0 NOT NULL,'
            || 'CITT_NUMERO VARCHAR2(50 CHAR),'
            || 'DOCUMENTO_MEDICO_REFERENCIA VARCHAR2(100 CHAR),'
            || 'CODIGO_PLAME_SUBSIDIO VARCHAR2(6 CHAR),'
            || 'CODIGO_PLAME_DIFERENCIAL VARCHAR2(6 CHAR),'
            || 'SUBSIDIO_TOTAL_100 NUMBER(18,2),'
            || 'BASE_RECONOCIDA_ESSALUD NUMBER(18,2),'
            || 'SUBSIDIO_DIARIO_ESSALUD NUMBER(18,2),'
            || 'SUBSIDIO_ESSALUD NUMBER(18,2),'
            || 'PAGO_DIFERENCIAL NUMBER(18,2),'
            || 'ESTADO VARCHAR2(20 CHAR) DEFAULT ''CALCULADO'' NOT NULL,'
            || 'OBSERVACION VARCHAR2(500 CHAR),'
            || 'ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,'
            || 'CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
            || 'CREATED_BY VARCHAR2(60 CHAR),'
            || 'CONSTRAINT INDECI_SUBSIDIO_EVT_CALC_PK PRIMARY KEY (ID),'
            || 'CONSTRAINT FK_SUBSIDIO_EVT_CALC_EMP FOREIGN KEY (EMPLEADO_ID) REFERENCES INDECI_EMPLEADO (ID),'
            || 'CONSTRAINT FK_SUBSIDIO_EVT_CALC_EVENTO FOREIGN KEY (EMPLEADO_EVENTO_ID) REFERENCES INDECI_EMPLEADO_EVENTO (ID),'
            || 'CONSTRAINT FK_SUBSIDIO_EVT_CALC_MOV FOREIGN KEY (MOVIMIENTO_PLANILLA_ID) REFERENCES INDECI_MOVIMIENTO_PLANILLA (ID),'
            || 'CONSTRAINT INDECI_SUBSIDIO_TIPO_CK CHECK (TIPO_SUBSIDIO IN (''ENFERMEDAD'',''MATERNIDAD'')),'
            || 'CONSTRAINT INDECI_SUBSIDIO_FECHAS_CK CHECK (FECHA_FIN_DESCANSO >= FECHA_INICIO_DESCANSO),'
            || 'CONSTRAINT INDECI_SUBSIDIO_ACTIVO_CK CHECK (ACTIVO IN (0,1))'
            || ')'
            || ' TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE('INDECI_SUBSIDIO_EVENTO_CALCULO -> creada en TBS ' || v_ts);
    ELSE
        DBMS_OUTPUT.PUT_LINE('INDECI_SUBSIDIO_EVENTO_CALCULO ya existe. Sin cambios.');
    END IF;
END;
/

DECLARE
    v_ts VARCHAR2(30);

    PROCEDURE add_ix_if_missing(p_name VARCHAR2, p_sql VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_INDEXES
         WHERE INDEX_NAME = p_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE(p_name || ' -> creado.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_name || ' ya existe.');
        END IF;
    END;
BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    add_ix_if_missing(
        'INDECI_SUBSIDIO_EVT_EMP_ANIO_IX',
        'CREATE INDEX INDECI_SUBSIDIO_EVT_EMP_ANIO_IX '
        || 'ON INDECI_SUBSIDIO_EVENTO_CALCULO (EMPLEADO_ID, ANIO_CALENDARIO, ACTIVO) '
        || 'TABLESPACE ' || v_ts);

    add_ix_if_missing(
        'INDECI_SUBSIDIO_EVT_EVENTO_IX',
        'CREATE INDEX INDECI_SUBSIDIO_EVT_EVENTO_IX '
        || 'ON INDECI_SUBSIDIO_EVENTO_CALCULO (EMPLEADO_EVENTO_ID, ACTIVO) '
        || 'TABLESPACE ' || v_ts);

    add_ix_if_missing(
        'INDECI_SUBSIDIO_EVT_MOV_IX',
        'CREATE INDEX INDECI_SUBSIDIO_EVT_MOV_IX '
        || 'ON INDECI_SUBSIDIO_EVENTO_CALCULO (MOVIMIENTO_PLANILLA_ID, ACTIVO) '
        || 'TABLESPACE ' || v_ts);
END;
/

COMMENT ON TABLE INDECI_SUBSIDIO_EVENTO_CALCULO IS
    'P0 subsidios CAS: trazabilidad por evento medico de dias entidad, dias EsSalud, codigos PLAME 0915/0916/2073 y pago diferencial.';

COMMIT;
