-- ============================================================================
-- V010_76 - Tabla INDECI_IR4TA_CONFIG_ANUAL + seeds 2024/2025/2026
--
-- Configuracion anual de Rentas de 4ta Categoria para trabajadores CAS.
-- El motor de planilla (GeneradorPlanillaService) consulta esta tabla para
-- obtener la UIT y tasa de retencion vigente por periodo, en lugar de leer
-- directamente de TBL_PARAMETRO_REMUNERATIVO.
--
-- Base normativa: TUO LIR Art. 33 inc. e) - D.S. 122-94-EF - SUNAT 3042.
-- Ejecutar conectado como GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

-- ----------------------------------------------------------------------------
-- 1) Tabla principal
-- ----------------------------------------------------------------------------
DECLARE
    v_ts     VARCHAR2(30);
    v_exists NUMBER;
    v_rows   NUMBER;

    PROCEDURE eliminar_tabla_vacia IS
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_TABLES
         WHERE TABLE_NAME = 'INDECI_IR4TA_CONFIG_ANUAL';
        IF v_exists = 0 THEN RETURN; END IF;

        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM INDECI_IR4TA_CONFIG_ANUAL' INTO v_rows;
        IF v_rows > 0 THEN
            DBMS_OUTPUT.PUT_LINE('INDECI_IR4TA_CONFIG_ANUAL tiene ' || v_rows || ' filas. No se elimina.');
            RETURN;
        END IF;
        EXECUTE IMMEDIATE 'DROP TABLE INDECI_IR4TA_CONFIG_ANUAL CASCADE CONSTRAINTS PURGE';
        DBMS_OUTPUT.PUT_LINE('Tabla vacia eliminada (CASCADE CONSTRAINTS).');
    END;

    PROCEDURE crear_tabla_si_falta(p_tabla VARCHAR2, p_ddl VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_TABLES
         WHERE TABLE_NAME = UPPER(p_tabla);
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_tabla || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_tabla || ' ya existe. Sin cambios.');
        END IF;
    END;

BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    DBMS_OUTPUT.PUT_LINE('Tablespace detectado: ' || v_ts);

    eliminar_tabla_vacia();

    crear_tabla_si_falta(
        'INDECI_IR4TA_CONFIG_ANUAL',
        'CREATE TABLE INDECI_IR4TA_CONFIG_ANUAL ('
        || 'ID                     NUMBER GENERATED BY DEFAULT AS IDENTITY,'
        || 'ANIO_FISCAL            NUMBER(4)      NOT NULL,'
        || 'VIGENCIA_INICIO        DATE           NOT NULL,'
        || 'VIGENCIA_FIN           DATE,'
        || 'UIT_VIGENTE            NUMBER(10,2)   NOT NULL,'
        || 'TASA_IR4TA             NUMBER(6,4)    DEFAULT 8 NOT NULL,'
        || 'BASE_INAFECTA_IR4TA    NUMBER(10,2),'
        || 'FUENTE_OFICIAL         VARCHAR2(500)  NOT NULL,'
        || 'URL_FUENTE_OFICIAL     VARCHAR2(1000),'
        || 'FECHA_PUBLICACION      DATE,'
        || 'OBSERVACION            VARCHAR2(200),'
        || 'ESTADO                 VARCHAR2(20)   DEFAULT ''BORRADOR'' NOT NULL,'
        || 'BLOQUEADO_POR_PLANILLA NUMBER(1)      DEFAULT 0 NOT NULL,'
        || 'MOTIVO_ANULACION       VARCHAR2(500),'
        || 'ANULADO_POR            VARCHAR2(100),'
        || 'ANULADO_EN             TIMESTAMP,'
        || 'CREADO_POR             VARCHAR2(100)  NOT NULL,'
        || 'CREADO_EN              TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,'
        || 'MODIFICADO_POR         VARCHAR2(100),'
        || 'MODIFICADO_EN          TIMESTAMP,'
        || 'CONSTRAINT INDECI_IR4TA_CFG_PK       PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_IR4TA_CFG_ESTADO_CK CHECK (ESTADO IN (''BORRADOR'',''VIGENTE'',''CERRADO'',''ANULADO'')),'
        || 'CONSTRAINT INDECI_IR4TA_CFG_BLOQ_CK  CHECK (BLOQUEADO_POR_PLANILLA IN (0,1)),'
        || 'CONSTRAINT INDECI_IR4TA_CFG_UIT_CK   CHECK (UIT_VIGENTE > 0),'
        || 'CONSTRAINT INDECI_IR4TA_CFG_TASA_CK  CHECK (TASA_IR4TA > 0)'
        || ')'
    );

    DBMS_OUTPUT.PUT_LINE('V010_76 tabla lista.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR V010_76 (tabla): ' || SQLERRM);
        RAISE;
END;
/

-- ----------------------------------------------------------------------------
-- 2) Indices
-- ----------------------------------------------------------------------------
DECLARE
    PROCEDURE crear_indice_si_falta(
        p_index_name VARCHAR2,
        p_table_name VARCHAR2,
        p_columns    VARCHAR2
    ) IS
        v_exists NUMBER;
        v_ts     VARCHAR2(30);
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_INDEXES
         WHERE INDEX_NAME = UPPER(p_index_name);
        IF v_exists > 0 THEN
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' ya existe. Sin cambios.');
            RETURN;
        END IF;
        SELECT TABLESPACE_NAME INTO v_ts
          FROM USER_TABLES
         WHERE TABLE_NAME = UPPER(p_table_name);
        EXECUTE IMMEDIATE
            'CREATE INDEX ' || p_index_name
            || ' ON ' || p_table_name || ' ' || p_columns
            || ' TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE(p_index_name || ' -> creado en TBS ' || v_ts);
    END;

BEGIN
    crear_indice_si_falta('INDECI_IR4TA_CFG_ANIO_IDX',   'INDECI_IR4TA_CONFIG_ANUAL', '(ANIO_FISCAL)');
    crear_indice_si_falta('INDECI_IR4TA_CFG_ESTADO_IDX',  'INDECI_IR4TA_CONFIG_ANUAL', '(ESTADO)');
    crear_indice_si_falta('INDECI_IR4TA_CFG_FECHA_IDX',   'INDECI_IR4TA_CONFIG_ANUAL', '(VIGENCIA_INICIO, VIGENCIA_FIN)');
    DBMS_OUTPUT.PUT_LINE('V010_76 indices listos.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR V010_76 (indices): ' || SQLERRM);
        RAISE;
END;
/

-- ----------------------------------------------------------------------------
-- 3) Seeds 2024 / 2025 / 2026
-- UIT 2024=5150, 2025=5350, 2026=5500 (D.S. 301-2025-EF).
-- BASE_INAFECTA = 75% UIT (Art. 33 inc. e TUO LIR).
-- TASA_IR4TA = 8% (uniforme CAS).
-- ----------------------------------------------------------------------------
DECLARE
    v_count NUMBER;
BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM INDECI_IR4TA_CONFIG_ANUAL' INTO v_count;
    IF v_count = 0 THEN
        -- 2024 — Cerrado
        EXECUTE IMMEDIATE
            'INSERT INTO INDECI_IR4TA_CONFIG_ANUAL '
            || '(ID,ANIO_FISCAL,VIGENCIA_INICIO,VIGENCIA_FIN,UIT_VIGENTE,'
            || 'TASA_IR4TA,BASE_INAFECTA_IR4TA,FUENTE_OFICIAL,ESTADO,CREADO_POR) '
            || 'VALUES (1,2024,DATE ''2024-01-01'',DATE ''2024-12-31'',5150,'
            || '8,3862.50,''TUO LIR Art. 33 - D.S. 122-94-EF - R.S. 013-2007/SUNAT'',''CERRADO'',''SISTEMA'')';

        -- 2025 — Cerrado
        EXECUTE IMMEDIATE
            'INSERT INTO INDECI_IR4TA_CONFIG_ANUAL '
            || '(ID,ANIO_FISCAL,VIGENCIA_INICIO,VIGENCIA_FIN,UIT_VIGENTE,'
            || 'TASA_IR4TA,BASE_INAFECTA_IR4TA,FUENTE_OFICIAL,ESTADO,CREADO_POR) '
            || 'VALUES (2,2025,DATE ''2025-01-01'',DATE ''2025-12-31'',5350,'
            || '8,4012.50,''TUO LIR Art. 33 - D.S. 122-94-EF - R.S. 013-2007/SUNAT'',''CERRADO'',''SISTEMA'')';

        -- 2026 — Vigente (D.S. 301-2025-EF, UIT=5500)
        EXECUTE IMMEDIATE
            'INSERT INTO INDECI_IR4TA_CONFIG_ANUAL '
            || '(ID,ANIO_FISCAL,VIGENCIA_INICIO,VIGENCIA_FIN,UIT_VIGENTE,'
            || 'TASA_IR4TA,BASE_INAFECTA_IR4TA,FUENTE_OFICIAL,ESTADO,CREADO_POR) '
            || 'VALUES (3,2026,DATE ''2026-01-01'',DATE ''2026-12-31'',5500,'
            || '8,4125.00,''D.S. 301-2025-EF (UIT 2026) - TUO LIR Art. 33 - R.S. 013-2007/SUNAT'',''VIGENTE'',''SISTEMA'')';

        BEGIN
            EXECUTE IMMEDIATE
                'ALTER TABLE INDECI_IR4TA_CONFIG_ANUAL MODIFY ID '
                || 'GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)';
            DBMS_OUTPUT.PUT_LINE('Secuencia IDENTITY reiniciada (START WITH LIMIT VALUE).');
        EXCEPTION
            WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Aviso: ' || SQLERRM);
        END;

        DBMS_OUTPUT.PUT_LINE('Seeds IR4TA CONFIG -> 3 filas (2024/2025/2026) insertadas.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('INDECI_IR4TA_CONFIG_ANUAL ya tiene datos. Seeds omitidos.');
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('V010_76 finalizado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR V010_76 (seeds): ' || SQLERRM);
        RAISE;
END;
/

-- Verificacion
SELECT ID, ANIO_FISCAL, VIGENCIA_INICIO, VIGENCIA_FIN,
       UIT_VIGENTE, TASA_IR4TA, BASE_INAFECTA_IR4TA, ESTADO
  FROM INDECI_IR4TA_CONFIG_ANUAL
 ORDER BY ANIO_FISCAL;
