-- ============================================================================
-- V010_94 — Tabla INDECI_IR4TA_CONTROL_ANUAL (control de tope por trabajador/año)
--
-- CONTEXTO (plan ir4ta-tope-anual / pendiente B2):
--   Estado de control anual de la suspensión de retención IR4ta de cada
--   trabajador CAS con constancia. Una fila por (EMPLEADO_ID, ANIO_FISCAL).
--
--   El acumulado conocido por INDECI se RECALCULA desde planillas cerradas
--   (no es un valor editable a mano). El TIPO_TOPE es un flag MANUAL fijado
--   por RR. HH. (default GENERAL_CAS).
--
--   Esta tabla NO altera el motor ni las planillas históricas: solo registra
--   monitoreo, detección de exceso y la confirmación documentada del reinicio.
--
-- Relación: SUSPENSION_4TA_ID -> INDECI_SUSPENSION_4TA(ID) (V010_48).
-- Auditoría fina: se delega a la infra @Auditable/INDECI (no tabla nueva).
--
-- IDEMPOTENTE. Ejecutar conectado como GESTIONRRHH / Oracle 19c+.
-- Rollback: V010_94__ir4ta_control_anual_rollback.sql
-- ============================================================================

SET SERVEROUTPUT ON;

-- ----------------------------------------------------------------------------
-- 1) Tabla principal
-- ----------------------------------------------------------------------------
DECLARE
    v_ts     VARCHAR2(30);
    v_exists NUMBER;
BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_SUSPENSION_4TA';

    DBMS_OUTPUT.PUT_LINE('Tablespace detectado: ' || v_ts);

    SELECT COUNT(*) INTO v_exists
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_IR4TA_CONTROL_ANUAL';

    IF v_exists > 0 THEN
        DBMS_OUTPUT.PUT_LINE('INDECI_IR4TA_CONTROL_ANUAL ya existe. Sin cambios.');
    ELSE
        EXECUTE IMMEDIATE
            'CREATE TABLE INDECI_IR4TA_CONTROL_ANUAL ('
            || 'ID                     NUMBER GENERATED BY DEFAULT AS IDENTITY,'
            || 'EMPLEADO_ID            NUMBER         NOT NULL,'
            || 'ANIO_FISCAL            NUMBER(4)      NOT NULL,'
            || 'SUSPENSION_4TA_ID      NUMBER,'
            -- Flag manual de RR. HH.: qué tope aplica al trabajador.
            || 'TIPO_TOPE              VARCHAR2(20)   DEFAULT ''GENERAL_CAS'' NOT NULL,'
            || 'TOPE_ANUAL_APLICADO    NUMBER(12,2),'
            -- Acumulado conocido por INDECI (recalculado desde planillas cerradas).
            || 'ACUMULADO_INDECI       NUMBER(14,2)   DEFAULT 0 NOT NULL,'
            || 'PCT_CONSUMIDO          NUMBER(7,2),'
            || 'ULTIMO_PERIODO_CALC    VARCHAR2(7),'    -- 'YYYY-MM'
            || 'ESTADO_CONTROL         VARCHAR2(40)   DEFAULT ''VIGENTE'' NOT NULL,'
            -- Detección de exceso.
            || 'PERIODO_EXCESO         VARCHAR2(7),'
            || 'FECHA_DETECCION_EXCESO TIMESTAMP,'
            -- Confirmación de reinicio de retención (RR. HH.).
            || 'PERIODO_REINICIO       VARCHAR2(7),'
            || 'SUSTENTO_REINICIO      VARCHAR2(1000),'
            || 'CONFIRMADO_POR         VARCHAR2(100),'
            || 'CONFIRMADO_EN          TIMESTAMP,'
            || 'OBSERVACION            VARCHAR2(500),'
            || 'CREADO_POR             VARCHAR2(100)  NOT NULL,'
            || 'CREADO_EN              TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,'
            || 'MODIFICADO_POR         VARCHAR2(100),'
            || 'MODIFICADO_EN          TIMESTAMP,'
            || 'CONSTRAINT INDECI_IR4TA_CTRL_PK        PRIMARY KEY (ID),'
            || 'CONSTRAINT INDECI_IR4TA_CTRL_UK        UNIQUE (EMPLEADO_ID, ANIO_FISCAL),'
            || 'CONSTRAINT INDECI_IR4TA_CTRL_TIPO_CK   CHECK (TIPO_TOPE IN (''GENERAL_CAS'',''DIRECTOR_SIMILAR'')),'
            || 'CONSTRAINT INDECI_IR4TA_CTRL_ESTADO_CK CHECK (ESTADO_CONTROL IN ('
            || '''VIGENTE'',''ALERTA_80_PORCIENTO'',''ALERTA_90_PORCIENTO'',''CERCA_DEL_TOPE'','
            || '''EXCEDE_TOPE_REQUIERE_VALIDACION'',''REINICIO_CONFIRMADO'',''RETENCION_ACTIVA'','
            || '''VENCIDA'',''ANULADA'')),'
            || 'CONSTRAINT INDECI_IR4TA_CTRL_ACUM_CK   CHECK (ACUMULADO_INDECI >= 0),'
            || 'CONSTRAINT INDECI_IR4TA_CTRL_SUSP_FK   FOREIGN KEY (SUSPENSION_4TA_ID) '
            || 'REFERENCES INDECI_SUSPENSION_4TA (ID)'
            || ') TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE('INDECI_IR4TA_CONTROL_ANUAL -> creada en TBS ' || v_ts);
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR V010_94 (tabla): ' || SQLERRM);
        RAISE;
END;
/

-- ----------------------------------------------------------------------------
-- 2) Índices
-- ----------------------------------------------------------------------------
DECLARE
    PROCEDURE crear_indice_si_falta(
        p_index_name VARCHAR2,
        p_table_name VARCHAR2,
        p_columns    VARCHAR2
    ) IS
        v_exists NUMBER;
        v_ts     VARCHAR2(30);
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_INDEXES
         WHERE INDEX_NAME = UPPER(p_index_name);
        IF v_exists > 0 THEN
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' ya existe. Sin cambios.');
            RETURN;
        END IF;
        SELECT TABLESPACE_NAME INTO v_ts
          FROM USER_TABLES
         WHERE TABLE_NAME = UPPER(p_table_name);
        EXECUTE IMMEDIATE
            'CREATE INDEX ' || p_index_name
            || ' ON ' || p_table_name || ' ' || p_columns
            || ' TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE(p_index_name || ' -> creado en TBS ' || v_ts);
    EXCEPTION
        -- ORA-01408: la lista de columnas ya está indexada (p.ej. por una
        -- constraint UNIQUE). No es error: el índice ya cumple su función.
        WHEN OTHERS THEN
            IF SQLCODE = -1408 THEN
                DBMS_OUTPUT.PUT_LINE(p_index_name || ' omitido: lista ya indexada.');
            ELSE
                RAISE;
            END IF;
    END;
BEGIN
    -- (EMPLEADO_ID, ANIO_FISCAL) ya está indexada por la constraint UNIQUE
    -- INDECI_IR4TA_CTRL_UK → no se crea índice adicional (evita ORA-01408).
    crear_indice_si_falta('INDECI_IR4TA_CTRL_ESTADO_IDX', 'INDECI_IR4TA_CONTROL_ANUAL', '(ESTADO_CONTROL)');
    crear_indice_si_falta('INDECI_IR4TA_CTRL_SUSP_IDX',   'INDECI_IR4TA_CONTROL_ANUAL', '(SUSPENSION_4TA_ID)');
    DBMS_OUTPUT.PUT_LINE('V010_94 índices listos.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR V010_94 (índices): ' || SQLERRM);
        RAISE;
END;
/

-- Verificación
SELECT TABLE_NAME FROM USER_TABLES  WHERE TABLE_NAME = 'INDECI_IR4TA_CONTROL_ANUAL';
SELECT INDEX_NAME FROM USER_INDEXES WHERE TABLE_NAME = 'INDECI_IR4TA_CONTROL_ANUAL' ORDER BY INDEX_NAME;
