-- ============================================================================
-- V010_74 - Tabla INDECI_ESSALUD_VIGENCIA + seeds 2024/2025/2026
--
-- Defensa:
--   - Tablespace heredado de INDECI_EMPLEADO (evita ORA-01950/00959).
--   - Si la tabla existe VACIA, DROP TABLE CASCADE CONSTRAINTS PURGE (no DROP INDEX
--     suelto: ORA-02429 en indice PK). Recrea tabla + secuencia IDENTITY correcta.
--   - Seeds con ID explicito + restart identity.
-- Ejecutar conectado como GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

-- ----------------------------------------------------------------------------
-- 1) Reparacion + tabla principal
-- ----------------------------------------------------------------------------
DECLARE
    v_ts     VARCHAR2(30);
    v_exists NUMBER;
    v_rows   NUMBER;

    PROCEDURE eliminar_tabla_vacia IS
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_TABLES
         WHERE TABLE_NAME = 'INDECI_ESSALUD_VIGENCIA';
        IF v_exists = 0 THEN
            RETURN;
        END IF;

        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM INDECI_ESSALUD_VIGENCIA' INTO v_rows;
        IF v_rows > 0 THEN
            DBMS_OUTPUT.PUT_LINE(
                'INDECI_ESSALUD_VIGENCIA tiene ' || v_rows || ' filas. No se elimina.'
            );
            RETURN;
        END IF;

        -- CASCADE CONSTRAINTS: elimina PK, indices secundarios y secuencia IDENTITY.
        -- No usar DROP INDEX previo (ORA-02429 sobre indice de PK).
        EXECUTE IMMEDIATE 'DROP TABLE INDECI_ESSALUD_VIGENCIA CASCADE CONSTRAINTS PURGE';
        DBMS_OUTPUT.PUT_LINE(
            'Tabla vacia eliminada (CASCADE CONSTRAINTS): secuencia IDENTITY en USERS corregida.'
        );
    END;

    PROCEDURE crear_tabla_si_falta(p_tabla VARCHAR2, p_ddl VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_TABLES
         WHERE TABLE_NAME = UPPER(p_tabla);
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_tabla || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_tabla || ' ya existe. Sin cambios.');
        END IF;
    END;

BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    DBMS_OUTPUT.PUT_LINE('Tablespace detectado: ' || v_ts);

    eliminar_tabla_vacia();

    crear_tabla_si_falta(
        'INDECI_ESSALUD_VIGENCIA',
        'CREATE TABLE INDECI_ESSALUD_VIGENCIA ('
        || 'ID                     NUMBER GENERATED BY DEFAULT AS IDENTITY,'
        || 'ANIO_VIGENCIA          NUMBER(4)     NOT NULL,'
        || 'VIGENCIA_INICIO        DATE          NOT NULL,'
        || 'VIGENCIA_FIN           DATE,'
        || 'UIT_VIGENTE            NUMBER(10,2)  NOT NULL,'
        || 'PCT_BASE_CAS           NUMBER(6,4)   DEFAULT 45    NOT NULL,'
        || 'PCT_ESSALUD            NUMBER(6,4)   DEFAULT 9     NOT NULL,'
        || 'PCT_ESSALUD_EPS        NUMBER(6,4)   DEFAULT 6.75  NOT NULL,'
        || 'PCT_CREDITO_EPS        NUMBER(6,4)   DEFAULT 2.25  NOT NULL,'
        || 'FUENTE_OFICIAL         VARCHAR2(500) NOT NULL,'
        || 'URL_FUENTE_OFICIAL     VARCHAR2(1000),'
        || 'FECHA_PUBLICACION      DATE,'
        || 'OBSERVACION            VARCHAR2(1000),'
        || 'ESTADO                 VARCHAR2(20)  DEFAULT ''VIGENTE'' NOT NULL,'
        || 'BLOQUEADO_POR_PLANILLA NUMBER(1)     DEFAULT 0 NOT NULL,'
        || 'MOTIVO_ANULACION       VARCHAR2(500),'
        || 'ANULADO_POR            VARCHAR2(100),'
        || 'ANULADO_EN             TIMESTAMP,'
        || 'CREADO_POR             VARCHAR2(100) NOT NULL,'
        || 'CREADO_EN              TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,'
        || 'MODIFICADO_POR         VARCHAR2(100),'
        || 'MODIFICADO_EN          TIMESTAMP,'
        || 'CONSTRAINT INDECI_ESSALUD_VIG_PK      PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_ESSALUD_VIG_ESTADO_CK CHECK (ESTADO IN (''VIGENTE'',''PROGRAMADO'',''CERRADO'',''ANULADO'')),'
        || 'CONSTRAINT INDECI_ESSALUD_VIG_BLOQ_CK   CHECK (BLOQUEADO_POR_PLANILLA IN (0,1))'
        || ')'
    );

    DBMS_OUTPUT.PUT_LINE('V010_74 tabla lista.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR V010_74 (tabla): ' || SQLERRM);
        RAISE;
END;
/

-- ----------------------------------------------------------------------------
-- 2) Indices
-- ----------------------------------------------------------------------------
DECLARE
    PROCEDURE crear_indice_si_falta(
        p_index_name VARCHAR2,
        p_table_name VARCHAR2,
        p_columns    VARCHAR2
    ) IS
        v_exists NUMBER;
        v_ts     VARCHAR2(30);
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_INDEXES
         WHERE INDEX_NAME = UPPER(p_index_name);
        IF v_exists > 0 THEN
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' ya existe. Sin cambios.');
            RETURN;
        END IF;

        SELECT TABLESPACE_NAME INTO v_ts
          FROM USER_TABLES
         WHERE TABLE_NAME = UPPER(p_table_name);

        EXECUTE IMMEDIATE
            'CREATE INDEX ' || p_index_name
            || ' ON ' || p_table_name || ' ' || p_columns
            || ' TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE(p_index_name || ' -> creado en TBS ' || v_ts);
    END;

BEGIN
    crear_indice_si_falta(
        'INDECI_ESSALUD_VIG_ANIO_IDX',
        'INDECI_ESSALUD_VIGENCIA',
        '(ANIO_VIGENCIA)'
    );
    crear_indice_si_falta(
        'INDECI_ESSALUD_VIG_ESTADO_IDX',
        'INDECI_ESSALUD_VIGENCIA',
        '(ESTADO)'
    );
    crear_indice_si_falta(
        'INDECI_ESSALUD_VIG_FECHA_IDX',
        'INDECI_ESSALUD_VIGENCIA',
        '(VIGENCIA_INICIO, VIGENCIA_FIN)'
    );

    DBMS_OUTPUT.PUT_LINE('V010_74 indices listos.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR V010_74 (indices): ' || SQLERRM);
        RAISE;
END;
/

-- ----------------------------------------------------------------------------
-- 3) Seeds 2024 / 2025 / 2026
-- ----------------------------------------------------------------------------
DECLARE
    v_count NUMBER;
BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM INDECI_ESSALUD_VIGENCIA' INTO v_count;
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'INSERT INTO INDECI_ESSALUD_VIGENCIA '
            || '(ID,ANIO_VIGENCIA,VIGENCIA_INICIO,VIGENCIA_FIN,UIT_VIGENTE,'
            || 'PCT_BASE_CAS,PCT_ESSALUD,PCT_ESSALUD_EPS,PCT_CREDITO_EPS,'
            || 'FUENTE_OFICIAL,ESTADO,CREADO_POR) '
            || 'VALUES (1,2024,DATE ''2024-01-01'',DATE ''2024-12-31'',5150,'
            || '45,9,6.75,2.25,''SUNAT / EsSalud - D.S. 009-97-SA'',''CERRADO'',''SISTEMA'')';

        EXECUTE IMMEDIATE
            'INSERT INTO INDECI_ESSALUD_VIGENCIA '
            || '(ID,ANIO_VIGENCIA,VIGENCIA_INICIO,VIGENCIA_FIN,UIT_VIGENTE,'
            || 'PCT_BASE_CAS,PCT_ESSALUD,PCT_ESSALUD_EPS,PCT_CREDITO_EPS,'
            || 'FUENTE_OFICIAL,ESTADO,CREADO_POR) '
            || 'VALUES (2,2025,DATE ''2025-01-01'',DATE ''2025-12-31'',5350,'
            || '45,9,6.75,2.25,''SUNAT / EsSalud - D.S. 009-97-SA'',''CERRADO'',''SISTEMA'')';

        EXECUTE IMMEDIATE
            'INSERT INTO INDECI_ESSALUD_VIGENCIA '
            || '(ID,ANIO_VIGENCIA,VIGENCIA_INICIO,VIGENCIA_FIN,UIT_VIGENTE,'
            || 'PCT_BASE_CAS,PCT_ESSALUD,PCT_ESSALUD_EPS,PCT_CREDITO_EPS,'
            || 'FUENTE_OFICIAL,ESTADO,CREADO_POR) '
            || 'VALUES (3,2026,DATE ''2026-01-01'',DATE ''2026-12-31'',5500,'
            || '45,9,6.75,2.25,''SUNAT / EsSalud - D.S. 009-97-SA'',''VIGENTE'',''SISTEMA'')';

        BEGIN
            EXECUTE IMMEDIATE
                'ALTER TABLE INDECI_ESSALUD_VIGENCIA MODIFY ID '
                || 'GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)';
            DBMS_OUTPUT.PUT_LINE('Secuencia IDENTITY reiniciada (START WITH LIMIT VALUE).');
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Aviso: no se pudo reiniciar IDENTITY: ' || SQLERRM);
        END;

        DBMS_OUTPUT.PUT_LINE('Seeds ESSALUD VIGENCIA -> 3 filas (2024/2025/2026) insertadas.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('INDECI_ESSALUD_VIGENCIA ya tiene datos. Seeds omitidos.');
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('V010_74 finalizado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR V010_74 (seeds): ' || SQLERRM);
        RAISE;
END;
/

-- Verificacion
SELECT ID, ANIO_VIGENCIA, VIGENCIA_INICIO, VIGENCIA_FIN,
       UIT_VIGENTE, PCT_BASE_CAS, PCT_ESSALUD, ESTADO
  FROM INDECI_ESSALUD_VIGENCIA
 ORDER BY ANIO_VIGENCIA;
