-- ============================================================================
-- V010_87 subsidio_seed_catalogos (P0-F1)
-- Catálogos administrables: tipos, estados, severidades, motivos.
-- ============================================================================
SET SERVEROUTPUT ON;
SET DEFINE OFF;

MERGE INTO INDECI_SUBSIDIO_CATALOGO d
USING (
    SELECT 'TIPO_CASO' AS TIPO_CATALOGO, 'ENFERMEDAD' AS CODIGO, 'Enfermedad / incapacidad temporal' AS NOMBRE FROM DUAL UNION ALL
    SELECT 'TIPO_CASO', 'MATERNIDAD', 'Maternidad' FROM DUAL UNION ALL
    SELECT 'ESTADO_CASO', 'BORRADOR', 'Borrador' FROM DUAL UNION ALL
    SELECT 'ESTADO_CASO', 'PENDIENTE_VALIDACION', 'Pendiente de validación' FROM DUAL UNION ALL
    SELECT 'ESTADO_CASO', 'CALCULADO', 'Calculado' FROM DUAL UNION ALL
    SELECT 'ESTADO_CASO', 'APLICADO_PLANILLA', 'Aplicado a planilla' FROM DUAL UNION ALL
    SELECT 'ESTADO_CASO', 'EN_TRAMITE_ESSALUD', 'En trámite EsSalud' FROM DUAL UNION ALL
    SELECT 'ESTADO_CASO', 'CERRADO', 'Cerrado' FROM DUAL UNION ALL
    SELECT 'ESTADO_TRAMO', 'BORRADOR', 'Borrador' FROM DUAL UNION ALL
    SELECT 'ESTADO_TRAMO', 'CALCULADO', 'Calculado' FROM DUAL UNION ALL
    SELECT 'ESTADO_TRAMO', 'APLICADO', 'Aplicado' FROM DUAL UNION ALL
    SELECT 'SEVERIDAD_VALIDACION', 'BLOQUEO', 'Bloqueo' FROM DUAL UNION ALL
    SELECT 'SEVERIDAD_VALIDACION', 'ALERTA', 'Alerta' FROM DUAL UNION ALL
    SELECT 'SEVERIDAD_VALIDACION', 'INFORMATIVA', 'Informativa' FROM DUAL
) s ON (d.TIPO_CATALOGO = s.TIPO_CATALOGO AND d.CODIGO = s.CODIGO)
WHEN NOT MATCHED THEN
    INSERT (TIPO_CATALOGO, CODIGO, NOMBRE, ACTIVO, ORDEN_VISUAL)
    VALUES (s.TIPO_CATALOGO, s.CODIGO, s.NOMBRE, 1, 100);

COMMIT;
DBMS_OUTPUT.PUT_LINE('V010_87 catalogos subsidio sincronizados.');
/
