-- ============================================================================
-- Spec 010 / V010_19 — Préstamos y saldo de vacaciones (SPEC §12.2 PANTALLA-08)
--
-- Habilita los saldos que muestra el Portal del Empleado:
--   1. INDECI_PRESTAMO        — préstamos del empleado con su saldo pendiente
--   2. INDECI_VACACION_SALDO  — días de vacaciones ganados/gozados por año
--
-- DECISIONES DE DISEÑO (alineadas con V010_10 / V010_17):
--   - Naming INDECI_* ; PKs IDENTITY — coherencia local.
--   - PRESTAMO: el saldo pendiente NO se almacena, se deriva
--     (MONTO_TOTAL − CUOTAS_PAGADAS × CUOTA_MENSUAL) en el servicio.
--   - VACACION_SALDO: UK (EMPLEADO_ID, ANIO) — una fila por empleado y año;
--     el saldo de días se deriva (DIAS_GANADOS − DIAS_GOZADOS).
--   - Sin ON DELETE CASCADE: bajas lógicas (ESTADO / ACTIVO).
--
-- DEFENSA EN PROFUNDIDAD: idempotente (add_table_if_missing / add_index_if_missing).
-- Ejecutar en esquema GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;

    PROCEDURE add_table_if_missing(
        p_table_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM ALL_TABLES
         WHERE OWNER = 'GESTIONRRHH' AND TABLE_NAME = p_table_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl;
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' -> creada.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(
        p_index_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM ALL_INDEXES
         WHERE OWNER = 'GESTIONRRHH' AND INDEX_NAME = p_index_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl;
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' -> creado.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    -- ==================================================================
    -- 1) INDECI_PRESTAMO
    -- ==================================================================
    add_table_if_missing(
        'INDECI_PRESTAMO',
        'CREATE TABLE GESTIONRRHH.INDECI_PRESTAMO ('
        ||   'ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        ||   'EMPLEADO_ID     NUMBER NOT NULL,'
        ||   'DESCRIPCION     VARCHAR2(200 CHAR) NOT NULL,'
        ||   'MONTO_TOTAL     NUMBER(12,2) NOT NULL,'
        ||   'NUMERO_CUOTAS   NUMBER(4) NOT NULL,'
        ||   'CUOTA_MENSUAL   NUMBER(12,2) NOT NULL,'
        ||   'CUOTAS_PAGADAS  NUMBER(4) DEFAULT 0 NOT NULL,'
        ||   'ESTADO          VARCHAR2(12 CHAR) DEFAULT ''ACTIVO'' NOT NULL,'
        ||   'FECHA_INICIO    DATE,'
        ||   'ACTIVO          NUMBER(1) DEFAULT 1 NOT NULL,'
        ||   'CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CONSTRAINT INDECI_PRESTAMO_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_PRESTAMO_EMP_FK FOREIGN KEY (EMPLEADO_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_EMPLEADO (ID),'
        ||   'CONSTRAINT INDECI_PRESTAMO_ESTADO_CK '
        ||     'CHECK (ESTADO IN (''ACTIVO'', ''CANCELADO'')),'
        ||   'CONSTRAINT INDECI_PRESTAMO_CUOTAS_CK '
        ||     'CHECK (CUOTAS_PAGADAS >= 0 AND CUOTAS_PAGADAS <= NUMERO_CUOTAS),'
        ||   'CONSTRAINT INDECI_PRESTAMO_MONTO_CK '
        ||     'CHECK (MONTO_TOTAL >= 0 AND CUOTA_MENSUAL >= 0 AND NUMERO_CUOTAS > 0)'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_PRESTAMO_EMP',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_PRESTAMO_EMP '
        || 'ON GESTIONRRHH.INDECI_PRESTAMO (EMPLEADO_ID, ESTADO)'
    );

    -- ==================================================================
    -- 2) INDECI_VACACION_SALDO
    -- ==================================================================
    add_table_if_missing(
        'INDECI_VACACION_SALDO',
        'CREATE TABLE GESTIONRRHH.INDECI_VACACION_SALDO ('
        ||   'ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        ||   'EMPLEADO_ID    NUMBER NOT NULL,'
        ||   'ANIO           NUMBER(4) NOT NULL,'
        ||   'DIAS_GANADOS   NUMBER(6,2) DEFAULT 0 NOT NULL,'
        ||   'DIAS_GOZADOS   NUMBER(6,2) DEFAULT 0 NOT NULL,'
        ||   'OBSERVACION    VARCHAR2(200 CHAR),'
        ||   'ACTIVO         NUMBER(1) DEFAULT 1 NOT NULL,'
        ||   'CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CONSTRAINT INDECI_VAC_SALDO_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_VAC_SALDO_EMP_FK FOREIGN KEY (EMPLEADO_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_EMPLEADO (ID),'
        ||   'CONSTRAINT INDECI_VAC_SALDO_DIAS_CK '
        ||     'CHECK (DIAS_GANADOS >= 0 AND DIAS_GOZADOS >= 0),'
        ||   'CONSTRAINT INDECI_VAC_SALDO_UK UNIQUE (EMPLEADO_ID, ANIO)'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_VAC_SALDO_EMP',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_VAC_SALDO_EMP '
        || 'ON GESTIONRRHH.INDECI_VACACION_SALDO (EMPLEADO_ID)'
    );

    -- ==================================================================
    -- COMMENTS
    -- ==================================================================
    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_PRESTAMO IS '
        || '''SPEC §12.2 PANTALLA-08 — Préstamos del empleado. Saldo pendiente derivado: '
        || 'MONTO_TOTAL - CUOTAS_PAGADAS * CUOTA_MENSUAL.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_PRESTAMO.ESTADO IS '
        || '''ACTIVO | CANCELADO — pasa a CANCELADO cuando CUOTAS_PAGADAS = NUMERO_CUOTAS.''';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_VACACION_SALDO IS '
        || '''SPEC §12.2 PANTALLA-08 — Días de vacaciones por empleado y año. '
        || 'Saldo derivado: DIAS_GANADOS - DIAS_GOZADOS.''';

    DBMS_OUTPUT.PUT_LINE('V010_19 finalizado.');

    SELECT COUNT(*) INTO v_count
      FROM ALL_TABLES
     WHERE OWNER = 'GESTIONRRHH'
       AND TABLE_NAME IN ('INDECI_PRESTAMO', 'INDECI_VACACION_SALDO');
    DBMS_OUTPUT.PUT_LINE('Tablas presentes ahora en GESTIONRRHH: ' || v_count || ' / 2.');
END;
/
