-- ============================================================================
-- V010_75 - INDECI_EPS (catálogo) + INDECI_EMPLEADO_SALUD_EPS
-- Módulo: Salud / EPS del empleado
-- Normativa: D.S. 009-97-SA — aporte empleador EsSalud 9%
-- Ejecutar conectado como GESTIONRRHH / Oracle 19c+
-- ============================================================================

SET SERVEROUTPUT ON;

-- ----------------------------------------------------------------------------
-- 1) Catálogo INDECI_EPS
-- ----------------------------------------------------------------------------
DECLARE
    v_ts     VARCHAR2(30);
    v_exists NUMBER;
BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    SELECT COUNT(*) INTO v_exists
      FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_EPS';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE INDECI_EPS ('
            || 'ID       NUMBER GENERATED BY DEFAULT AS IDENTITY,'
            || 'CODIGO   VARCHAR2(20)  NOT NULL,'
            || 'NOMBRE   VARCHAR2(200) NOT NULL,'
            || 'ACTIVO   NUMBER(1)     DEFAULT 1 NOT NULL,'
            || 'CONSTRAINT INDECI_EPS_PK      PRIMARY KEY (ID),'
            || 'CONSTRAINT INDECI_EPS_COD_UK  UNIQUE (CODIGO),'
            || 'CONSTRAINT INDECI_EPS_ACT_CK  CHECK (ACTIVO IN (0,1))'
            || ') TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE('INDECI_EPS -> creada en TBS ' || v_ts);
    ELSE
        DBMS_OUTPUT.PUT_LINE('INDECI_EPS ya existe.');
    END IF;
END;
/

-- Seeds catálogo EPS
DECLARE v_count NUMBER;
BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM INDECI_EPS' INTO v_count;
    IF v_count = 0 THEN
        INSERT INTO INDECI_EPS (ID, CODIGO, NOMBRE, ACTIVO) VALUES (1, 'FESALUD', 'FESALUD S.A.',   1);
        INSERT INTO INDECI_EPS (ID, CODIGO, NOMBRE, ACTIVO) VALUES (2, 'PACIFICO','PACIFICO EPS',   1);
        INSERT INTO INDECI_EPS (ID, CODIGO, NOMBRE, ACTIVO) VALUES (3, 'RIMAC',   'RIMAC EPS',      1);
        INSERT INTO INDECI_EPS (ID, CODIGO, NOMBRE, ACTIVO) VALUES (4, 'MAPFRE',  'MAPFRE EPS',     1);
        EXECUTE IMMEDIATE
            'ALTER TABLE INDECI_EPS MODIFY ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)';
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Seeds INDECI_EPS -> 4 filas insertadas.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('INDECI_EPS ya tiene datos. Seeds omitidos.');
    END IF;
END;
/

-- ----------------------------------------------------------------------------
-- 2) Tabla principal INDECI_EMPLEADO_SALUD_EPS
-- ----------------------------------------------------------------------------
DECLARE
    v_ts     VARCHAR2(30);
    v_exists NUMBER;
BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    SELECT COUNT(*) INTO v_exists
      FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_EMPLEADO_SALUD_EPS';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE INDECI_EMPLEADO_SALUD_EPS ('
            || 'ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY,'
            || 'EMPLEADO_ID         NUMBER        NOT NULL,'
            || 'TIPO_COBERTURA      VARCHAR2(20)  NOT NULL,'
            || 'EPS_ID              NUMBER,'
            || 'FECHA_INICIO        DATE          NOT NULL,'
            || 'FECHA_FIN           DATE,'
            || 'ESTADO              VARCHAR2(20)  DEFAULT ''ACTIVO'' NOT NULL,'
            || 'DOCUMENTO_SUSTENTO  VARCHAR2(500),'
            || 'OBSERVACION         VARCHAR2(1000),'
            || 'MOTIVO_ANULACION    VARCHAR2(500),'
            || 'ANULADO_POR         VARCHAR2(100),'
            || 'ANULADO_EN          TIMESTAMP,'
            || 'CREADO_POR          VARCHAR2(100) NOT NULL,'
            || 'CREADO_EN           TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,'
            || 'MODIFICADO_POR      VARCHAR2(100),'
            || 'MODIFICADO_EN       TIMESTAMP,'
            || 'CONSTRAINT INDECI_EMP_SAL_EPS_PK       PRIMARY KEY (ID),'
            || 'CONSTRAINT INDECI_EMP_SAL_EPS_EMP_FK   FOREIGN KEY (EMPLEADO_ID)  REFERENCES INDECI_EMPLEADO(ID),'
            || 'CONSTRAINT INDECI_EMP_SAL_EPS_EPS_FK   FOREIGN KEY (EPS_ID)       REFERENCES INDECI_EPS(ID),'
            || 'CONSTRAINT INDECI_EMP_SAL_EPS_TIPO_CK  CHECK (TIPO_COBERTURA IN (''ESSALUD'',''ESSALUD_EPS'')),'
            || 'CONSTRAINT INDECI_EMP_SAL_EPS_EST_CK   CHECK (ESTADO IN (''ACTIVO'',''CERRADO'',''INACTIVO'',''ANULADO''))'
            || ') TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE('INDECI_EMPLEADO_SALUD_EPS -> creada en TBS ' || v_ts);
    ELSE
        DBMS_OUTPUT.PUT_LINE('INDECI_EMPLEADO_SALUD_EPS ya existe.');
    END IF;
END;
/

-- Índices
DECLARE
    PROCEDURE crear_idx(p_name VARCHAR2, p_table VARCHAR2, p_cols VARCHAR2) IS
        v_exists NUMBER;
        v_ts     VARCHAR2(30);
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = UPPER(p_name);
        IF v_exists > 0 THEN RETURN; END IF;
        SELECT TABLESPACE_NAME INTO v_ts FROM USER_TABLES WHERE TABLE_NAME = UPPER(p_table);
        EXECUTE IMMEDIATE 'CREATE INDEX ' || p_name || ' ON ' || p_table || ' ' || p_cols || ' TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE(p_name || ' -> creado.');
    END;
BEGIN
    crear_idx('INDECI_EMP_SAL_EPS_EMP_IDX',   'INDECI_EMPLEADO_SALUD_EPS', '(EMPLEADO_ID)');
    crear_idx('INDECI_EMP_SAL_EPS_EST_IDX',   'INDECI_EMPLEADO_SALUD_EPS', '(ESTADO)');
    crear_idx('INDECI_EMP_SAL_EPS_FECHA_IDX', 'INDECI_EMPLEADO_SALUD_EPS', '(EMPLEADO_ID, FECHA_INICIO, FECHA_FIN)');
    DBMS_OUTPUT.PUT_LINE('V010_75 indices listos.');
END;
/

COMMIT;
-- Verificación
SELECT ID, CODIGO, NOMBRE, ACTIVO FROM INDECI_EPS ORDER BY ID;
