-- ============================================================================
-- Spec 013 / B3 / V010_32 — Correlativo de documentos MCPP (NRO_PLANILLA)
--                          (Etapa 3 · B3 · M14)
--
-- Mantiene el último número de planilla emitido por (entidad, año, mes, tipo) para
-- el MCPP Web. El service lo incrementa con lock pesimista (SELECT … FOR UPDATE)
-- al generar cada PLL*.TXT, garantizando NRO_PLANILLA únicos y secuenciales.
--
-- NOTA: el archivo PLAME (.rem/.jor/.snl) NO usa esta tabla: su nombre es
-- determinístico = 0601 + YYYY + MM + RUC. Solo MCPP requiere correlativo.
--
-- DECISIONES DE DISEÑO:
--   - PK IDENTITY + UNIQUE (COD_ENTIDAD, ANIO, MES, TIPO_DOCUMENTO) — coherencia
--     con el resto del schema (IDENTITY); la combinación natural va en el UK y es
--     la que se bloquea con FOR UPDATE.
--   - TIPO_DOCUMENTO admite 'MCPP' (correlativo global del período) y las variantes
--     por tipo ('MCPP_01/03/12'); la semántica exacta (global vs por tipo) se
--     valida con archivos reales — los PLL observados (0019-0024, 0032-0038, 0039)
--     sugieren correlativo GLOBAL por período. PLAME incluido por completitud.
--
-- DEFENSA EN PROFUNDIDAD: idempotente. Sin seed (las filas las crea el service
-- on-demand al pedir el primer correlativo de cada combinación).
-- Ejecutar en esquema GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;

    PROCEDURE add_table_if_missing(
        p_table_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM ALL_TABLES
         WHERE OWNER = 'GESTIONRRHH' AND TABLE_NAME = p_table_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl;
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' -> creada.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    add_table_if_missing(
        'INDECI_CORRELATIVO_DOCUMENTO',
        'CREATE TABLE GESTIONRRHH.INDECI_CORRELATIVO_DOCUMENTO ('
        ||   'ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        ||   'COD_ENTIDAD     VARCHAR2(6 CHAR)  NOT NULL,'
        ||   'ANIO            NUMBER(4) NOT NULL,'
        ||   'MES             NUMBER(2) NOT NULL,'
        ||   'TIPO_DOCUMENTO  VARCHAR2(10 CHAR) NOT NULL,'
        ||   'ULTIMO_NRO      NUMBER(10) DEFAULT 0 NOT NULL,'
        ||   'CONSTRAINT INDECI_CORREL_DOC_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_CORREL_DOC_UK '
        ||     'UNIQUE (COD_ENTIDAD, ANIO, MES, TIPO_DOCUMENTO),'
        ||   'CONSTRAINT INDECI_CORREL_DOC_TIPO_CK '
        ||     'CHECK (TIPO_DOCUMENTO IN '
        ||       '(''MCPP'', ''MCPP_01'', ''MCPP_03'', ''MCPP_12'', ''PLAME'')),'
        ||   'CONSTRAINT INDECI_CORREL_DOC_MES_CK CHECK (MES BETWEEN 1 AND 12),'
        ||   'CONSTRAINT INDECI_CORREL_DOC_NRO_CK CHECK (ULTIMO_NRO >= 0)'
        || ')'
    );

    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_CORRELATIVO_DOCUMENTO IS '
        || '''B3 / M14 — Correlativo de NRO_PLANILLA MCPP por (entidad, año, mes, tipo). '
        || 'Se incrementa con lock pesimista. PLAME no lo usa (nombre determinístico).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_CORRELATIVO_DOCUMENTO.ULTIMO_NRO IS '
        || '''Último número emitido. siguiente() devuelve ULTIMO_NRO + 1 y persiste.''';

    DBMS_OUTPUT.PUT_LINE('V010_32 finalizado.');

    SELECT COUNT(*) INTO v_count
      FROM ALL_TABLES
     WHERE OWNER = 'GESTIONRRHH' AND TABLE_NAME = 'INDECI_CORRELATIVO_DOCUMENTO';
    DBMS_OUTPUT.PUT_LINE('INDECI_CORRELATIVO_DOCUMENTO presente: ' || v_count || ' / 1.');
END;
/
