-- ============================================================================
-- Spec 013 / B3 / V010_29 — Log de exportaciones PLAME / MCPP
--                          (Etapa 3 · B3 · M09)
--
-- Registra cada archivo generado (PLAME .rem/.jor/.snl, MCPP por tipo) con su
-- metadata: hash de integridad, nro de líneas, totales y, post-pago, el ticket
-- MCPP. Complementa la auditoría AOP (TBL_LOG_AUDITORIA registra quién/cuándo;
-- esta tabla guarda el QUÉ se generó).
--
-- DECISIONES DE DISEÑO (alineadas con V010_10):
--   - Naming INDECI_*; PK IDENTITY — coherencia local.
--   - PERIODO como VARCHAR2(7) "YYYY-MM" (mismo criterio que ArchivoBancoService),
--     sin FK dura: el log es transversal y debe sobrevivir cambios de período.
--   - TOTAL_* en NUMBER(14,2): los montos de exportación SUNAT deben ser exactos
--     (BigDecimal en Java).
--   - NRO_TICKET_MCPP nullable: se llena después, al confirmar pago (M14).
--
-- DEFENSA EN PROFUNDIDAD: idempotente (add_table_if_missing / add_index_if_missing).
-- Ejecutar en esquema GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;

    PROCEDURE add_table_if_missing(
        p_table_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM ALL_TABLES
         WHERE OWNER = 'GESTIONRRHH' AND TABLE_NAME = p_table_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl;
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' -> creada.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(
        p_index_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM ALL_INDEXES
         WHERE OWNER = 'GESTIONRRHH' AND INDEX_NAME = p_index_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl;
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' -> creado.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    add_table_if_missing(
        'INDECI_EXPORT_ARCHIVO',
        'CREATE TABLE GESTIONRRHH.INDECI_EXPORT_ARCHIVO ('
        ||   'ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        ||   'PERIODO           VARCHAR2(7 CHAR)  NOT NULL,'
        ||   'TIPO_ARCHIVO      VARCHAR2(12 CHAR) NOT NULL,'
        ||   'NOMBRE_ARCHIVO    VARCHAR2(80 CHAR) NOT NULL,'
        ||   'HASH_SHA256       VARCHAR2(64 CHAR) NOT NULL,'
        ||   'NRO_LINEAS        NUMBER(8) DEFAULT 0 NOT NULL,'
        ||   'TOTAL_INGRESOS    NUMBER(14,2),'
        ||   'TOTAL_DESCUENTOS  NUMBER(14,2),'
        ||   'GENERADO_POR      NUMBER,'
        ||   'FECHA_GENERADO    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'NRO_TICKET_MCPP   VARCHAR2(20 CHAR),'
        ||   'CONSTRAINT INDECI_EXPORT_ARCHIVO_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_EXPORT_ARCHIVO_TIPO_CK '
        ||     'CHECK (TIPO_ARCHIVO IN '
        ||       '(''PLAME_REM'', ''PLAME_JOR'', ''PLAME_SNL'', '
        ||       ' ''MCPP_01'', ''MCPP_03'', ''MCPP_12'')),'
        ||   'CONSTRAINT INDECI_EXPORT_ARCHIVO_LINEAS_CK '
        ||     'CHECK (NRO_LINEAS >= 0)'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_EXPORT_PER_TIPO',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_EXPORT_PER_TIPO '
        || 'ON GESTIONRRHH.INDECI_EXPORT_ARCHIVO (PERIODO, TIPO_ARCHIVO)'
    );

    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_EXPORT_ARCHIVO IS '
        || '''B3 / M09 — Log de archivos PLAME/MCPP generados: hash, líneas, totales y ticket MCPP. '
        || 'Complementa TBL_LOG_AUDITORIA (que registra quién/cuándo).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_EXPORT_ARCHIVO.TIPO_ARCHIVO IS '
        || '''PLAME_REM | PLAME_JOR | PLAME_SNL | MCPP_01 | MCPP_03 | MCPP_12.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_EXPORT_ARCHIVO.HASH_SHA256 IS '
        || '''SHA-256 del contenido del archivo: integridad y no-repudio de lo declarado.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_EXPORT_ARCHIVO.NRO_TICKET_MCPP IS '
        || '''Ticket MCPP de Tesorería post-pago (M14). NULL hasta confirmar.''';

    DBMS_OUTPUT.PUT_LINE('V010_29 finalizado.');

    SELECT COUNT(*) INTO v_count
      FROM ALL_TABLES
     WHERE OWNER = 'GESTIONRRHH' AND TABLE_NAME = 'INDECI_EXPORT_ARCHIVO';
    DBMS_OUTPUT.PUT_LINE('INDECI_EXPORT_ARCHIVO presente: ' || v_count || ' / 1.');
END;
/
