-- ============================================================================
-- Spec 010 / V010_02 — Columnas MEF en INDECI_CONCEPTO_PLANILLA
-- Cumple LEY-01 (Ley 32448 — CODIGO_MEF obligatorio) y LEY-07 (MUC vs CUC).
-- Las columnas se crean NULLABLE; el NOT NULL se aplica en una migración
-- posterior (V010_06) recién después de validar el backfill de V010_05.
-- Ejecutar en esquema GESTIONRRHH / Oracle.
-- ============================================================================

ALTER TABLE GESTIONRRHH.INDECI_CONCEPTO_PLANILLA ADD (
    CODIGO_MEF          VARCHAR2(10 CHAR),
    TIPO_CONCEPTO       VARCHAR2(30 CHAR),
    AFECTO_IR_5TA       VARCHAR2(1 CHAR) DEFAULT 'N',
    AFECTO_APORTE_PENS  VARCHAR2(1 CHAR) DEFAULT 'N',
    AFECTO_ESSALUD      VARCHAR2(1 CHAR) DEFAULT 'N',
    ES_MUC              VARCHAR2(1 CHAR) DEFAULT 'N',
    ES_CUC              VARCHAR2(1 CHAR) DEFAULT 'N',
    REGIMEN_APLICABLE   VARCHAR2(20 CHAR) DEFAULT 'TODOS',
    FECHA_VIG_INI       DATE DEFAULT SYSDATE,
    FECHA_VIG_FIN       DATE
);

ALTER TABLE GESTIONRRHH.INDECI_CONCEPTO_PLANILLA ADD CONSTRAINT INDECI_CONCEPTO_TIPO_CK
    CHECK (TIPO_CONCEPTO IS NULL OR TIPO_CONCEPTO IN (
        'REMUNERATIVO',
        'NO_REMUNERATIVO',
        'DESCUENTO',
        'APORTE_TRABAJADOR',
        'APORTE_EMPLEADOR'
    ));

ALTER TABLE GESTIONRRHH.INDECI_CONCEPTO_PLANILLA ADD CONSTRAINT INDECI_CONCEPTO_REGIMEN_CK
    CHECK (REGIMEN_APLICABLE IS NULL OR REGIMEN_APLICABLE IN (
        '276', '728', '1057', 'SERVIR', 'TODOS'
    ));

ALTER TABLE GESTIONRRHH.INDECI_CONCEPTO_PLANILLA ADD CONSTRAINT INDECI_CONCEPTO_AFECTO_5TA_CK
    CHECK (AFECTO_IR_5TA IN ('S', 'N'));
ALTER TABLE GESTIONRRHH.INDECI_CONCEPTO_PLANILLA ADD CONSTRAINT INDECI_CONCEPTO_AFECTO_PENS_CK
    CHECK (AFECTO_APORTE_PENS IN ('S', 'N'));
ALTER TABLE GESTIONRRHH.INDECI_CONCEPTO_PLANILLA ADD CONSTRAINT INDECI_CONCEPTO_AFECTO_ESS_CK
    CHECK (AFECTO_ESSALUD IN ('S', 'N'));
ALTER TABLE GESTIONRRHH.INDECI_CONCEPTO_PLANILLA ADD CONSTRAINT INDECI_CONCEPTO_ES_MUC_CK
    CHECK (ES_MUC IN ('S', 'N'));
ALTER TABLE GESTIONRRHH.INDECI_CONCEPTO_PLANILLA ADD CONSTRAINT INDECI_CONCEPTO_ES_CUC_CK
    CHECK (ES_CUC IN ('S', 'N'));

COMMENT ON COLUMN GESTIONRRHH.INDECI_CONCEPTO_PLANILLA.CODIGO_MEF IS
    'Ley 32448: código oficial AIRHSP del concepto. Obligatorio para pagar.';
COMMENT ON COLUMN GESTIONRRHH.INDECI_CONCEPTO_PLANILLA.TIPO_CONCEPTO IS
    'Clasificación del motor: REMUNERATIVO|NO_REMUNERATIVO|DESCUENTO|APORTE_TRABAJADOR|APORTE_EMPLEADOR.';
COMMENT ON COLUMN GESTIONRRHH.INDECI_CONCEPTO_PLANILLA.ES_MUC IS
    'Monto Único Consolidado (régimen 276). LEY-07: lo que recibe el trabajador en boleta.';
COMMENT ON COLUMN GESTIONRRHH.INDECI_CONCEPTO_PLANILLA.ES_CUC IS
    'Costo Único Consolidado (Ley 32448): costo total para la entidad. NO va en boleta.';
COMMENT ON COLUMN GESTIONRRHH.INDECI_CONCEPTO_PLANILLA.REGIMEN_APLICABLE IS
    'Régimen al que aplica: 276|728|1057|SERVIR|TODOS.';
