-- ============================================================================
-- F1.4a / V010_40 — INDECI_EMPLEADO_REINTEGRO
--
-- Soporte de Motor v3 PASO 5b — reintegro por días.
--
-- CONTEXTO:
--   El Excel CAS consolidado del cliente maneja "días de reintegro" como un
--   componente que prorratea la remuneración del empleado por X días extra
--   (típicamente cuando un trabajador regulariza un período no pagado).
--
--   Fórmula (D.Leg. 276 / Excel):
--       reintegro = base_remunerativa / 30 × dias_reintegro
--
--   F1.4 agrega la persistencia. F1.5 conectará el cálculo al flujo del
--   motor (cuando MONTO_CONTRATO también esté en juego).
--
-- DECISIONES DE DISEÑO:
--   - PERIODO VARCHAR2(6) (formato YYYYMM) — consistente con
--     INDECI_ASISTENCIA_CABECERA.PERIODO y MOVIMIENTO_PLANILLA.PERIODO.
--     NO se usa PERIODO_ID porque la búsqueda del motor recibe el string
--     periodo directamente.
--   - UK por (EMPLEADO_ID, PERIODO): un solo reintegro vigente por empleado/
--     período. Re-cargar implica baja lógica del anterior.
--   - DIAS_REINTEGRO NUMBER(3) con CHECK 1..31. Cero no tiene sentido
--     (sería "no hay reintegro" → borrar la fila).
--   - MOTIVO VARCHAR2(200) obligatorio: auditoría exige trazar por qué se
--     reintegra (RRHH lo justifica). OBSERVACION opcional para texto largo.
--   - ACTIVO NUMBER(1) DEFAULT 1: baja lógica, no eliminación física.
--   - Tablespace explícito (TS_GESTIONRRHH_DATA) heredado de INDECI_EMPLEADO
--     en CREATE TABLE y CREATE UNIQUE INDEX (ver [[claude-md-aspiracional]]).
--
-- IDEMPOTENTE. Schema NO hardcodeado. Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

-- ----------------------------------------------------------------------------
-- 1) Tabla nueva con tablespace explícito.
-- ----------------------------------------------------------------------------
DECLARE
    v_ts VARCHAR2(30);
    PROCEDURE add_table_if_missing(
        p_table_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_TABLES
         WHERE TABLE_NAME = p_table_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    add_table_if_missing(
        'INDECI_EMPLEADO_REINTEGRO',
        'CREATE TABLE INDECI_EMPLEADO_REINTEGRO ('
        ||   'ID              NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,'
        ||   'EMPLEADO_ID     NUMBER(10) NOT NULL,'
        ||   'PERIODO         VARCHAR2(6 CHAR) NOT NULL,'
        ||   'DIAS_REINTEGRO  NUMBER(3) NOT NULL,'
        ||   'MOTIVO          VARCHAR2(200 CHAR) NOT NULL,'
        ||   'OBSERVACION     VARCHAR2(500 CHAR),'
        ||   'ACTIVO          NUMBER(1) DEFAULT 1 NOT NULL,'
        ||   'CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CREATED_BY      VARCHAR2(60 CHAR),'
        ||   'CONSTRAINT INDECI_EMP_REINTEGRO_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT FK_EMP_REINTEGRO_EMPLEADO '
        ||      'FOREIGN KEY (EMPLEADO_ID) REFERENCES INDECI_EMPLEADO (ID),'
        ||   'CONSTRAINT INDECI_EMP_REINTEGRO_ACTIVO_CK '
        ||      'CHECK (ACTIVO IN (0, 1)),'
        ||   'CONSTRAINT INDECI_EMP_REINTEGRO_DIAS_CK '
        ||      'CHECK (DIAS_REINTEGRO BETWEEN 1 AND 31)'
        || ')'
    );

    EXECUTE IMMEDIATE 'COMMENT ON TABLE INDECI_EMPLEADO_REINTEGRO IS '
        || '''F1.4 — Reintegro por días: prorratea remuneración por días extra de período no pagado. Motor PASO 5b lo consume.''';
END;
/

-- ----------------------------------------------------------------------------
-- 2) UK (EMPLEADO_ID, PERIODO) — un solo reintegro vigente por empleado/período.
--    Patrón: CREATE UNIQUE INDEX con TABLESPACE explícito, luego ADD CONSTRAINT
--    USING INDEX (ver V010_39 y [[claude-md-aspiracional]] — evita ORA-00959).
-- ----------------------------------------------------------------------------
DECLARE
    v_ts                VARCHAR2(30);
    v_constraint_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_constraint_exists
      FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_NAME = 'INDECI_EMP_REINTEGRO_UK';

    IF v_constraint_exists > 0 THEN
        DBMS_OUTPUT.PUT_LINE('INDECI_EMP_REINTEGRO_UK ya existe. Sin cambios.');
        RETURN;
    END IF;

    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    -- Limpiar índice huérfano (defensivo).
    BEGIN
        EXECUTE IMMEDIATE 'DROP INDEX INDECI_EMP_REINTEGRO_UK';
        DBMS_OUTPUT.PUT_LINE('Índice huérfano previo -> eliminado.');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -1418 THEN
                NULL; -- no existe, OK.
            ELSE
                RAISE;
            END IF;
    END;

    EXECUTE IMMEDIATE
        'CREATE UNIQUE INDEX INDECI_EMP_REINTEGRO_UK '
        || 'ON INDECI_EMPLEADO_REINTEGRO (EMPLEADO_ID, PERIODO) '
        || 'TABLESPACE ' || v_ts;
    DBMS_OUTPUT.PUT_LINE('Índice único INDECI_EMP_REINTEGRO_UK -> creado en TBS ' || v_ts);

    EXECUTE IMMEDIATE
        'ALTER TABLE INDECI_EMPLEADO_REINTEGRO '
        || 'ADD CONSTRAINT INDECI_EMP_REINTEGRO_UK '
        || 'UNIQUE (EMPLEADO_ID, PERIODO) '
        || 'USING INDEX INDECI_EMP_REINTEGRO_UK';
    DBMS_OUTPUT.PUT_LINE('Constraint INDECI_EMP_REINTEGRO_UK -> creado.');
END;
/

-- ----------------------------------------------------------------------------
-- 3) Índice de soporte para queries del repo (lookup por empleado+activo).
--    El UK ya cubre (EMPLEADO_ID, PERIODO); este es para listados por empleado.
-- ----------------------------------------------------------------------------
DECLARE
    v_exists NUMBER;
    v_ts     VARCHAR2(30);
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'INDECI_EMP_REINTEGRO_EMP_IX';

    IF v_exists > 0 THEN
        DBMS_OUTPUT.PUT_LINE('INDECI_EMP_REINTEGRO_EMP_IX ya existe. Sin cambios.');
        RETURN;
    END IF;

    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    EXECUTE IMMEDIATE
        'CREATE INDEX INDECI_EMP_REINTEGRO_EMP_IX '
        || 'ON INDECI_EMPLEADO_REINTEGRO (EMPLEADO_ID, ACTIVO) '
        || 'TABLESPACE ' || v_ts;
    DBMS_OUTPUT.PUT_LINE('INDECI_EMP_REINTEGRO_EMP_IX -> creado en TBS ' || v_ts);
END;
/

COMMIT;

-- ----------------------------------------------------------------------------
-- 4) Verificación rápida.
-- ----------------------------------------------------------------------------
DECLARE
    v_tabla_existe   NUMBER;
    v_uk_existe      NUMBER;
    v_ix_emp_existe  NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_tabla_existe
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO_REINTEGRO';
    SELECT COUNT(*) INTO v_uk_existe
      FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_NAME = 'INDECI_EMP_REINTEGRO_UK';
    SELECT COUNT(*) INTO v_ix_emp_existe
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'INDECI_EMP_REINTEGRO_EMP_IX';

    DBMS_OUTPUT.PUT_LINE('---');
    DBMS_OUTPUT.PUT_LINE('Tabla     INDECI_EMPLEADO_REINTEGRO     : ' || v_tabla_existe);
    DBMS_OUTPUT.PUT_LINE('UK        INDECI_EMP_REINTEGRO_UK       : ' || v_uk_existe);
    DBMS_OUTPUT.PUT_LINE('Índice    INDECI_EMP_REINTEGRO_EMP_IX   : ' || v_ix_emp_existe);
    DBMS_OUTPUT.PUT_LINE('V010_40 listo.');
END;
/
