-- ============================================================================
-- F0.2 / V010_34 — INDECI_TIPO_CARGO + INDECI_CARGO + ALTERs de puesto/oficina
--                  (Estabilización post-pull 2026-05-31 — soporta entities
--                   Cargo, TipoCargo y la nueva FK CARGO_ID en EMPLEADO_PUESTO_HIST,
--                   más la nueva FK ESTRUCTURA_ORGANICA_ID en OFICINA).
--
-- CONTEXTO:
--   El pull reciente trajo las entities Cargo/TipoCargo + repos y refactorizó
--   EmpleadoPuestoService para validar CARGO_ID contra INDECI_CARGO. Sin esta
--   tabla, todos los guardar/actualizar de puesto fallan en producción.
--
-- DECISIONES DE DISEÑO:
--   - PK IDENTITY (consistente con el resto del schema; ver [[claude-md-aspiracional]]).
--   - INDECI_TIPO_CARGO con UK por CODIGO (TipoCargoRepository.findByCodigo).
--   - INDECI_CARGO con FK TIPO_CARGO_ID nullable (un cargo puede no tener tipo aún).
--   - ALTER ADD COLUMN idempotente: try/catch ORA-01430 (la columna ya existe).
--   - FKs SOFT (ENABLE NOVALIDATE) en los ALTERs porque pueden existir filas pre-pull
--     con CARGO_ID nulo.
--   - Seeds mínimos de TIPO_CARGO según convenciones del sector público peruano
--     (NOMBRADO, CONTRATADO, ENCARGADO, CAS, FUNCIONARIO, PRACTICANTE). RRHH puede
--     ampliarlos por UI.
--   - NO se hardcodea el nombre del schema. Las tablas se crean en el schema del
--     usuario conectado y los lookups idempotentes usan USER_* (no ALL_* con OWNER).
--
-- IDEMPOTENTE: ejecutar varias veces no rompe. Ejecutar como el usuario propietario
-- del schema de planillas (Oracle 19c+).
-- ============================================================================

SET SERVEROUTPUT ON;

-- ----------------------------------------------------------------------------
-- 1) Tablas nuevas (patrón add_table_if_missing).
-- ----------------------------------------------------------------------------
-- Tablas heredan el TABLESPACE de INDECI_EMPLEADO (ancla estable que sabemos
-- existe en el schema). Evita ORA-00959 cuando el default tablespace del
-- usuario está vacío o roto (caso TBS_RRHH no existe).
DECLARE
    v_ts VARCHAR2(30);
    PROCEDURE add_table_if_missing(
        p_table_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_TABLES
         WHERE TABLE_NAME = p_table_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO';
    add_table_if_missing(
        'INDECI_TIPO_CARGO',
        'CREATE TABLE INDECI_TIPO_CARGO ('
        ||   'ID         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,'
        ||   'CODIGO     VARCHAR2(20 CHAR),'
        ||   'NOMBRE     VARCHAR2(100 CHAR) NOT NULL,'
        ||   'ACTIVO     NUMBER(1) DEFAULT 1 NOT NULL,'
        ||   'CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CONSTRAINT INDECI_TIPO_CARGO_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_TIPO_CARGO_CODIGO_UK UNIQUE (CODIGO),'
        ||   'CONSTRAINT INDECI_TIPO_CARGO_ACTIVO_CK CHECK (ACTIVO IN (0, 1))'
        || ')'
    );

    add_table_if_missing(
        'INDECI_CARGO',
        'CREATE TABLE INDECI_CARGO ('
        ||   'ID            NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,'
        ||   'TIPO_CARGO_ID NUMBER(10),'
        ||   'CODIGO        VARCHAR2(20 CHAR),'
        ||   'NOMBRE        VARCHAR2(150 CHAR) NOT NULL,'
        ||   'ACTIVO        NUMBER(1) DEFAULT 1 NOT NULL,'
        ||   'CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CONSTRAINT INDECI_CARGO_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_CARGO_TIPO_FK FOREIGN KEY (TIPO_CARGO_ID) '
        ||      'REFERENCES INDECI_TIPO_CARGO (ID),'
        ||   'CONSTRAINT INDECI_CARGO_ACTIVO_CK CHECK (ACTIVO IN (0, 1))'
        || ')'
    );

    EXECUTE IMMEDIATE 'COMMENT ON TABLE INDECI_TIPO_CARGO IS '
        || '''F0.2 — Catálogo de tipos de cargo (Nombrado / Contratado / CAS / Funcionario / etc.). Pull 2026-05-31.''';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE INDECI_CARGO IS '
        || '''F0.2 — Catálogo de cargos. Soporte de Cargo entity + validación en EmpleadoPuestoService. Pull 2026-05-31.''';

    DBMS_OUTPUT.PUT_LINE('V010_34 tablas listas.');
END;
/

-- ----------------------------------------------------------------------------
-- 2) ALTER TABLE idempotente: agregar columnas si no existen.
--    a) INDECI_EMPLEADO_PUESTO_HIST.CARGO_ID  → FK INDECI_CARGO
--    b) INDECI_OFICINA.ESTRUCTURA_ORGANICA_ID → FK INDECI_ESTRUCTURA_ORGANICA
-- ----------------------------------------------------------------------------
DECLARE
    PROCEDURE add_column_if_missing(
        p_table_name  VARCHAR2,
        p_column_name VARCHAR2,
        p_column_ddl  VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = p_table_name
           AND COLUMN_NAME = p_column_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table_name
                || ' ADD ' || p_column_ddl;
            DBMS_OUTPUT.PUT_LINE(p_table_name || '.' || p_column_name || ' -> agregada.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table_name || '.' || p_column_name || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_fk_if_missing(
        p_table_name      VARCHAR2,
        p_constraint_name VARCHAR2,
        p_constraint_ddl  VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_CONSTRAINTS
         WHERE TABLE_NAME = p_table_name
           AND CONSTRAINT_NAME = p_constraint_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table_name
                || ' ADD CONSTRAINT ' || p_constraint_name || ' ' || p_constraint_ddl;
            DBMS_OUTPUT.PUT_LINE(p_constraint_name || ' -> creado.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_constraint_name || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    -- 2a) EMPLEADO_PUESTO_HIST.CARGO_ID
    add_column_if_missing(
        'INDECI_EMPLEADO_PUESTO_HIST',
        'CARGO_ID',
        'CARGO_ID NUMBER(10)'
    );
    add_fk_if_missing(
        'INDECI_EMPLEADO_PUESTO_HIST',
        'INDECI_EMP_PUESTO_CARGO_FK',
        'FOREIGN KEY (CARGO_ID) REFERENCES INDECI_CARGO (ID) ENABLE NOVALIDATE'
    );

    -- 2b) OFICINA.ESTRUCTURA_ORGANICA_ID
    add_column_if_missing(
        'INDECI_OFICINA',
        'ESTRUCTURA_ORGANICA_ID',
        'ESTRUCTURA_ORGANICA_ID NUMBER(10)'
    );
    add_fk_if_missing(
        'INDECI_OFICINA',
        'INDECI_OFICINA_ESTRUCTURA_FK',
        'FOREIGN KEY (ESTRUCTURA_ORGANICA_ID) REFERENCES INDECI_ESTRUCTURA_ORGANICA (ID) ENABLE NOVALIDATE'
    );

    DBMS_OUTPUT.PUT_LINE('V010_34 ALTERs aplicados.');
END;
/

-- ----------------------------------------------------------------------------
-- 3) Índices de soporte para los joins lazy del nuevo Cargo/Oficina mapping.
-- ----------------------------------------------------------------------------
-- El índice hereda el TABLESPACE de la tabla padre (USER_TABLES.TABLESPACE_NAME).
-- Esto evita ORA-00959 cuando el default tablespace del usuario no existe.
DECLARE
    PROCEDURE add_index_if_missing(
        p_index_name VARCHAR2,
        p_table_name VARCHAR2,
        p_columns    VARCHAR2   -- e.g. '(CARGO_ID)'
    ) IS
        v_exists NUMBER;
        v_ts     VARCHAR2(30);
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM USER_INDEXES
         WHERE INDEX_NAME = p_index_name;
        IF v_exists > 0 THEN
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' ya existe. Sin cambios.');
            RETURN;
        END IF;

        SELECT TABLESPACE_NAME INTO v_ts
          FROM USER_TABLES
         WHERE TABLE_NAME = p_table_name;

        EXECUTE IMMEDIATE
            'CREATE INDEX ' || p_index_name
            || ' ON ' || p_table_name || ' ' || p_columns
            || ' TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE(p_index_name || ' -> creado en TBS ' || v_ts);
    END;
BEGIN
    add_index_if_missing(
        'INDECI_EMP_PUESTO_CARGO_IX',
        'INDECI_EMPLEADO_PUESTO_HIST',
        '(CARGO_ID)'
    );
    add_index_if_missing(
        'INDECI_CARGO_TIPO_IX',
        'INDECI_CARGO',
        '(TIPO_CARGO_ID)'
    );
    add_index_if_missing(
        'INDECI_OFICINA_ESTRUCTURA_IX',
        'INDECI_OFICINA',
        '(ESTRUCTURA_ORGANICA_ID)'
    );
    DBMS_OUTPUT.PUT_LINE('V010_34 índices listos.');
END;
/

-- ----------------------------------------------------------------------------
-- 4) Seed mínimo de TIPO_CARGO (idempotente).
--    RRHH puede ampliar por UI; mantener WHEN NOT MATCHED (no pisar lo cargado).
-- ----------------------------------------------------------------------------
MERGE INTO INDECI_TIPO_CARGO d
USING (
    SELECT 'NOMBRADO'    AS CODIGO, 'Nombrado'                AS NOMBRE FROM DUAL UNION ALL
    SELECT 'CONTRATADO'  AS CODIGO, 'Contratado por D.Leg.'   AS NOMBRE FROM DUAL UNION ALL
    SELECT 'CAS'         AS CODIGO, 'CAS (D.Leg. 1057)'       AS NOMBRE FROM DUAL UNION ALL
    SELECT 'FUNCIONARIO' AS CODIGO, 'Funcionario'             AS NOMBRE FROM DUAL UNION ALL
    SELECT 'ENCARGADO'   AS CODIGO, 'Encargado'               AS NOMBRE FROM DUAL UNION ALL
    SELECT 'PRACTICANTE' AS CODIGO, 'Practicante'             AS NOMBRE FROM DUAL UNION ALL
    SELECT 'SERVIR'      AS CODIGO, 'Régimen SERVIR'          AS NOMBRE FROM DUAL
) s
ON (d.CODIGO = s.CODIGO)
WHEN NOT MATCHED THEN
    INSERT (CODIGO, NOMBRE, ACTIVO, CREATED_AT)
    VALUES (s.CODIGO, s.NOMBRE, 1, SYSTIMESTAMP);

COMMIT;
