-- ============================================================================
-- V010_51 — Corrige objetos de esquema faltantes detectados por
--           scripts/verificacion-esquema.sql (2026-06-03).
--
-- Gaps detectados (entidad JPA ↔ tabla):
--   - TABLA  FALTANTE: INDECI_TIPO_PERSONAL     (catálogo base, ninguna migración la creaba)
--   - TABLA  FALTANTE: INDECI_META_PRESUPUESTAL (V010_22 falló por TBS_RRHH inexistente)
--   - TABLA  FALTANTE: INDECI_EXPORT_ARCHIVO    (V010_29 falló por TBS_RRHH inexistente)
--   - COLUMNA FALTANTE: INDECI_OFICINA.SEDE_ID
--
-- Causa raíz de las tablas: V010_22/V010_29 hacían CREATE TABLE sin TABLESPACE
-- explícito → ORA-00959 cuando el default del schema (TBS_RRHH) no existe.
-- Aquí se hereda el TABLESPACE de INDECI_EMPLEADO (ancla estable), igual que
-- V010_34/35/48. DDL fiel a V010_22/V010_29 y a las entidades. Idempotente.
-- Ejecutar en GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_ts VARCHAR2(30);

    PROCEDURE add_table_if_missing(p_table VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_column_if_missing(p_table VARCHAR2, p_col VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = p_table AND COLUMN_NAME = p_col;
        IF v = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD (' || p_ddl || ')';
            DBMS_OUTPUT.PUT_LINE(p_table || '.' || p_col || ' -> agregada.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table || '.' || p_col || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    -- 1) Catálogo INDECI_TIPO_PERSONAL (entidad: id, codigo, nombre).
    add_table_if_missing(
        'INDECI_TIPO_PERSONAL',
        'CREATE TABLE INDECI_TIPO_PERSONAL ('
        || 'ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'CODIGO VARCHAR2(20 CHAR),'
        || 'NOMBRE VARCHAR2(100 CHAR) NOT NULL,'
        || 'CONSTRAINT INDECI_TIPO_PERSONAL_PK PRIMARY KEY (ID)'
        || ')'
    );

    -- 2) INDECI_META_PRESUPUESTAL (DDL fiel a V010_22 + tablespace).
    add_table_if_missing(
        'INDECI_META_PRESUPUESTAL',
        'CREATE TABLE INDECI_META_PRESUPUESTAL ('
        || 'ID                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'PERIODO_ID         NUMBER NOT NULL,'
        || 'META               VARCHAR2(20 CHAR) NOT NULL,'
        || 'CENTRO_COSTO       VARCHAR2(60 CHAR),'
        || 'FUENTE_FINANC      VARCHAR2(20 CHAR),'
        || 'MONTO_CERTIFICADO  NUMBER(14,2) DEFAULT 0 NOT NULL,'
        || 'ACTIVO             NUMBER(1) DEFAULT 1 NOT NULL,'
        || 'CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        || 'UPDATED_AT         TIMESTAMP,'
        || 'CONSTRAINT INDECI_META_PRESUP_PK PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_META_PRESUP_PERIODO_FK FOREIGN KEY (PERIODO_ID) '
        ||   'REFERENCES INDECI_PERIODO_PLANILLA (ID),'
        || 'CONSTRAINT INDECI_META_PRESUP_UK UNIQUE (PERIODO_ID, META),'
        || 'CONSTRAINT INDECI_META_PRESUP_MONTO_CK CHECK (MONTO_CERTIFICADO >= 0)'
        || ')'
    );

    -- 3) INDECI_EXPORT_ARCHIVO (DDL fiel a V010_29 + tablespace).
    add_table_if_missing(
        'INDECI_EXPORT_ARCHIVO',
        'CREATE TABLE INDECI_EXPORT_ARCHIVO ('
        || 'ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'PERIODO           VARCHAR2(7 CHAR)  NOT NULL,'
        || 'TIPO_ARCHIVO      VARCHAR2(12 CHAR) NOT NULL,'
        || 'NOMBRE_ARCHIVO    VARCHAR2(80 CHAR) NOT NULL,'
        || 'HASH_SHA256       VARCHAR2(64 CHAR) NOT NULL,'
        || 'NRO_LINEAS        NUMBER(8) DEFAULT 0 NOT NULL,'
        || 'TOTAL_INGRESOS    NUMBER(14,2),'
        || 'TOTAL_DESCUENTOS  NUMBER(14,2),'
        || 'GENERADO_POR      NUMBER,'
        || 'FECHA_GENERADO    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        || 'NRO_TICKET_MCPP   VARCHAR2(20 CHAR),'
        || 'CONSTRAINT INDECI_EXPORT_ARCHIVO_PK PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_EXPORT_ARCHIVO_TIPO_CK '
        ||   'CHECK (TIPO_ARCHIVO IN '
        ||     '(''PLAME_REM'', ''PLAME_JOR'', ''PLAME_SNL'', '
        ||     ' ''MCPP_01'', ''MCPP_03'', ''MCPP_12'')),'
        || 'CONSTRAINT INDECI_EXPORT_ARCHIVO_LINEAS_CK CHECK (NRO_LINEAS >= 0)'
        || ')'
    );

    -- 4) Columna faltante INDECI_OFICINA.SEDE_ID (FK lógica a INDECI_SEDE).
    add_column_if_missing('INDECI_OFICINA', 'SEDE_ID', 'SEDE_ID NUMBER');

    DBMS_OUTPUT.PUT_LINE('V010_51 finalizado.');
END;
/
