-- ============================================================================
-- V010_88 subsidio_seed_parametros_v1 (P0-F1)
-- Parámetros iniciales referencia Excel LD mayo 2026.
-- ============================================================================
SET SERVEROUTPUT ON;
SET DEFINE OFF;

MERGE INTO INDECI_SUBSIDIO_PARAMETRO d
USING (
    SELECT 'UIT_REF' AS CODIGO, 'Referencia UIT' AS NOMBRE, 'REF' AS TIPO_VALOR FROM DUAL UNION ALL
    SELECT 'BIM_PCT_CAS', 'Tope BIM (% UIT)', 'DECIMAL' FROM DUAL UNION ALL
    SELECT 'DIVISOR_PROMEDIO', 'Divisor promedio base (días)', 'INTEGER' FROM DUAL UNION ALL
    SELECT 'DIAS_ENTIDAD_ENF', 'Días asumidos entidad enfermedad', 'INTEGER' FROM DUAL UNION ALL
    SELECT 'DIAS_ENTIDAD_MAT', 'Días asumidos entidad maternidad', 'INTEGER' FROM DUAL UNION ALL
    SELECT 'DIAS_MATERNIDAD_REG', 'Días maternidad regular', 'INTEGER' FROM DUAL UNION ALL
    SELECT 'DIAS_MATERNIDAD_AMP', 'Días maternidad ampliada', 'INTEGER' FROM DUAL UNION ALL
    SELECT 'REDONDEO_ESSALUD', 'Redondeo EsSalud', 'TEXTO' FROM DUAL UNION ALL
    SELECT 'REDONDEO_INDECI', 'Redondeo INDECI', 'TEXTO' FROM DUAL UNION ALL
    SELECT 'GAP_CITT_DIAS', 'Tolerancia continuidad CITT (días)', 'INTEGER' FROM DUAL
) s ON (d.CODIGO = s.CODIGO)
WHEN NOT MATCHED THEN
    INSERT (CODIGO, NOMBRE, TIPO_VALOR, ACTIVO)
    VALUES (s.CODIGO, s.NOMBRE, s.TIPO_VALOR, 1);

MERGE INTO INDECI_SUBSIDIO_PARAMETRO_VERSION d
USING (
    SELECT p.ID AS PARAMETRO_ID, 0.45 AS VALOR_NUMERICO, CAST(NULL AS VARCHAR2(500)) AS VALOR_TEXTO,
           DATE '2026-01-01' AS FECHA_VIG_INI, DATE '2026-12-31' AS FECHA_VIG_FIN,
           'VIGENTE' AS ESTADO, 'Excel LD mayo 2026' AS FUENTE_NORMATIVA, p.CODIGO
      FROM INDECI_SUBSIDIO_PARAMETRO p WHERE p.CODIGO = 'BIM_PCT_CAS'
    UNION ALL
    SELECT p.ID, 360, NULL, DATE '2026-01-01', DATE '2026-12-31', 'VIGENTE', 'EsSalud/Excel LD', p.CODIGO
      FROM INDECI_SUBSIDIO_PARAMETRO p WHERE p.CODIGO = 'DIVISOR_PROMEDIO'
    UNION ALL
    SELECT p.ID, 20, NULL, DATE '2026-01-01', DATE '2026-12-31', 'VIGENTE', 'D.S. 009-97-SA', p.CODIGO
      FROM INDECI_SUBSIDIO_PARAMETRO p WHERE p.CODIGO = 'DIAS_ENTIDAD_ENF'
    UNION ALL
    SELECT p.ID, 0, NULL, DATE '2026-01-01', DATE '2026-12-31', 'VIGENTE', 'Política INDECI', p.CODIGO
      FROM INDECI_SUBSIDIO_PARAMETRO p WHERE p.CODIGO = 'DIAS_ENTIDAD_MAT'
    UNION ALL
    SELECT p.ID, 98, NULL, DATE '2026-01-01', DATE '2026-12-31', 'VIGENTE', 'Ley 30367', p.CODIGO
      FROM INDECI_SUBSIDIO_PARAMETRO p WHERE p.CODIGO = 'DIAS_MATERNIDAD_REG'
    UNION ALL
    SELECT p.ID, 128, NULL, DATE '2026-01-01', DATE '2026-12-31', 'VIGENTE', 'Ley 30367 ampliación', p.CODIGO
      FROM INDECI_SUBSIDIO_PARAMETRO p WHERE p.CODIGO = 'DIAS_MATERNIDAD_AMP'
    UNION ALL
    SELECT p.ID, 1, NULL, DATE '2026-01-01', DATE '2026-12-31', 'VIGENTE', 'Operación INDECI', p.CODIGO
      FROM INDECI_SUBSIDIO_PARAMETRO p WHERE p.CODIGO = 'GAP_CITT_DIAS'
    UNION ALL
    SELECT p.ID, NULL, 'HALF_UP scale 0', DATE '2026-01-01', DATE '2026-12-31', 'VIGENTE', 'Excel LD', p.CODIGO
      FROM INDECI_SUBSIDIO_PARAMETRO p WHERE p.CODIGO = 'REDONDEO_ESSALUD'
    UNION ALL
    SELECT p.ID, NULL, 'HALF_UP scale 2', DATE '2026-01-01', DATE '2026-12-31', 'VIGENTE', 'Excel LD', p.CODIGO
      FROM INDECI_SUBSIDIO_PARAMETRO p WHERE p.CODIGO = 'REDONDEO_INDECI'
) s ON (d.PARAMETRO_ID = s.PARAMETRO_ID AND d.ESTADO = 'VIGENTE' AND d.FECHA_VIG_INI = s.FECHA_VIG_INI)
WHEN NOT MATCHED THEN
    INSERT (PARAMETRO_ID, VALOR_NUMERICO, VALOR_TEXTO, FECHA_VIG_INI, FECHA_VIG_FIN, ESTADO, FUENTE_NORMATIVA, CREATED_BY)
    VALUES (s.PARAMETRO_ID, s.VALOR_NUMERICO, s.VALOR_TEXTO, s.FECHA_VIG_INI, s.FECHA_VIG_FIN, s.ESTADO, s.FUENTE_NORMATIVA, 'SEED_V010_88');

COMMIT;
DBMS_OUTPUT.PUT_LINE('V010_88 parametros subsidio v1 sincronizados.');
/
