-- ============================================================================
-- Spec 010 / V010_17 — Módulo M04 Asistencia y Control de Tiempo (SPEC §12.2)
--
-- Habilita PANTALLA-02 (Carga de Asistencia, ROL_RRHH): calendario mensual por
-- empleado con tipo de día y minutos de tardanza.
--
-- TABLAS:
--   1. INDECI_ASISTENCIA_CABECERA  — una fila por empleado + período
--   2. INDECI_ASISTENCIA_DETALLE   — una fila por día del período
--
-- DECISIONES DE DISEÑO (alineadas con V010_10):
--   - Naming INDECI_* (no TBL_*) — coherencia local del schema.
--   - PKs IDENTITY (no SEQUENCE) — coherencia local.
--   - UK (EMPLEADO_ID, PERIODO) en cabecera: el servicio hace UPSERT (una sola
--     asistencia por empleado/período); no se usa baja lógica de duplicados.
--   - UK (CABECERA_ID, DIA) en detalle: un registro por día calendario.
--   - DESCUENTO_TARDANZA / DESCUENTO_FALTA: D.Leg. 276 Art. 24 (REGLA 276-02):
--       descuento_tardanza = ROUND((REMUNERACION_BASE/30/8/60) * total_min, 2)
--       descuento_falta    = ROUND((REMUNERACION_BASE/30) * dias_falta, 2)
--     El motor M05 (PASO 7) consumirá estos valores cuando se integre.
--   - Sin USUARIO_CREO/MODIFICO: auditoría centralizada en AuditoriaAspect.
--
-- DEFENSA EN PROFUNDIDAD: idempotente (add_table_if_missing / add_index_if_missing).
-- Ejecutar en esquema GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;

    PROCEDURE add_table_if_missing(
        p_table_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO v_exists
          FROM ALL_TABLES
         WHERE OWNER      = 'GESTIONRRHH'
           AND TABLE_NAME = p_table_name;

        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl;
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' -> creada.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(
        p_index_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO v_exists
          FROM ALL_INDEXES
         WHERE OWNER      = 'GESTIONRRHH'
           AND INDEX_NAME = p_index_name;

        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl;
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' -> creado.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    -- ==================================================================
    -- 1) INDECI_ASISTENCIA_CABECERA — una fila por empleado + período
    -- ==================================================================
    add_table_if_missing(
        'INDECI_ASISTENCIA_CABECERA',
        'CREATE TABLE GESTIONRRHH.INDECI_ASISTENCIA_CABECERA ('
        ||   'ID                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        ||   'EMPLEADO_ID         NUMBER NOT NULL,'
        ||   'PERIODO             VARCHAR2(7 CHAR) NOT NULL,'
        ||   'REMUNERACION_BASE   NUMBER(12,2),'
        ||   'DIAS_LABORADOS      NUMBER(3)  DEFAULT 0 NOT NULL,'
        ||   'DIAS_FALTA          NUMBER(3)  DEFAULT 0 NOT NULL,'
        ||   'TOTAL_MIN_TARDANZA  NUMBER(6)  DEFAULT 0 NOT NULL,'
        ||   'DESCUENTO_TARDANZA  NUMBER(12,2) DEFAULT 0 NOT NULL,'
        ||   'DESCUENTO_FALTA     NUMBER(12,2) DEFAULT 0 NOT NULL,'
        ||   'ESTADO              VARCHAR2(10 CHAR) DEFAULT ''BORRADOR'' NOT NULL,'
        ||   'OBSERVACION         VARCHAR2(500 CHAR),'
        ||   'ACTIVO              NUMBER(1) DEFAULT 1 NOT NULL,'
        ||   'CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'CONSTRAINT INDECI_ASIST_CAB_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_ASIST_CAB_EMP_FK FOREIGN KEY (EMPLEADO_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_EMPLEADO (ID),'
        ||   'CONSTRAINT INDECI_ASIST_CAB_ESTADO_CK '
        ||     'CHECK (ESTADO IN (''BORRADOR'', ''VALIDADA'')),'
        ||   'CONSTRAINT INDECI_ASIST_CAB_UK UNIQUE (EMPLEADO_ID, PERIODO)'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_ASIST_CAB_PERIODO',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_ASIST_CAB_PERIODO '
        || 'ON GESTIONRRHH.INDECI_ASISTENCIA_CABECERA (PERIODO, ACTIVO)'
    );

    -- ==================================================================
    -- 2) INDECI_ASISTENCIA_DETALLE — una fila por día del período
    -- ==================================================================
    add_table_if_missing(
        'INDECI_ASISTENCIA_DETALLE',
        'CREATE TABLE GESTIONRRHH.INDECI_ASISTENCIA_DETALLE ('
        ||   'ID                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        ||   'CABECERA_ID        NUMBER NOT NULL,'
        ||   'DIA                DATE   NOT NULL,'
        ||   'TIPO_DIA           VARCHAR2(15 CHAR) NOT NULL,'
        ||   'MINUTOS_TARDANZA   NUMBER(4) DEFAULT 0 NOT NULL,'
        ||   'OBSERVACION        VARCHAR2(200 CHAR),'
        ||   'CONSTRAINT INDECI_ASIST_DET_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_ASIST_DET_CAB_FK FOREIGN KEY (CABECERA_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_ASISTENCIA_CABECERA (ID),'
        ||   'CONSTRAINT INDECI_ASIST_DET_TIPO_CK '
        ||     'CHECK (TIPO_DIA IN '
        ||       '(''LABORAL'', ''FALTA'', ''TARDANZA'', ''LICENCIA'', ''VACACIONES'', ''DESCANSO'')),'
        ||   'CONSTRAINT INDECI_ASIST_DET_MIN_CK '
        ||     'CHECK (MINUTOS_TARDANZA >= 0),'
        ||   'CONSTRAINT INDECI_ASIST_DET_UK UNIQUE (CABECERA_ID, DIA)'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_ASIST_DET_CAB',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_ASIST_DET_CAB '
        || 'ON GESTIONRRHH.INDECI_ASISTENCIA_DETALLE (CABECERA_ID)'
    );

    -- ==================================================================
    -- COMMENTS (idempotente — Oracle sobrescribe)
    -- ==================================================================
    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_ASISTENCIA_CABECERA IS '
        || '''SPEC §12.2 PANTALLA-02 / M04 — Resumen de asistencia por empleado y período. '
        || 'UPSERT: una sola fila por (EMPLEADO_ID, PERIODO).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_ASISTENCIA_CABECERA.REMUNERACION_BASE IS '
        || '''Remuneración mensual usada como base del descuento (D.Leg. 276 Art. 24).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_ASISTENCIA_CABECERA.DESCUENTO_TARDANZA IS '
        || '''REGLA 276-02: ROUND((REMUNERACION_BASE/30/8/60) * TOTAL_MIN_TARDANZA, 2).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_ASISTENCIA_CABECERA.DESCUENTO_FALTA IS '
        || '''REGLA 276-02: ROUND((REMUNERACION_BASE/30) * DIAS_FALTA, 2).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_ASISTENCIA_CABECERA.ESTADO IS '
        || '''BORRADOR | VALIDADA — VALIDADA habilita el consumo por el motor M05 (PASO 7).''';

    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_ASISTENCIA_DETALLE IS '
        || '''SPEC §12.2 PANTALLA-02 / M04 — Día calendario del período con su tipo y tardanza.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_ASISTENCIA_DETALLE.TIPO_DIA IS '
        || '''LABORAL | FALTA | TARDANZA | LICENCIA | VACACIONES | DESCANSO (fin de semana).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_ASISTENCIA_DETALLE.MINUTOS_TARDANZA IS '
        || '''Minutos de tardanza del día (tras aplicar tolerancia parametrizada — D.Leg. 276 Art. 24).''';

    DBMS_OUTPUT.PUT_LINE('V010_17 finalizado.');

    -- Reporte final
    SELECT COUNT(*) INTO v_count
      FROM ALL_TABLES
     WHERE OWNER      = 'GESTIONRRHH'
       AND TABLE_NAME IN (
           'INDECI_ASISTENCIA_CABECERA',
           'INDECI_ASISTENCIA_DETALLE');
    DBMS_OUTPUT.PUT_LINE('Tablas M04 presentes ahora en GESTIONRRHH: ' || v_count || ' / 2.');
END;
/
