-- V010_110__empleado_concepto_descuento_judicial.sql
-- Agregar columnas para registrar el mandato judicial del Descuento por Pensión Alimentaria (05201)

ALTER TABLE GESTIONRRHH.INDECI_EMPLEADO_CONCEPTO 
ADD (
    JUDICIAL_TIPO_CALCULO VARCHAR2(20),
    JUDICIAL_BASE_CALCULO VARCHAR2(50),
    JUDICIAL_NRO_EXPEDIENTE VARCHAR2(100),
    JUDICIAL_NRO_OFICIO VARCHAR2(100),
    JUDICIAL_JUZGADO VARCHAR2(200),
    JUDICIAL_BENEF_TIPO_DOC VARCHAR2(20),
    JUDICIAL_BENEF_NRO_DOC VARCHAR2(20),
    JUDICIAL_BENEF_NOMBRE VARCHAR2(200),
    JUDICIAL_ENTIDAD_BANCARIA VARCHAR2(100),
    JUDICIAL_CUENTA_BANCARIA VARCHAR2(100)
);

COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_CONCEPTO.JUDICIAL_TIPO_CALCULO IS 'Tipo de calculo para judicial (MONTO_FIJO o PORCENTAJE)';
COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_CONCEPTO.JUDICIAL_BASE_CALCULO IS 'Base de calculo judicial (BRUTA_MENOS_LEY o TOTAL_BRUTA)';
COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_CONCEPTO.JUDICIAL_NRO_EXPEDIENTE IS 'Numero de expediente judicial';
COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_CONCEPTO.JUDICIAL_NRO_OFICIO IS 'Numero de oficio del mandato judicial';
COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_CONCEPTO.JUDICIAL_JUZGADO IS 'Juzgado emisor del mandato';
COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_CONCEPTO.JUDICIAL_BENEF_TIPO_DOC IS 'Tipo de documento del beneficiario (DNI, CE)';
COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_CONCEPTO.JUDICIAL_BENEF_NRO_DOC IS 'Numero de documento del beneficiario';
COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_CONCEPTO.JUDICIAL_BENEF_NOMBRE IS 'Nombre completo del beneficiario de la pension alimentaria';
COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_CONCEPTO.JUDICIAL_ENTIDAD_BANCARIA IS 'Entidad bancaria destino';
COMMENT ON COLUMN GESTIONRRHH.INDECI_EMPLEADO_CONCEPTO.JUDICIAL_CUENTA_BANCARIA IS 'Numero de cuenta bancaria o CCI del beneficiario';
