-- ============================================================================
-- V010_89 subsidio_seed_reglas_v1 (P0-F1)
-- Bundle regla vigente 2026 + fórmulas + validaciones + mapeo conceptos PLAME.
-- ============================================================================
SET SERVEROUTPUT ON;
SET DEFINE OFF;

MERGE INTO INDECI_SUBSIDIO_REGLA_VIGENCIA d
USING (
    SELECT 'SUBSIDIO_CAS_2026' AS CODIGO, '2026.1' AS VERSION,
           DATE '2026-01-01' AS FECHA_VIG_INI, DATE '2026-12-31' AS FECHA_VIG_FIN,
           'VIGENTE' AS ESTADO,
           'Bundle inicial subsidios CAS — referencia Excel LD mayo 2026' AS DESCRIPCION
      FROM DUAL
) s ON (d.CODIGO = s.CODIGO AND d.VERSION = s.VERSION)
WHEN NOT MATCHED THEN
    INSERT (CODIGO, VERSION, FECHA_VIG_INI, FECHA_VIG_FIN, ESTADO, DESCRIPCION)
    VALUES (s.CODIGO, s.VERSION, s.FECHA_VIG_INI, s.FECHA_VIG_FIN, s.ESTADO, s.DESCRIPCION);

DECLARE
    v_regla_id NUMBER;
BEGIN
    SELECT ID INTO v_regla_id FROM INDECI_SUBSIDIO_REGLA_VIGENCIA
     WHERE CODIGO = 'SUBSIDIO_CAS_2026' AND VERSION = '2026.1';

    MERGE INTO INDECI_SUBSIDIO_REGLA_FORMULA d
    USING (
        SELECT v_regla_id AS REGLA_VIGENCIA_ID, 'SUBSIDIO_DIARIO_ESSALUD' AS CODIGO_FORMULA,
               '{"op":"DIVIDE","args":[{"op":"SUM_TOP","months":12,"field":"baseComputable","cap":"TOPE_MENSUAL"},{"ref":"DIVISOR_PROMEDIO"}],"round":{"mode":"HALF_UP","scale":2}}' AS EXPRESION_JSON,
               'Subsidio diario EsSalud' AS DESCRIPCION FROM DUAL
    ) s ON (d.REGLA_VIGENCIA_ID = s.REGLA_VIGENCIA_ID AND d.CODIGO_FORMULA = s.CODIGO_FORMULA)
    WHEN NOT MATCHED THEN
        INSERT (REGLA_VIGENCIA_ID, CODIGO_FORMULA, EXPRESION_JSON, DESCRIPCION, ACTIVO)
        VALUES (s.REGLA_VIGENCIA_ID, s.CODIGO_FORMULA, s.EXPRESION_JSON, s.DESCRIPCION, 1);

    MERGE INTO INDECI_SUBSIDIO_REGLA_VALIDACION d
    USING (
        SELECT v_regla_id, 'SUB_V001', NULL, 'BLOQUEO', 'Los tramos mensuales se superponen. Ajuste fechas antes de calcular.' FROM DUAL UNION ALL
        SELECT v_regla_id, 'SUB_V003', NULL, 'BLOQUEO', 'No puede aplicar subsidio: el periodo de planilla está cerrado.' FROM DUAL UNION ALL
        SELECT v_regla_id, 'SUB_V013', NULL, 'INFORMATIVA', 'Está viendo un cálculo de simulación; no afecta planilla oficial.' FROM DUAL
    ) s ON (d.REGLA_VIGENCIA_ID = s.REGLA_VIGENCIA_ID AND d.CODIGO = s.CODIGO)
    WHEN NOT MATCHED THEN
        INSERT (REGLA_VIGENCIA_ID, CODIGO, EXPRESION_JSON, SEVERIDAD, MENSAJE_USUARIO, ACTIVO)
        VALUES (s.REGLA_VIGENCIA_ID, s.CODIGO, s.EXPRESION_JSON, s.SEVERIDAD, s.MENSAJE_USUARIO, 1);

    MERGE INTO INDECI_SUBSIDIO_REGLA_CONCEPTO d
    USING (
        SELECT v_regla_id, 'MATERNIDAD', c.ID, '0915', 'SUBSIDIO_100'
          FROM INDECI_CONCEPTO_PLANILLA c WHERE c.CODIGO = 'SUBSIDIO_MATERNIDAD' AND c.ACTIVO = 1
        UNION ALL
        SELECT v_regla_id, 'ENFERMEDAD', c.ID, '0916', 'SUBSIDIO_100'
          FROM INDECI_CONCEPTO_PLANILLA c WHERE c.CODIGO = 'SUBSIDIO_ENFERMEDAD' AND c.ACTIVO = 1
        UNION ALL
        SELECT v_regla_id, 'DIFERENCIAL', c.ID, '2073', 'DIFERENCIAL_2073'
          FROM INDECI_CONCEPTO_PLANILLA c WHERE c.CODIGO = 'SUBSIDIO_DIF_CAS' AND c.ACTIVO = 1
    ) s ON (d.REGLA_VIGENCIA_ID = s.REGLA_VIGENCIA_ID AND d.TIPO_SUBSIDIO = s.TIPO_SUBSIDIO AND d.TIPO_IMPUTACION = s.TIPO_IMPUTACION)
    WHEN NOT MATCHED THEN
        INSERT (REGLA_VIGENCIA_ID, TIPO_SUBSIDIO, CONCEPTO_PLANILLA_ID, CODIGO_PLAME, TIPO_IMPUTACION, ACTIVO)
        VALUES (s.REGLA_VIGENCIA_ID, s.TIPO_SUBSIDIO, s.CONCEPTO_PLANILLA_ID, s.CODIGO_PLAME, s.TIPO_IMPUTACION, 1);
END;
/

COMMIT;
DBMS_OUTPUT.PUT_LINE('V010_89 reglas subsidio v1 sincronizadas.');
/
