-- V010_109__seed_bancom_cuota_sindical.sql
-- Adición de conceptos voluntarios: Bancom (SISPER-736) y Cuota Sindical (SISPER-737)

MERGE INTO GESTIONRRHH.INDECI_CONCEPTO_PLANILLA d
USING (
    SELECT '05313' AS CODIGO_MEF, '736' AS CODIGO_SISPER, 'Bancom' AS NOMBRE, 'DESCUENTO' AS TIPO_CONCEPTO, 'N' AS AFECTO_IR_5TA, 'N' AS AFECTO_APORTE_PENS, 'N' AS AFECTO_ESSALUD, 'N' AS ES_MUC, 'N' AS ES_CUC, 'TODOS' AS REGIMEN_APLICABLE FROM DUAL UNION ALL
    SELECT '05314', '737', 'Cuota Sindical', 'DESCUENTO', 'N', 'N', 'N', 'N', 'N', 'TODOS' FROM DUAL
) s
ON (d.CODIGO_MEF = s.CODIGO_MEF)
WHEN NOT MATCHED THEN INSERT (
    CODIGO, CODIGO_MEF, CODIGO_SISPER, NOMBRE, TIPO,
    TIPO_CONCEPTO, AFECTO_IR_5TA, AFECTO_APORTE_PENS, AFECTO_ESSALUD,
    ES_MUC, ES_CUC, REGIMEN_APLICABLE,
    ACTIVO, CREATED_AT, FECHA_VIG_INI
) VALUES (
    s.CODIGO_MEF, s.CODIGO_MEF, s.CODIGO_SISPER, s.NOMBRE,
    'DESCUENTO',
    s.TIPO_CONCEPTO, s.AFECTO_IR_5TA, s.AFECTO_APORTE_PENS, s.AFECTO_ESSALUD,
    s.ES_MUC, s.ES_CUC, s.REGIMEN_APLICABLE,
    1, CURRENT_TIMESTAMP, DATE '2026-01-01'
);

COMMIT;
