-- ============================================================================
-- M04 / V010_82 — Configuración de jornada y tolerancias por régimen laboral
--
-- OBJETIVO: una configuración de jornada por régimen (INDECI_REGIMEN_LABORAL),
--   para calcular tardanzas (ingreso y regreso de almuerzo) y el descuento legal
--   (D.Leg. 276 Art. 24 / LEY-04): el divisor de jornada y las tolerancias salen
--   de aquí. El monto del descuento sigue siendo proporcional a la remuneración.
--
-- DECISIONES: 1 config por régimen (UK REGIMEN_LABORAL_ID); naming INDECI_*;
--   idempotente; TABLESPACE ancla de INDECI_EMPLEADO.
--
-- Ejecutar en esquema GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;
    v_ts    VARCHAR2(30);

    PROCEDURE add_table_if_missing(p_table_name VARCHAR2, p_create_ddl VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM ALL_TABLES
         WHERE OWNER = 'GESTIONRRHH' AND TABLE_NAME = p_table_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' -> creada en TBS ' || v_ts || '.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(p_index_name VARCHAR2, p_create_ddl VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM ALL_INDEXES
         WHERE OWNER = 'GESTIONRRHH' AND INDEX_NAME = p_index_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' -> creado en TBS ' || v_ts || '.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    SELECT TABLESPACE_NAME INTO v_ts FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_EMPLEADO';
    DBMS_OUTPUT.PUT_LINE('Tablespace ancla (INDECI_EMPLEADO): ' || v_ts);

    add_table_if_missing(
        'INDECI_JORNADA_REGIMEN',
        'CREATE TABLE GESTIONRRHH.INDECI_JORNADA_REGIMEN ('
        ||   'ID                       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        ||   'REGIMEN_LABORAL_ID       NUMBER NOT NULL,'
        ||   'HORA_INGRESO             VARCHAR2(5 CHAR),'
        ||   'HORA_SALIDA              VARCHAR2(5 CHAR),'
        ||   'REFRIGERIO_INICIO        VARCHAR2(5 CHAR),'
        ||   'REFRIGERIO_FIN           VARCHAR2(5 CHAR),'
        ||   'TOLERANCIA_INGRESO_MIN   NUMBER(4)   DEFAULT 0 NOT NULL,'
        ||   'TOLERANCIA_ALMUERZO_MIN  NUMBER(4)   DEFAULT 0 NOT NULL,'
        ||   'JORNADA_HORAS            NUMBER(4,2) DEFAULT 8 NOT NULL,'
        ||   'ACTIVO                   NUMBER(1)   DEFAULT 1 NOT NULL,'
        ||   'CREATED_AT               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'UPDATED_AT               TIMESTAMP,'
        ||   'CONSTRAINT INDECI_JORNADA_REG_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_JORNADA_REG_FK FOREIGN KEY (REGIMEN_LABORAL_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_REGIMEN_LABORAL (ID),'
        ||   'CONSTRAINT INDECI_JORNADA_REG_UK UNIQUE (REGIMEN_LABORAL_ID),'
        ||   'CONSTRAINT INDECI_JORNADA_REG_TOL_CK '
        ||     'CHECK (TOLERANCIA_INGRESO_MIN >= 0 AND TOLERANCIA_ALMUERZO_MIN >= 0),'
        ||   'CONSTRAINT INDECI_JORNADA_REG_HORAS_CK CHECK (JORNADA_HORAS > 0)'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_JORNADA_REG_REGIMEN',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_JORNADA_REG_REGIMEN '
        || 'ON GESTIONRRHH.INDECI_JORNADA_REGIMEN (REGIMEN_LABORAL_ID, ACTIVO)'
    );

    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_JORNADA_REGIMEN IS '
        || '''M04 - Jornada y tolerancias por regimen laboral (calculo de tardanzas y descuento D.Leg. 276).''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_JORNADA_REGIMEN.TOLERANCIA_INGRESO_MIN IS '
        || '''Minutos de gracia tras la hora de ingreso antes de contar tardanza.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_JORNADA_REGIMEN.TOLERANCIA_ALMUERZO_MIN IS '
        || '''Minutos de gracia tras el fin de refrigerio antes de contar tardanza de regreso.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_JORNADA_REGIMEN.JORNADA_HORAS IS '
        || '''Horas de jornada: divisor de la formula de descuento (remun/30/jornada/60).''';

    DBMS_OUTPUT.PUT_LINE('V010_82 finalizado.');
    SELECT COUNT(*) INTO v_count FROM ALL_TABLES
     WHERE OWNER = 'GESTIONRRHH' AND TABLE_NAME = 'INDECI_JORNADA_REGIMEN';
    DBMS_OUTPUT.PUT_LINE('Tabla INDECI_JORNADA_REGIMEN: ' || v_count || ' / 1.');
END;
/
