-- ============================================================================
-- Spec 012 / V010_22 — Certificación presupuestal por meta (Etapa 3 · C1 · P-05)
--
-- Soporta el SEMÁFORO PRESUPUESTAL de la pantalla de aprobación del período:
--   compara, por meta presupuestal, el monto CERTIFICADO (techo) contra el
--   monto COMPROMETIDO (suma de netos de la planilla del período).
--
--   INDECI_META_PRESUPUESTAL — una fila por (PERIODO_ID, META):
--     MONTO_CERTIFICADO  → techo de la certificación presupuestal física.
--                          Lo ingresa Tesorería/Contabilidad; NO se calcula.
--     El monto COMPROMETIDO no se almacena: se deriva en el servicio sumando
--     INDECI_MOVIMIENTO_PLANILLA.NETO_PAGAR de los empleados de esa meta.
--
-- DECISIONES DE DISEÑO (alineadas con V010_10 / V010_19):
--   - Naming INDECI_* ; PK IDENTITY — coherencia local.
--   - UK (PERIODO_ID, META) — una certificación por meta y período.
--   - CENTRO_COSTO / FUENTE_FINANC se copian de INDECI_EMPLEADO_PLANILLA para
--     mostrarlos aunque la meta aún no tenga empleados cargados.
--   - Sin ON DELETE CASCADE: baja lógica (ACTIVO).
--
-- DEFENSA EN PROFUNDIDAD: idempotente (add_table_if_missing / add_index_if_missing).
-- Ejecutar en esquema GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;

    PROCEDURE add_table_if_missing(
        p_table_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM ALL_TABLES
         WHERE OWNER = 'GESTIONRRHH' AND TABLE_NAME = p_table_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl;
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' -> creada.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table_name || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(
        p_index_name VARCHAR2,
        p_create_ddl VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM ALL_INDEXES
         WHERE OWNER = 'GESTIONRRHH' AND INDEX_NAME = p_index_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_create_ddl;
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' -> creado.');
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_index_name || ' ya existe. Sin cambios.');
        END IF;
    END;
BEGIN
    add_table_if_missing(
        'INDECI_META_PRESUPUESTAL',
        'CREATE TABLE GESTIONRRHH.INDECI_META_PRESUPUESTAL ('
        ||   'ID                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        ||   'PERIODO_ID         NUMBER NOT NULL,'
        ||   'META               VARCHAR2(20 CHAR) NOT NULL,'
        ||   'CENTRO_COSTO       VARCHAR2(60 CHAR),'
        ||   'FUENTE_FINANC      VARCHAR2(20 CHAR),'
        ||   'MONTO_CERTIFICADO  NUMBER(14,2) DEFAULT 0 NOT NULL,'
        ||   'ACTIVO             NUMBER(1) DEFAULT 1 NOT NULL,'
        ||   'CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        ||   'UPDATED_AT         TIMESTAMP,'
        ||   'CONSTRAINT INDECI_META_PRESUP_PK PRIMARY KEY (ID),'
        ||   'CONSTRAINT INDECI_META_PRESUP_PERIODO_FK FOREIGN KEY (PERIODO_ID) '
        ||     'REFERENCES GESTIONRRHH.INDECI_PERIODO_PLANILLA (ID),'
        ||   'CONSTRAINT INDECI_META_PRESUP_UK UNIQUE (PERIODO_ID, META),'
        ||   'CONSTRAINT INDECI_META_PRESUP_MONTO_CK '
        ||     'CHECK (MONTO_CERTIFICADO >= 0)'
        || ')'
    );

    add_index_if_missing(
        'IX_INDECI_META_PRESUP_PER',
        'CREATE INDEX GESTIONRRHH.IX_INDECI_META_PRESUP_PER '
        || 'ON GESTIONRRHH.INDECI_META_PRESUPUESTAL (PERIODO_ID)'
    );

    EXECUTE IMMEDIATE 'COMMENT ON TABLE GESTIONRRHH.INDECI_META_PRESUPUESTAL IS '
        || '''Spec 012 / C1 P-05 — Certificación presupuestal por meta y período. '
        || 'MONTO_CERTIFICADO es el techo ingresado por Tesoreria; el comprometido se deriva.''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN GESTIONRRHH.INDECI_META_PRESUPUESTAL.MONTO_CERTIFICADO IS '
        || '''Techo de la certificacion presupuestal fisica (Ley 28411 / LEY-05). No se calcula.''';

    DBMS_OUTPUT.PUT_LINE('V010_22 finalizado.');

    SELECT COUNT(*) INTO v_count
      FROM ALL_TABLES
     WHERE OWNER = 'GESTIONRRHH'
       AND TABLE_NAME = 'INDECI_META_PRESUPUESTAL';
    DBMS_OUTPUT.PUT_LINE('INDECI_META_PRESUPUESTAL presente: ' || v_count || ' / 1.');
END;
/
