BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_PLANILLA_LOTE ADD CONCEPTO_PLANILLA VARCHAR2(20)';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1430 THEN
         RAISE;
      END IF;
END;
/
