DECLARE
    v_ts VARCHAR2(30);
    v_ts_exists NUMBER;
    v_ts_clause VARCHAR2(100) := '';
    v_count NUMBER;
BEGIN
    -- 0) Resolver un TABLESPACE válido (evita ORA-00959 cuando el default
    --    del esquema, TBS_RRHH, no existe). Ancla: INDECI_EMPLEADO.
    BEGIN
        SELECT TABLESPACE_NAME INTO v_ts
          FROM USER_TABLES
         WHERE TABLE_NAME = 'INDECI_EMPLEADO';
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_ts := NULL;
    END;

    IF v_ts IS NOT NULL THEN
        SELECT COUNT(*) INTO v_ts_exists
          FROM USER_TABLESPACES
         WHERE TABLESPACE_NAME = v_ts;
        IF v_ts_exists = 0 THEN
            v_ts := NULL;
        END IF;
    END IF;

    IF v_ts IS NULL THEN
        SELECT DEFAULT_TABLESPACE INTO v_ts
          FROM USER_USERS
         WHERE USERNAME = USER;
        SELECT COUNT(*) INTO v_ts_exists
          FROM USER_TABLESPACES
         WHERE TABLESPACE_NAME = v_ts;
        IF v_ts_exists = 0 THEN
            v_ts := NULL;
        END IF;
    END IF;

    IF v_ts IS NOT NULL THEN
        v_ts_clause := ' TABLESPACE ' || v_ts;
    END IF;

    -- 1. Crear tabla INDECI_MODALIDAD_CAS
    SELECT COUNT(*) INTO v_count FROM all_tables WHERE owner = 'GESTIONRRHH' AND table_name = 'INDECI_MODALIDAD_CAS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE GESTIONRRHH.INDECI_MODALIDAD_CAS (
            ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CODIGO VARCHAR2(20) NOT NULL,
            NOMBRE VARCHAR2(100) NOT NULL,
            ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL
        )' || v_ts_clause;
    END IF;

    -- 2. Agregar columna MODALIDAD_CAS_ID a INDECI_EMPLEADO_PLANILLA
    SELECT COUNT(*) INTO v_count FROM all_tab_columns WHERE owner = 'GESTIONRRHH' AND table_name = 'INDECI_EMPLEADO_PLANILLA' AND column_name = 'MODALIDAD_CAS_ID';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_EMPLEADO_PLANILLA ADD MODALIDAD_CAS_ID NUMBER(19,0)';
    END IF;
END;
/

-- Insertar catalogos base
MERGE INTO GESTIONRRHH.INDECI_MODALIDAD_CAS dst
USING (
    SELECT 'CAS_MOD_TRANS' AS CODIGO, 'Necesidad Transitoria' AS NOMBRE FROM DUAL UNION ALL
    SELECT 'CAS_MOD_SUPL' AS CODIGO, 'Suplencia' AS NOMBRE FROM DUAL UNION ALL
    SELECT 'CAS_MOD_CONF' AS CODIGO, 'Confianza' AS NOMBRE FROM DUAL
) src ON (dst.CODIGO = src.CODIGO)
WHEN NOT MATCHED THEN
    INSERT (CODIGO, NOMBRE, ACTIVO)
    VALUES (src.CODIGO, src.NOMBRE, 1);


