-- ==============================================================================
-- HU-02: Creación de Maestro de Lotes de Planilla
-- Agrega entidad fuerte para gestionar el Master-Detail de las planillas.
-- ==============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_ts VARCHAR2(30);
    v_ts_exists NUMBER;
    v_ts_clause VARCHAR2(100) := '';
BEGIN
    -- 0) Resolver un TABLESPACE válido (evita ORA-00959 cuando el default
    --    del esquema, TBS_RRHH, no existe). Ancla: INDECI_EMPLEADO →
    --    default del usuario → sin cláusula. Mismo patrón que V010_97/100.
    BEGIN
        SELECT TABLESPACE_NAME INTO v_ts
          FROM USER_TABLES
         WHERE TABLE_NAME = 'INDECI_EMPLEADO';
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_ts := NULL;
    END;

    IF v_ts IS NOT NULL THEN
        SELECT COUNT(*) INTO v_ts_exists
          FROM USER_TABLESPACES
         WHERE TABLESPACE_NAME = v_ts;
        IF v_ts_exists = 0 THEN
            v_ts := NULL;
        END IF;
    END IF;

    IF v_ts IS NULL THEN
        SELECT DEFAULT_TABLESPACE INTO v_ts
          FROM USER_USERS
         WHERE USERNAME = USER;
        SELECT COUNT(*) INTO v_ts_exists
          FROM USER_TABLESPACES
         WHERE TABLESPACE_NAME = v_ts;
        IF v_ts_exists = 0 THEN
            v_ts := NULL;
        END IF;
    END IF;

    IF v_ts IS NOT NULL THEN
        v_ts_clause := ' TABLESPACE ' || v_ts;
    END IF;

    -- 1) Crear INDECI_PLANILLA_LOTE
    BEGIN
        EXECUTE IMMEDIATE 'CREATE TABLE GESTIONRRHH.INDECI_PLANILLA_LOTE (
            ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            PERIODO VARCHAR2(6) NOT NULL,
            REGIMEN_LABORAL_CODIGO VARCHAR2(20),
            TIPO_PLANILLA VARCHAR2(50) NOT NULL,
            CORRELATIVO NUMBER(4,0),
            ESTADO VARCHAR2(20) DEFAULT ''BORRADOR'' NOT NULL,
            CREADO_POR VARCHAR2(50) DEFAULT ''SYSTEM'' NOT NULL,
            CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
        )' || v_ts_clause;
        DBMS_OUTPUT.PUT_LINE('Tabla INDECI_PLANILLA_LOTE creada exitosamente.');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
END;
/

-- Añadir FK en la tabla transaccional (Permite NULL para no romper histórico)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_MOVIMIENTO_PLANILLA ADD LOTE_ID NUMBER(19,0)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_MOVIMIENTO_PLANILLA 
        ADD CONSTRAINT FK_MOV_PLANILLA_LOTE FOREIGN KEY (LOTE_ID) 
        REFERENCES GESTIONRRHH.INDECI_PLANILLA_LOTE(ID)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2275 THEN
            RAISE;
        END IF;
END;
/
