DECLARE
    v_count NUMBER;
BEGIN
    -- 1. EMPLEADO_PUESTO_ID
    SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name = 'INDECI_MOVIMIENTO_PLANILLA' AND column_name = 'EMPLEADO_PUESTO_ID';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_MOVIMIENTO_PLANILLA ADD (EMPLEADO_PUESTO_ID NUMBER(19,0) NULL)';
    END IF;

    -- 2. TIPO_PLANILLA
    SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name = 'INDECI_MOVIMIENTO_PLANILLA' AND column_name = 'TIPO_PLANILLA';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_MOVIMIENTO_PLANILLA ADD (TIPO_PLANILLA VARCHAR2(20) DEFAULT ''ORDINARIA'' NULL)';
    END IF;

    -- 3. FECHA_INICIO_PAGO
    SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name = 'INDECI_MOVIMIENTO_PLANILLA' AND column_name = 'FECHA_INICIO_PAGO';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_MOVIMIENTO_PLANILLA ADD (FECHA_INICIO_PAGO DATE NULL)';
    END IF;

    -- 4. FECHA_FIN_PAGO
    SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name = 'INDECI_MOVIMIENTO_PLANILLA' AND column_name = 'FECHA_FIN_PAGO';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_MOVIMIENTO_PLANILLA ADD (FECHA_FIN_PAGO DATE NULL)';
    END IF;
END;
/

