BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_VACACION_SALDO DROP CONSTRAINT UK_VACACION_SALDO_EMP_ANIO';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            RAISE;
        END IF;
END;
/
