-- Rollback V012_34 — elimina la columna MODALIDAD_TELETRABAJO. Idempotente.
SET SERVEROUTPUT ON
DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_cnt
    FROM all_tab_columns
    WHERE owner = 'GESTIONRRHH'
      AND table_name = 'INDECI_SOLICITUD_RRHH'
      AND column_name = 'MODALIDAD_TELETRABAJO';
    IF l_cnt > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_SOLICITUD_RRHH DROP COLUMN MODALIDAD_TELETRABAJO';
    END IF;
END;
/
