-- ============================================================================
-- V012_15 — Módulo Liquidación de CTS Trunca (feature 016): tabla + parámetros
--           + extensión del CHECK de snapshot para admitir REGLA='CTS'.
--
-- 1. Tabla INDECI_LIQUIDACION_CTS (una fila = liquidación de un vínculo/período).
-- 2. Extiende INDECI_CALC_SNAPSHOT_REGLA_CK (V010_61) para admitir 'CTS'
--    (si no, el snapshot del cálculo CTS fallaría con ORA-02290).
-- 3. Seeds de parámetros (REGLA-02, factores/divisor NO hardcodeados en Java):
--    CTS_FACTOR_ANUAL_276 / CTS_FACTOR_ANUAL_SERVIR (=1.0 → 100%; RR.HH. ajustable)
--    CTS_DIVISOR_DIAS (=360).
--
-- Naming INDECI_*; PK IDENTITY; TABLESPACE anclado a INDECI_EMPLEADO (evita
-- ORA-00959). Idempotente. Ejecutar en GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_ts        VARCHAR2(30);
    v_ck_exists NUMBER;

    PROCEDURE add_table_if_missing(p_table VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(p_idx VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_INDEXES WHERE INDEX_NAME = p_idx;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_idx || ' -> creado en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_idx || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE seed_param(p_codigo VARCHAR2, p_valor NUMBER, p_unidad VARCHAR2) IS
        v NUMBER;
    BEGIN
        FOR y IN 2020 .. 2030 LOOP
            SELECT COUNT(*) INTO v
              FROM GESTIONRRHH.INDECI_PARAMETRO_REMUNERATIVO
             WHERE CODIGO_PARAMETRO = p_codigo
               AND ANIO_FISCAL = y
               AND REGIMEN_LABORAL_ID IS NULL;
            IF v = 0 THEN
                INSERT INTO GESTIONRRHH.INDECI_PARAMETRO_REMUNERATIVO
                    (CODIGO_PARAMETRO, ANIO_FISCAL, REGIMEN_LABORAL_ID, VALOR_NUMERICO,
                     UNIDAD, FECHA_VIG_INI, FECHA_VIG_FIN, ACTIVO, CREATED_AT)
                VALUES
                    (p_codigo, y, NULL, p_valor, p_unidad,
                     TO_DATE(y || '-01-01','YYYY-MM-DD'), NULL, 1, SYSTIMESTAMP);
            END IF;
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('Parámetro ' || p_codigo || ' sembrado (2020-2030).');
    END;

BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    -- ── 1. Tabla de liquidaciones ───────────────────────────────────────────
    add_table_if_missing(
        'INDECI_LIQUIDACION_CTS',
        'CREATE TABLE INDECI_LIQUIDACION_CTS ('
        || 'ID                       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'EMPLEADO_ID              NUMBER NOT NULL,'
        || 'EMPLEADO_PLANILLA_ID     NUMBER NOT NULL,'
        || 'PERIODO                  VARCHAR2(7 CHAR) NOT NULL,'
        || 'REGIMEN_LABORAL_ID       NUMBER NOT NULL,'
        || 'REGIMEN_CODIGO           VARCHAR2(10 CHAR) NOT NULL,'
        || 'ESTRATEGIA               VARCHAR2(20 CHAR) NOT NULL,'
        || 'FECHA_INGRESO            DATE NOT NULL,'
        || 'FECHA_CESE               DATE NOT NULL,'
        || 'ANIOS                    NUMBER(4)  DEFAULT 0 NOT NULL,'
        || 'MESES                    NUMBER(2)  DEFAULT 0 NOT NULL,'
        || 'DIAS                     NUMBER(2)  DEFAULT 0 NOT NULL,'
        || 'DIAS_EFECTIVOS_FRACCION  NUMBER(5)  DEFAULT 0 NOT NULL,'
        || 'BASE_COMPUTABLE          NUMBER(14,2) NOT NULL,'
        || 'FACTOR_ANUAL             NUMBER(8,4)  NOT NULL,'
        || 'DIVISOR_DIAS             NUMBER(5)    NOT NULL,'
        || 'MONTO_ANIOS              NUMBER(14,2) DEFAULT 0 NOT NULL,'
        || 'MONTO_FRACCION           NUMBER(14,2) DEFAULT 0 NOT NULL,'
        || 'MONTO_TOTAL              NUMBER(14,2) DEFAULT 0 NOT NULL,'
        || 'ESTADO                   VARCHAR2(12 CHAR) DEFAULT ''PENDIENTE'' NOT NULL,'
        || 'SNAPSHOT_ID              NUMBER,'
        || 'NRO_CONSTANCIA           VARCHAR2(40 CHAR),'
        || 'OBSERVACION              VARCHAR2(400 CHAR),'
        || 'CREATED_BY               VARCHAR2(50 CHAR),'
        || 'CREATED_AT               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        || 'UPDATED_BY               VARCHAR2(50 CHAR),'
        || 'UPDATED_AT               TIMESTAMP,'
        || 'CONSTRAINT INDECI_LIQUIDACION_CTS_PK PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_LIQUIDACION_CTS_EMP_FK FOREIGN KEY (EMPLEADO_ID) '
        ||   'REFERENCES INDECI_EMPLEADO (ID),'
        || 'CONSTRAINT INDECI_LIQUIDACION_CTS_EMPPLA_FK FOREIGN KEY (EMPLEADO_PLANILLA_ID) '
        ||   'REFERENCES INDECI_EMPLEADO_PLANILLA (ID),'
        || 'CONSTRAINT INDECI_LIQUIDACION_CTS_UK UNIQUE (EMPLEADO_PLANILLA_ID, PERIODO),'
        || 'CONSTRAINT INDECI_LIQUIDACION_CTS_ESTADO_CK '
        ||   'CHECK (ESTADO IN (''PENDIENTE'', ''CALCULADO'', ''CERRADO'')),'
        || 'CONSTRAINT INDECI_LIQUIDACION_CTS_ESTRAT_CK '
        ||   'CHECK (ESTRATEGIA IN (''CTS276'', ''CTSSERVIR''))'
        || ')'
    );

    add_index_if_missing(
        'INDECI_LIQ_CTS_PERIODO_IDX',
        'CREATE INDEX INDECI_LIQ_CTS_PERIODO_IDX '
        || 'ON INDECI_LIQUIDACION_CTS (PERIODO, REGIMEN_LABORAL_ID)'
    );

    -- ── 2. Extender el CHECK de REGLA del snapshot para admitir 'CTS' ────────
    SELECT COUNT(*) INTO v_ck_exists
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'INDECI_CALCULO_SNAPSHOT'
       AND CONSTRAINT_NAME = 'INDECI_CALC_SNAPSHOT_REGLA_CK';
    IF v_ck_exists > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_CALCULO_SNAPSHOT '
            || 'DROP CONSTRAINT INDECI_CALC_SNAPSHOT_REGLA_CK';
    END IF;
    EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_CALCULO_SNAPSHOT ADD ('
        || 'CONSTRAINT INDECI_CALC_SNAPSHOT_REGLA_CK '
        || 'CHECK (REGLA IN ('
        || '''GENERAL'', ''IR4TA_CAS'', ''IR5TA'', ''SUBSIDIO'', ''ESSALUD'', ''CTS'')))';
    DBMS_OUTPUT.PUT_LINE('INDECI_CALC_SNAPSHOT_REGLA_CK -> recreado con CTS.');

    -- ── 3. Seeds de parámetros (REGLA-02) ───────────────────────────────────
    -- UNIDAD restringida por INDECI_PARAM_REM_UNIDAD_CK a {PEN,PCT,MIN,DIAS}:
    -- el factor por año se modela como 'PCT' (1.0 = 100%); el divisor como 'DIAS'.
    seed_param('CTS_FACTOR_ANUAL_276',    1.0, 'PCT');
    seed_param('CTS_FACTOR_ANUAL_SERVIR', 1.0, 'PCT');
    seed_param('CTS_DIVISOR_DIAS',        360, 'DIAS');

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('V012_15 finalizado correctamente.');
END;
/
