-- ============================================================================
-- V012_18 — Calendario laboral: FERIADOS y DESCANSOS semanales (M04 Asistencia)
--
-- Objetivo: dar al motor de asistencia la base para decidir qué día es
-- laborable y así calcular FALTAS correctamente (un día NO laborable —feriado
-- o descanso semanal— nunca es falta). Requerido por la carga de asistencia
-- (Reloj 1 y Reloj 2 / COEN): las faltas se generan por calendario.
--
-- 1. INDECI_FERIADO           — catálogo de feriados POR AÑO (2026 sembrado).
-- 2. INDECI_DESCANSO_SEMANAL  — días de descanso semanal (global o por régimen).
--
-- Naming INDECI_*; PK IDENTITY; TABLESPACE anclado a INDECI_EMPLEADO (evita
-- ORA-00959). Idempotente. Ejecutar en GESTIONRRHH / Oracle 19c+.
--
-- ┌────────────────────────────────────────────────────────────────────────┐
-- │ ⚠️  VALIDACIÓN RR.HH. OBLIGATORIA ANTES DE PRODUCCIÓN                    │
-- │ Los feriados afectan DESCUENTOS por falta (dinero). La lista 2026 debe   │
-- │ contrastarse con la publicación oficial (PCM / El Peruano). Los feriados │
-- │ "clásicos" son D.Leg. 713; los agregados por ley reciente (07-jun,       │
-- │ 23-jul, 06-ago, 09-dic) están marcados VERIFICAR: confirmar norma        │
-- │ vigente 2026 y desactivar (ACTIVO=0) o corregir lo que no aplique.       │
-- └────────────────────────────────────────────────────────────────────────┘
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_ts VARCHAR2(30);

    PROCEDURE add_table_if_missing(p_table VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(p_idx VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_INDEXES WHERE INDEX_NAME = p_idx;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_idx || ' -> creado en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_idx || ' ya existe. Sin cambios.');
        END IF;
    END;

    -- Inserta un feriado si no existe (idempotente por ANIO+FECHA).
    -- SQL DINÁMICO: las tablas se crean en este mismo bloque, así que el SQL estático
    -- no compilaría (ORA-00942). EXECUTE IMMEDIATE difiere la resolución a runtime.
    PROCEDURE seed_feriado(
        p_fecha        VARCHAR2,   -- 'YYYY-MM-DD'
        p_nombre       VARCHAR2,
        p_es_irrenunc  NUMBER,
        p_base_legal   VARCHAR2
    ) IS
        v      NUMBER;
        v_dt   DATE := TO_DATE(p_fecha, 'YYYY-MM-DD');
        v_anio NUMBER := EXTRACT(YEAR FROM TO_DATE(p_fecha, 'YYYY-MM-DD'));
    BEGIN
        EXECUTE IMMEDIATE
            'SELECT COUNT(*) FROM GESTIONRRHH.INDECI_FERIADO WHERE ANIO = :1 AND FECHA = :2'
            INTO v USING v_anio, v_dt;
        IF v = 0 THEN
            EXECUTE IMMEDIATE
                'INSERT INTO GESTIONRRHH.INDECI_FERIADO '
                || '(ANIO, FECHA, NOMBRE, TIPO, ES_IRRENUNCIABLE, BASE_LEGAL, ACTIVO, CREATED_AT) '
                || 'VALUES (:1, :2, :3, ''NACIONAL'', :4, :5, 1, SYSTIMESTAMP)'
                USING v_anio, v_dt, p_nombre, p_es_irrenunc, p_base_legal;
        END IF;
    END;

    -- Inserta un descanso semanal si no existe (REGIMEN NULL = aplica a todos).
    PROCEDURE seed_descanso(p_dia_iso NUMBER, p_nombre VARCHAR2) IS
        v NUMBER;
    BEGIN
        EXECUTE IMMEDIATE
            'SELECT COUNT(*) FROM GESTIONRRHH.INDECI_DESCANSO_SEMANAL '
            || 'WHERE DIA_ISO = :1 AND REGIMEN_LABORAL_ID IS NULL'
            INTO v USING p_dia_iso;
        IF v = 0 THEN
            EXECUTE IMMEDIATE
                'INSERT INTO GESTIONRRHH.INDECI_DESCANSO_SEMANAL '
                || '(REGIMEN_LABORAL_ID, DIA_ISO, DIA_NOMBRE, ACTIVO, CREATED_AT) '
                || 'VALUES (NULL, :1, :2, 1, SYSTIMESTAMP)'
                USING p_dia_iso, p_nombre;
        END IF;
    END;

BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    -- ── 1. Catálogo de feriados por año ─────────────────────────────────────
    add_table_if_missing(
        'INDECI_FERIADO',
        'CREATE TABLE INDECI_FERIADO ('
        || 'ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'ANIO              NUMBER(4)   NOT NULL,'
        || 'FECHA             DATE        NOT NULL,'
        || 'NOMBRE            VARCHAR2(120 CHAR) NOT NULL,'
        || 'TIPO              VARCHAR2(20 CHAR) DEFAULT ''NACIONAL'' NOT NULL,'
        || 'ES_IRRENUNCIABLE  NUMBER(1)   DEFAULT 1 NOT NULL,'
        || 'BASE_LEGAL        VARCHAR2(200 CHAR),'
        || 'ACTIVO            NUMBER(1)   DEFAULT 1 NOT NULL,'
        || 'CREATED_AT        TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,'
        || 'UPDATED_AT        TIMESTAMP,'
        || 'CONSTRAINT INDECI_FERIADO_PK PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_FERIADO_UK UNIQUE (ANIO, FECHA),'
        || 'CONSTRAINT INDECI_FERIADO_TIPO_CK '
        ||   'CHECK (TIPO IN (''NACIONAL'', ''REGIONAL'', ''NO_LABORABLE'')),'
        || 'CONSTRAINT INDECI_FERIADO_ACTIVO_CK CHECK (ACTIVO IN (0, 1))'
        || ')'
    );

    add_index_if_missing(
        'INDECI_FERIADO_ANIO_IDX',
        'CREATE INDEX INDECI_FERIADO_ANIO_IDX ON INDECI_FERIADO (ANIO, ACTIVO)'
    );

    -- ── 2. Descanso semanal (global o por régimen) ──────────────────────────
    -- DIA_ISO: 1=Lunes .. 7=Domingo (ISO-8601, independiente del NLS de Oracle).
    -- REGIMEN_LABORAL_ID NULL = descanso por defecto para todos los regímenes;
    -- una fila con régimen específico lo sobreescribe (p. ej. turnos que laboran
    -- sábado).
    add_table_if_missing(
        'INDECI_DESCANSO_SEMANAL',
        'CREATE TABLE INDECI_DESCANSO_SEMANAL ('
        || 'ID                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'REGIMEN_LABORAL_ID  NUMBER,'
        || 'DIA_ISO             NUMBER(1)   NOT NULL,'
        || 'DIA_NOMBRE          VARCHAR2(10 CHAR),'
        || 'ACTIVO              NUMBER(1)   DEFAULT 1 NOT NULL,'
        || 'CREATED_AT          TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,'
        || 'UPDATED_AT          TIMESTAMP,'
        || 'CONSTRAINT INDECI_DESCANSO_SEM_PK PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_DESCANSO_SEM_DIA_CK CHECK (DIA_ISO BETWEEN 1 AND 7),'
        || 'CONSTRAINT INDECI_DESCANSO_SEM_ACT_CK CHECK (ACTIVO IN (0, 1))'
        || ')'
    );

    add_index_if_missing(
        'INDECI_DESCANSO_SEM_REG_IDX',
        'CREATE INDEX INDECI_DESCANSO_SEM_REG_IDX '
        || 'ON INDECI_DESCANSO_SEMANAL (REGIMEN_LABORAL_ID, ACTIVO)'
    );

    -- ── 3. Seed FERIADOS NACIONALES 2026 ────────────────────────────────────
    -- Clásicos (D.Leg. 713). Irrenunciables salvo indicación.
    seed_feriado('2026-01-01', 'Año Nuevo',                          1, 'D.Leg. 713');
    seed_feriado('2026-04-02', 'Jueves Santo',                       0, 'D.Leg. 713');
    seed_feriado('2026-04-03', 'Viernes Santo',                      0, 'D.Leg. 713');
    seed_feriado('2026-05-01', 'Día del Trabajo',                    1, 'D.Leg. 713');
    seed_feriado('2026-06-07', 'Batalla de Arica y Día de la Bandera',1, 'Ley especial — VERIFICAR norma vigente 2026');
    seed_feriado('2026-06-29', 'San Pedro y San Pablo',              1, 'D.Leg. 713');
    seed_feriado('2026-07-23', 'Día de la Fuerza Aérea del Perú',    1, 'Ley especial — VERIFICAR norma vigente 2026');
    seed_feriado('2026-07-28', 'Fiestas Patrias',                    1, 'D.Leg. 713');
    seed_feriado('2026-07-29', 'Fiestas Patrias',                    1, 'D.Leg. 713');
    seed_feriado('2026-08-06', 'Batalla de Junín',                   1, 'Ley especial — VERIFICAR norma vigente 2026');
    seed_feriado('2026-08-30', 'Santa Rosa de Lima',                 1, 'D.Leg. 713');
    seed_feriado('2026-10-08', 'Combate de Angamos',                 1, 'D.Leg. 713');
    seed_feriado('2026-11-01', 'Día de Todos los Santos',            1, 'D.Leg. 713');
    seed_feriado('2026-12-08', 'Inmaculada Concepción',              1, 'D.Leg. 713');
    seed_feriado('2026-12-09', 'Batalla de Ayacucho',                1, 'Ley especial — VERIFICAR norma vigente 2026');
    seed_feriado('2026-12-25', 'Navidad',                            1, 'D.Leg. 713');
    DBMS_OUTPUT.PUT_LINE('Feriados 2026 sembrados (verificar los marcados por RR.HH.).');

    -- ── 4. Seed DESCANSO SEMANAL por defecto (sábado y domingo) ──────────────
    -- D.Leg. 713 — descanso semanal obligatorio (domingo). Régimen administrativo
    -- lun-vie => sábado también es no laborable por defecto. Ajustable por RR.HH.
    seed_descanso(6, 'SABADO');
    seed_descanso(7, 'DOMINGO');
    DBMS_OUTPUT.PUT_LINE('Descanso semanal por defecto sembrado (SAB, DOM).');

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('V012_18 finalizado correctamente.');
END;
/
