-- Rollback V012_25 — elimina el estado PENDIENTE_FIRMA si ninguna solicitud lo usa.
BEGIN
    DELETE FROM GESTIONRRHH.INDECI_ESTADO_SOLICITUD e
     WHERE e.CODIGO = 'PENDIENTE_FIRMA'
       AND NOT EXISTS (SELECT 1 FROM GESTIONRRHH.INDECI_SOLICITUD_RRHH s
                        WHERE s.ESTADO_SOLICITUD_ID = e.ID);
    COMMIT;
END;
/
