-- ROLLBACK V012_05 — Elimina la tabla de historial remunerativo.
SET SERVEROUTPUT ON;
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO_REMUNERACION_HIST';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE GESTIONRRHH.INDECI_EMPLEADO_REMUNERACION_HIST';
        DBMS_OUTPUT.PUT_LINE('INDECI_EMPLEADO_REMUNERACION_HIST -> eliminada.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('No existe. Sin cambios.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR rollback V012_05: ' || SQLERRM);
        RAISE;
END;
/
