-- ============================================================================
-- V012_27 — Papeleta de Teletrabajo diaria (Ley N° 31572 / SERVIR)
--
-- Nuevo TIPO de papeleta 'TELETRABAJO' sobre INDECI_SOLICITUD_RRHH, reutilizando
-- el flujo existente BORRADOR -> ENVIADO -> APROBADO_JEFE (firma jefe) ->
-- APROBADO_RRHH (recepción URH). NO se crean estados nuevos.
--
-- El servidor genera la papeleta al FINALIZAR su jornada y detalla las
-- actividades del día en INDECI_SOLICITUD_TELETRABAJO_DET (tabla hija,
-- patrón INDECI_SOLICITUD_VACACION_DET): una fila por actividad.
--
-- Naming INDECI_*; PK IDENTITY; TABLESPACE anclado a INDECI_SOLICITUD_RRHH.
-- Idempotente. Ejecutar en GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_ts VARCHAR2(30);

    PROCEDURE add_table_if_missing(p_table VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(p_idx VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_INDEXES WHERE INDEX_NAME = p_idx;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_idx || ' -> creado en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_idx || ' ya existe. Sin cambios.');
        END IF;
    END;

BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_SOLICITUD_RRHH';

    -- 1) Tabla hija de actividades del día -----------------------------------
    add_table_if_missing(
        'INDECI_SOLICITUD_TELETRABAJO_DET',
        'CREATE TABLE INDECI_SOLICITUD_TELETRABAJO_DET ('
        || 'ID                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'SOLICITUD_ID        NUMBER NOT NULL,'
        -- Orden de la actividad dentro del reporte del día.
        || 'NRO_ORDEN           NUMBER,'
        -- Actividad efectivamente realizada por el teletrabajador.
        || 'ACTIVIDAD           VARCHAR2(500 CHAR) NOT NULL,'
        -- Medio de verificación / entregable que sustenta la actividad.
        || 'MEDIO_VERIFICACION  VARCHAR2(300 CHAR),'
        -- Ruta/nombre de evidencia adjunta (opcional).
        || 'EVIDENCIA_ARCHIVO   VARCHAR2(500 CHAR),'
        || 'ACTIVO              NUMBER(1) DEFAULT 1 NOT NULL,'
        || 'CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        || 'CONSTRAINT INDECI_SOL_TT_DET_PK PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_SOL_TT_DET_SOL_FK FOREIGN KEY (SOLICITUD_ID) '
        ||   'REFERENCES INDECI_SOLICITUD_RRHH (ID),'
        || 'CONSTRAINT INDECI_SOL_TT_DET_ACT_CK CHECK (ACTIVO IN (0, 1))'
        || ')'
    );

    add_index_if_missing(
        'INDECI_SOL_TT_DET_SOL_IDX',
        'CREATE INDEX INDECI_SOL_TT_DET_SOL_IDX '
        || 'ON INDECI_SOLICITUD_TELETRABAJO_DET (SOLICITUD_ID, ACTIVO)'
    );

    -- 2) Tipo de papeleta 'TELETRABAJO' (idempotente por CODIGO) --------------
    DECLARE
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM INDECI_TIPO_SOLICITUD_RRHH
         WHERE CODIGO = 'TELETRABAJO';

        IF v_exists = 0 THEN
            INSERT INTO INDECI_TIPO_SOLICITUD_RRHH (
                NOMBRE, CODIGO, ACTIVO,
                MOSTRAR_HORAS, REQUIERE_SUSTENTO, REQUIERE_LUGAR,
                REQUIERE_OBSERVACION, MOSTRAR_LACTANCIA, MOSTRAR_DESCANSO_MEDICO,
                MOSTRAR_LICENCIA, MOSTRAR_VACACION, MOSTRAR_COMPENSACION
            ) VALUES (
                -- MOSTRAR_HORAS=0 y REQUIERE_OBSERVACION=0: el reporte de teletrabajo
                -- usa su propio diálogo (fecha + actividades), NO horas ni observación
                -- libre; con 1 el pipeline validarSolicitud rechazaría el registro.
                'Reporte de Teletrabajo', 'TELETRABAJO', 1,
                0, 0, 0,
                0, 0, 0,
                0, 0, 0
            );
            DBMS_OUTPUT.PUT_LINE('Tipo TELETRABAJO -> creado.');
        ELSE
            DBMS_OUTPUT.PUT_LINE('Tipo TELETRABAJO ya existe. Sin cambios.');
        END IF;
    END;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('V012_27 finalizado correctamente.');
END;
/
