-- Rollback V012_49 — vuelve JUSTIFICA_ASISTENCIA a 0 para código 011.
SET SERVEROUTPUT ON
BEGIN
    UPDATE GESTIONRRHH.INDECI_TIPO_SOLICITUD_RRHH
       SET JUSTIFICA_ASISTENCIA = 0
     WHERE CODIGO = '011';
    DBMS_OUTPUT.PUT_LINE('JUSTIFICA_ASISTENCIA revertido a 0 para código 011 (' || SQL%ROWCOUNT || ' fila[s]).');
    COMMIT;
END;
/
