-- Rollback V012_48 — elimina DIAS_CALENDARIO de ambas tablas.
SET SERVEROUTPUT ON;
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_SOLICITUD_VACACION_DET DROP COLUMN DIAS_CALENDARIO';
    DBMS_OUTPUT.PUT_LINE('INDECI_SOLICITUD_VACACION_DET.DIAS_CALENDARIO eliminada.');
    EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_VACACIONES DROP COLUMN DIAS_CALENDARIO';
    DBMS_OUTPUT.PUT_LINE('INDECI_VACACIONES.DIAS_CALENDARIO eliminada.');
END;
/
