-- ============================================================================
-- V012_37 ROLLBACK — Import de Vinculación: catálogos y campos
--
-- Revierte SOLO lo agregado por V012_37. No borra datos operativos.
-- Ejecutar en orden inverso. Idempotente.
-- ============================================================================
SET SERVEROUTPUT ON;

-- 7) NUMERO_CONTRATO: no se reduce (reducir podría truncar datos ya migrados).
--    Se deja en VARCHAR2(60) intencionalmente.

-- 6) INDECI_EMPLEADO_PLANILLA — quitar campos nuevos
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM ALL_TAB_COLUMNS
     WHERE OWNER='GESTIONRRHH' AND TABLE_NAME='INDECI_EMPLEADO_PLANILLA'
       AND COLUMN_NAME='BASE_LEGAL_VINCULO';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_EMPLEADO_PLANILLA DROP COLUMN BASE_LEGAL_VINCULO';
    END IF;

    SELECT COUNT(*) INTO v_count FROM ALL_TAB_COLUMNS
     WHERE OWNER='GESTIONRRHH' AND TABLE_NAME='INDECI_EMPLEADO_PLANILLA'
       AND COLUMN_NAME='NRO_CONVOCATORIA';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_EMPLEADO_PLANILLA DROP COLUMN NRO_CONVOCATORIA';
    END IF;
END;
/

-- 5) INDECI_EMPLEADO — quitar CLASE_PERSONAL (+ su CHECK)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM ALL_CONSTRAINTS
     WHERE OWNER='GESTIONRRHH' AND CONSTRAINT_NAME='INDECI_EMPLEADO_CLASE_PERS_CK';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_EMPLEADO DROP CONSTRAINT INDECI_EMPLEADO_CLASE_PERS_CK';
    END IF;

    SELECT COUNT(*) INTO v_count FROM ALL_TAB_COLUMNS
     WHERE OWNER='GESTIONRRHH' AND TABLE_NAME='INDECI_EMPLEADO'
       AND COLUMN_NAME='CLASE_PERSONAL';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_EMPLEADO DROP COLUMN CLASE_PERSONAL';
    END IF;
END;
/

-- 4) INDECI_ESTADO_CIVIL — quitar solo si no están referenciados
DELETE FROM GESTIONRRHH.INDECI_ESTADO_CIVIL ec
 WHERE ec.CODIGO IN ('SOLTERO','CASADO','CONVIVIENTE','DIVORCIADO','VIUDO')
   AND NOT EXISTS (SELECT 1 FROM GESTIONRRHH.INDECI_PERSONA p WHERE p.ESTADO_CIVIL_ID = ec.ID);

-- 3) BANKS — quitar solo si no están referenciados
DELETE FROM GESTIONRRHH.BANKS b
 WHERE UPPER(TRIM(b.NAME)) IN ('BANCO DE LA NACION','BANCO DE CREDITO DEL PERU','BBVA PERU',
                               'INTERBANK','SCOTIABANK','BANBIF','BANCO PICHINCHA')
   AND NOT EXISTS (SELECT 1 FROM GESTIONRRHH.INDECI_EMPLEADO_BANCO eb WHERE eb.BANK_ID = b.ID);

-- 2) INDECI_TIPO_CONTRATO — quitar CONFIANZA si no está en uso
DELETE FROM GESTIONRRHH.INDECI_TIPO_CONTRATO tc
 WHERE tc.CODIGO = 'CONFIANZA'
   AND NOT EXISTS (SELECT 1 FROM GESTIONRRHH.INDECI_EMPLEADO_PLANILLA ep WHERE ep.TIPO_CONTRATO_ID = tc.ID);

-- 1) INDECI_REGIMEN_PENSIONARIO — quitar CPMP si no está en uso
DELETE FROM GESTIONRRHH.INDECI_REGIMEN_PENSIONARIO rp
 WHERE rp.CODIGO = 'CPMP'
   AND NOT EXISTS (SELECT 1 FROM GESTIONRRHH.INDECI_EMPLEADO_PENSION epn WHERE epn.REGIMEN_PENSIONARIO_ID = rp.ID);

COMMIT;
