-- ============================================================================
-- V012_15 ROLLBACK — Elimina la tabla CTS, sus parámetros y revierte el CK
-- del snapshot al estado de V010_61 (sin 'CTS').
-- Idempotente. GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v NUMBER;
BEGIN
    SELECT COUNT(*) INTO v FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_LIQUIDACION_CTS';
    IF v > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE GESTIONRRHH.INDECI_LIQUIDACION_CTS CASCADE CONSTRAINTS';
        DBMS_OUTPUT.PUT_LINE('INDECI_LIQUIDACION_CTS -> eliminada.');
    END IF;

    DELETE FROM GESTIONRRHH.INDECI_PARAMETRO_REMUNERATIVO
     WHERE CODIGO_PARAMETRO IN ('CTS_FACTOR_ANUAL_276', 'CTS_FACTOR_ANUAL_SERVIR', 'CTS_DIVISOR_DIAS');

    SELECT COUNT(*) INTO v FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'INDECI_CALCULO_SNAPSHOT'
       AND CONSTRAINT_NAME = 'INDECI_CALC_SNAPSHOT_REGLA_CK';
    IF v > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_CALCULO_SNAPSHOT '
            || 'DROP CONSTRAINT INDECI_CALC_SNAPSHOT_REGLA_CK';
        EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_CALCULO_SNAPSHOT ADD ('
            || 'CONSTRAINT INDECI_CALC_SNAPSHOT_REGLA_CK '
            || 'CHECK (REGLA IN (''GENERAL'', ''IR4TA_CAS'', ''IR5TA'', ''SUBSIDIO'', ''ESSALUD'')))';
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('V012_15 ROLLBACK finalizado.');
END;
/
