-- ============================================================================
-- V012_19 — Alias de identidad del marcador (M04 Asistencia · Reloj 2 / COEN)
--
-- El reporte COEN NO trae DNI, solo "APELLIDOS, NOMBRES". Esta tabla es la
-- "libreta" que asocia ese nombre del marcador con el empleado del sistema.
-- Se llena de forma INDIVIDUAL desde la pantalla de mapeo (SPEC D1); una vez
-- mapeado, los próximos meses auto-emparejan. Sin DNI y sin alias → el sistema
-- NO adivina (protege descuentos): la fila queda 'sin mapeo' o 'NO REGISTRADO'.
--
-- Naming INDECI_*; PK IDENTITY; TABLESPACE anclado a INDECI_EMPLEADO.
-- Idempotente. Ejecutar en GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_ts VARCHAR2(30);

    PROCEDURE add_table_if_missing(p_table VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(p_idx VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_INDEXES WHERE INDEX_NAME = p_idx;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_idx || ' -> creado en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_idx || ' ya existe. Sin cambios.');
        END IF;
    END;

BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_EMPLEADO';

    add_table_if_missing(
        'INDECI_EMPLEADO_MARCADOR_ALIAS',
        'CREATE TABLE INDECI_EMPLEADO_MARCADOR_ALIAS ('
        || 'ID                        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'EMPLEADO_ID               NUMBER NOT NULL,'
        -- Nombre del marcador NORMALIZADO (mayúsculas, sin tildes, espacios simples):
        -- es la llave de emparejamiento.
        || 'NOMBRE_MARCADOR_NORM      VARCHAR2(150 CHAR) NOT NULL,'
        -- Nombre tal cual vino en el archivo (auditoría / mostrar al usuario).
        || 'NOMBRE_MARCADOR_ORIGINAL  VARCHAR2(150 CHAR),'
        || 'ORIGEN                    VARCHAR2(20 CHAR) DEFAULT ''COEN'' NOT NULL,'
        || 'ACTIVO                    NUMBER(1) DEFAULT 1 NOT NULL,'
        || 'CREATED_BY                VARCHAR2(50 CHAR),'
        || 'CREATED_AT                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        || 'UPDATED_BY                VARCHAR2(50 CHAR),'
        || 'UPDATED_AT                TIMESTAMP,'
        || 'CONSTRAINT INDECI_EMP_MARC_ALIAS_PK PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_EMP_MARC_ALIAS_UK UNIQUE (ORIGEN, NOMBRE_MARCADOR_NORM),'
        || 'CONSTRAINT INDECI_EMP_MARC_ALIAS_EMP_FK FOREIGN KEY (EMPLEADO_ID) '
        ||   'REFERENCES INDECI_EMPLEADO (ID),'
        || 'CONSTRAINT INDECI_EMP_MARC_ALIAS_ACT_CK CHECK (ACTIVO IN (0, 1))'
        || ')'
    );

    add_index_if_missing(
        'INDECI_EMP_MARC_ALIAS_EMP_IDX',
        'CREATE INDEX INDECI_EMP_MARC_ALIAS_EMP_IDX '
        || 'ON INDECI_EMPLEADO_MARCADOR_ALIAS (EMPLEADO_ID, ACTIVO)'
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('V012_19 finalizado correctamente.');
END;
/
