-- ============================================================================
-- V012_50 ROLLBACK — quita las 29 dependencias agregadas por V012_50.
--
-- Solo las elimina si ningún puesto de empleado las referencia todavía: si ya
-- se usaron para completar DEPENDENCIA_ID en INDECI_EMPLEADO_PUESTO_HIST, las
-- filas se conservan (evita dejar huérfanos).
-- ============================================================================
SET SERVEROUTPUT ON;

DELETE FROM GESTIONRRHH.INDECI_DEPENDENCIA d
 WHERE UPPER(TRIM(d.NOMBRE)) IN (
        'JEFATURA INSTITUCIONAL',
        'ORGANO DE CONTROL INSTITUCIONAL',
        'OFICINA DE COOPERACION Y ASUNTOS INTERNACIONALES',
        'UNIDAD FUNCIONAL DE GESTION DESCONCENTRADA',
        'DIRECCION DESCONCENTRADA DE AMAZONAS',
        'DIRECCION DESCONCENTRADA DE ANCASH',
        'DIRECCION DESCONCENTRADA DE APURIMAC',
        'DIRECCION DESCONCENTRADA DE AREQUIPA',
        'DIRECCION DESCONCENTRADA DE AYACUCHO',
        'DIRECCION DESCONCENTRADA DE CAJAMARCA',
        'DIRECCION DESCONCENTRADA DE CALLAO',
        'DIRECCION DESCONCENTRADA DE CUSCO',
        'DIRECCION DESCONCENTRADA DE HUANCAVELICA',
        'DIRECCION DESCONCENTRADA DE HUANUCO',
        'DIRECCION DESCONCENTRADA DE ICA',
        'DIRECCION DESCONCENTRADA DE JUNIN',
        'DIRECCION DESCONCENTRADA DE LA LIBERTAD',
        'DIRECCION DESCONCENTRADA DE LAMBAYEQUE',
        'DIRECCION DESCONCENTRADA DE LIMA',
        'DIRECCION DESCONCENTRADA DE LORETO',
        'DIRECCION DESCONCENTRADA DE MADRE DE DIOS',
        'DIRECCION DESCONCENTRADA DE MOQUEGUA',
        'DIRECCION DESCONCENTRADA DE PASCO',
        'DIRECCION DESCONCENTRADA DE PIURA',
        'DIRECCION DESCONCENTRADA DE PUNO',
        'DIRECCION DESCONCENTRADA DE SAN MARTIN',
        'DIRECCION DESCONCENTRADA DE TACNA',
        'DIRECCION DESCONCENTRADA DE TUMBES',
        'DIRECCION DESCONCENTRADA DE UCAYALI')
   AND NOT EXISTS (SELECT 1
                     FROM GESTIONRRHH.INDECI_EMPLEADO_PUESTO_HIST h
                    WHERE h.DEPENDENCIA_ID = d.ID);

COMMIT;
