-- ============================================================
-- V012_05 — Historial remunerativo del vínculo (F2)
--
-- Guarda las remuneraciones por vigencia para que el motor resuelva la BASE
-- según el período que procesa, en lugar de leer un único SUELDO_BASICO.
-- Decisión RR.HH. (2026-07-02): prioridad historial vigente y APROBADO; si no
-- hay, fallback a EMPLEADO_PLANILLA.SUELDO_BASICO con alerta/auditoría.
-- NO se elimina SUELDO_BASICO todavía.
--
-- Idempotente. Tablespace heredado de INDECI_EMPLEADO_PLANILLA.
-- ============================================================

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;
    v_ts    VARCHAR2(30);
BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_EMPLEADO_PLANILLA';

    SELECT COUNT(*) INTO v_count FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_EMPLEADO_REMUNERACION_HIST';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE GESTIONRRHH.INDECI_EMPLEADO_REMUNERACION_HIST ('
            || 'ID                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
            || 'EMPLEADO_PLANILLA_ID NUMBER        NOT NULL,'
            || 'VIGENCIA_DESDE       DATE          NOT NULL,'
            || 'VIGENCIA_HASTA       DATE,'
            || 'MONTO_BASE           NUMBER(12,2),'
            || 'REMUNERACION_TOTAL   NUMBER(12,2)  NOT NULL,'
            || 'TIPO_CAMBIO          VARCHAR2(40),'
            || 'DOCUMENTO_SUSTENTO   VARCHAR2(200),'
            || 'FUENTE               VARCHAR2(30)  DEFAULT ''MANUAL'' NOT NULL,'
            || 'ESTADO               VARCHAR2(20)  DEFAULT ''APROBADO'' NOT NULL,'
            || 'OBSERVACION          VARCHAR2(500),'
            || 'CREATED_BY           VARCHAR2(100),'
            || 'CREATED_AT           TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,'
            || 'CONSTRAINT INDECI_EMP_REM_HIST_FK FOREIGN KEY (EMPLEADO_PLANILLA_ID) '
            || '   REFERENCES GESTIONRRHH.INDECI_EMPLEADO_PLANILLA(ID),'
            || 'CONSTRAINT INDECI_EMP_REM_HIST_ESTADO_CK CHECK (ESTADO IN (''BORRADOR'',''APROBADO'',''ANULADO''))'
            || ') TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE('INDECI_EMPLEADO_REMUNERACION_HIST -> creada en ' || v_ts);

        EXECUTE IMMEDIATE
            'CREATE INDEX INDECI_EMP_REM_HIST_IDX '
            || 'ON GESTIONRRHH.INDECI_EMPLEADO_REMUNERACION_HIST '
            || '(EMPLEADO_PLANILLA_ID, ESTADO, VIGENCIA_DESDE) TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE('INDECI_EMP_REM_HIST_IDX -> creado.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('INDECI_EMPLEADO_REMUNERACION_HIST ya existe. Sin cambios.');
    END IF;

    DBMS_OUTPUT.PUT_LINE('V012_05 finalizado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR en V012_05: ' || SQLERRM);
        RAISE;
END;
/
