-- Agregar restricción única para (EMPLEADO_ID, ANIO) en INDECI_VACACION_SALDO
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE GESTIONRRHH.INDECI_VACACION_SALDO ADD CONSTRAINT UK_VACACION_SALDO_EMP_ANIO UNIQUE (EMPLEADO_ID, ANIO)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2261 THEN
            RAISE;
        END IF;
END;
/
