-- V012_11__fase3_adicional_reintegro.sql

-- 1. Agregar MOTIVO y SUSTENTO a INDECI_PLANILLA_LOTE para Planillas Adicionales y Reintegros
ALTER TABLE GESTIONRRHH.INDECI_PLANILLA_LOTE ADD MOTIVO VARCHAR2(500);
ALTER TABLE GESTIONRRHH.INDECI_PLANILLA_LOTE ADD SUSTENTO VARCHAR2(500);

-- 2. Crear tabla INDECI_REINTEGRO_MONTO para la Fase 3 de Reintegros
SET SERVEROUTPUT ON;

DECLARE
    v_ts VARCHAR2(30);
    v_ts_exists NUMBER;
    v_ts_clause VARCHAR2(100) := '';
BEGIN
    -- Resolver un TABLESPACE válido (evita ORA-00959 cuando el default no existe).
    BEGIN
        SELECT TABLESPACE_NAME INTO v_ts
          FROM USER_TABLES
         WHERE TABLE_NAME = 'INDECI_EMPLEADO';
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_ts := NULL;
    END;

    IF v_ts IS NOT NULL THEN
        SELECT COUNT(*) INTO v_ts_exists
          FROM USER_TABLESPACES
         WHERE TABLESPACE_NAME = v_ts;
        IF v_ts_exists = 0 THEN
            v_ts := NULL;
        END IF;
    END IF;

    IF v_ts IS NULL THEN
        SELECT DEFAULT_TABLESPACE INTO v_ts
          FROM USER_USERS
         WHERE USERNAME = USER;
        SELECT COUNT(*) INTO v_ts_exists
          FROM USER_TABLESPACES
         WHERE TABLESPACE_NAME = v_ts;
        IF v_ts_exists = 0 THEN
            v_ts := NULL;
        END IF;
    END IF;

    IF v_ts IS NOT NULL THEN
        v_ts_clause := ' TABLESPACE ' || v_ts;
    END IF;

    BEGIN
        EXECUTE IMMEDIATE 'CREATE TABLE GESTIONRRHH.INDECI_REINTEGRO_MONTO (
            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            EMPLEADO_ID NUMBER NOT NULL,
            PERIODO_DESTINO VARCHAR2(7) NOT NULL,
            PERIODO_ORIGEN VARCHAR2(7) NOT NULL,
            MOVIMIENTO_ORIGEN_ID NUMBER NOT NULL,
            CONCEPTO_ORIGEN_CODIGO VARCHAR2(20) NOT NULL,
            MONTO NUMBER(19,4) NOT NULL,
            MOTIVO VARCHAR2(500) NOT NULL,
            SUSTENTO VARCHAR2(500) NOT NULL,
            ESTADO_PAGO VARCHAR2(50) DEFAULT ''PENDIENTE'' NOT NULL,
            CREADO_POR VARCHAR2(60) NOT NULL,
            CREADO_EN TIMESTAMP NOT NULL
        )' || v_ts_clause;
        DBMS_OUTPUT.PUT_LINE('Tabla INDECI_REINTEGRO_MONTO creada exitosamente.');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
END;
/
