-- ============================================================
-- V012_09 — Track B F4: Gratificación CAS (Ley 32563) versionada
--
-- Sustento: Ley N.° 32563 (modifica art. 6 D.Leg. 1057) — los servidores CAS
-- reciben gratificación por Fiestas Patrias (julio) y por Navidad (diciembre),
-- cada una equivalente a UNA remuneración mensual (100%).
--
-- Crea INDECI_REGLA_BENEFICIO_CAS (regla versionada: LEGACY / FP / Navidad) y
-- siembra los 2 conceptos operativos de gratificación CAS (CODIGO_MEF 0077/0025)
-- en INDECI_CONCEPTO_PLANILLA, para que el motor los grabe en la planilla regular
-- de julio/diciembre. Conceptos INAFECTOS (no toca afectaciones tributarias/
-- pensionarias/EsSalud en F4 — pendiente validación tributaria RR.HH.).
--
-- Idempotente (MERGE por clave natural + check USER_TABLES). Tablespace heredado.
-- ============================================================

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;
    v_ts    VARCHAR2(30);
BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_EMPLEADO_PLANILLA';

    SELECT COUNT(*) INTO v_count FROM USER_TABLES
     WHERE TABLE_NAME = 'INDECI_REGLA_BENEFICIO_CAS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE GESTIONRRHH.INDECI_REGLA_BENEFICIO_CAS ('
            || 'ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
            || 'CODIGO_BENEFICIO    VARCHAR2(60)  NOT NULL,'
            || 'MES_APLICA          NUMBER(2)     NOT NULL,'
            || 'MONTO_TIPO          VARCHAR2(20)  NOT NULL,'
            || 'FACTOR              NUMBER(9,4),'
            || 'CODIGO_MEF          VARCHAR2(20),'
            || 'REGIMEN             VARCHAR2(10)  DEFAULT ''CAS'' NOT NULL,'
            || 'VIGENCIA_DESDE      DATE          NOT NULL,'
            || 'VIGENCIA_HASTA      DATE,'
            || 'ESTADO              VARCHAR2(20)  DEFAULT ''ACTIVO'' NOT NULL,'
            || 'NORMA_SUSTENTO      VARCHAR2(200),'
            || 'REQUIERE_APROB_RRHH CHAR(1)       DEFAULT ''N'','
            || 'CREATED_AT          TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,'
            || 'CONSTRAINT INDECI_REGLA_BEN_CAS_MONTO_CK CHECK (MONTO_TIPO IN (''FIJO'',''PCT_REMUNERACION'')),'
            || 'CONSTRAINT INDECI_REGLA_BEN_CAS_EST_CK   CHECK (ESTADO IN (''ACTIVO'',''INACTIVO'')),'
            || 'CONSTRAINT INDECI_REGLA_BEN_CAS_MES_CK   CHECK (MES_APLICA IN (7,12)),'
            || 'CONSTRAINT INDECI_REGLA_BEN_CAS_UK       UNIQUE (CODIGO_BENEFICIO, MES_APLICA, VIGENCIA_DESDE)'
            || ') TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE('INDECI_REGLA_BENEFICIO_CAS -> creada en ' || v_ts);

        EXECUTE IMMEDIATE
            'CREATE INDEX INDECI_REGLA_BEN_CAS_IDX ON GESTIONRRHH.INDECI_REGLA_BENEFICIO_CAS '
            || '(REGIMEN, MES_APLICA, ESTADO, VIGENCIA_DESDE) TABLESPACE ' || v_ts;
        DBMS_OUTPUT.PUT_LINE('INDECI_REGLA_BEN_CAS_IDX -> creado.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('INDECI_REGLA_BENEFICIO_CAS ya existe. Sin cambios de DDL.');
    END IF;

    DBMS_OUTPUT.PUT_LINE('V012_09 DDL finalizado.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR en V012_09 DDL: ' || SQLERRM);
        RAISE;
END;
/

-- Seed idempotente de las 3 reglas (FP + Navidad ACTIVAS 100%; LEGACY INACTIVA).
MERGE INTO GESTIONRRHH.INDECI_REGLA_BENEFICIO_CAS d
USING (
    SELECT 'GRATIFICACION_FIESTAS_PATRIAS_CAS' CODIGO_BENEFICIO, 7  MES_APLICA, 'PCT_REMUNERACION' MONTO_TIPO, 1.0000 FACTOR, '0077' CODIGO_MEF, 'ACTIVO'   ESTADO, 'Ley 32563 (modifica art. 6 D.Leg. 1057)' NORMA FROM DUAL UNION ALL
    SELECT 'GRATIFICACION_NAVIDAD_CAS',         12, 'PCT_REMUNERACION', 1.0000, '0025', 'ACTIVO',   'Ley 32563 (modifica art. 6 D.Leg. 1057)' FROM DUAL UNION ALL
    SELECT 'AGUINALDO_CAS_LEGACY',              7,  'FIJO',             NULL,   NULL,   'INACTIVO', 'Regla legacy (monto fijo MEF) — solo historicos/migracion' FROM DUAL UNION ALL
    SELECT 'AGUINALDO_CAS_LEGACY',              12, 'FIJO',             NULL,   NULL,   'INACTIVO', 'Regla legacy (monto fijo MEF) — solo historicos/migracion' FROM DUAL
) s
ON ( d.CODIGO_BENEFICIO = s.CODIGO_BENEFICIO AND d.MES_APLICA = s.MES_APLICA )
WHEN NOT MATCHED THEN INSERT
    (CODIGO_BENEFICIO, MES_APLICA, MONTO_TIPO, FACTOR, CODIGO_MEF, REGIMEN, VIGENCIA_DESDE, ESTADO, NORMA_SUSTENTO)
    VALUES (s.CODIGO_BENEFICIO, s.MES_APLICA, s.MONTO_TIPO, s.FACTOR, s.CODIGO_MEF, 'CAS', DATE '2025-01-01', s.ESTADO, s.NORMA);

-- Conceptos operativos de gratificación CAS (para que el motor los grabe en la
-- planilla). INAFECTOS: no afectan bases de pensión/EsSalud/IR (pendiente validación
-- tributaria RR.HH.). CODIGO_MEF 0077/0025 = códigos del catálogo MGRH (AGUI/GRAT jul/dic).
MERGE INTO GESTIONRRHH.INDECI_CONCEPTO_PLANILLA d
USING (
    SELECT '0077' AS CODIGO_MEF, 'Gratificación Fiestas Patrias CAS' AS NOMBRE, 'NO_REMUNERATIVO' AS TIPO_CONCEPTO, 'N' AS AFECTO_IR_5TA, 'N' AS AFECTO_APORTE_PENS, 'N' AS AFECTO_ESSALUD, 'N' AS ES_MUC, 'N' AS ES_CUC, '1057' AS REGIMEN_APLICABLE FROM DUAL UNION ALL
    SELECT '0025', 'Gratificación Navidad CAS', 'NO_REMUNERATIVO', 'N', 'N', 'N', 'N', 'N', '1057' FROM DUAL
) s
ON ( d.CODIGO_MEF = s.CODIGO_MEF )
WHEN MATCHED THEN UPDATE SET
    d.NOMBRE = s.NOMBRE, d.TIPO_CONCEPTO = s.TIPO_CONCEPTO,
    d.AFECTO_IR_5TA = s.AFECTO_IR_5TA, d.AFECTO_APORTE_PENS = s.AFECTO_APORTE_PENS,
    d.AFECTO_ESSALUD = s.AFECTO_ESSALUD, d.ES_MUC = s.ES_MUC, d.ES_CUC = s.ES_CUC,
    d.REGIMEN_APLICABLE = s.REGIMEN_APLICABLE
WHEN NOT MATCHED THEN INSERT (
    CODIGO, CODIGO_MEF, NOMBRE, TIPO, NATURALEZA,
    TIPO_CONCEPTO, AFECTO_IR_5TA, AFECTO_APORTE_PENS, AFECTO_ESSALUD,
    ES_MUC, ES_CUC, REGIMEN_APLICABLE, ACTIVO, CREATED_AT, FECHA_VIG_INI
) VALUES (
    s.CODIGO_MEF, s.CODIGO_MEF, s.NOMBRE, 'INGRESO', s.TIPO_CONCEPTO,
    s.TIPO_CONCEPTO, s.AFECTO_IR_5TA, s.AFECTO_APORTE_PENS, s.AFECTO_ESSALUD,
    s.ES_MUC, s.ES_CUC, s.REGIMEN_APLICABLE, 1, CURRENT_TIMESTAMP, DATE '2026-01-01'
);

COMMIT;
