-- ============================================================================
-- V012_31 — F9.3 Acumulación de vacaciones (D.S. 013-2019-PCM)
--
-- "Se pueden acumular hasta 2 períodos vacacionales (60 días). El exceso sobre
-- 2 períodos acumulados por desidia puede perder el goce físico, pero el
-- sistema NUNCA debe registrar esa pérdida de forma automática: se marca para
-- evaluación de RR.HH." (referencia normativa del proyecto,
-- vacaciones-ds-013-2019-pcm.md).
--
-- Esta tabla es un registro de AUDITORÍA, append-only (nunca se borra ni se
-- actualiza): documenta que RR.HH. evaluó la acumulación de un empleado y su
-- decisión, con sustento. NO modifica ningún saldo — el sistema jamás fuerza
-- pérdida ni goce automático; eso sigue pasando por los flujos existentes
-- (papeleta de vacaciones / Goce Directo).
--
-- Naming INDECI_*; PK IDENTITY; TABLESPACE anclado a INDECI_VACACIONES.
-- Idempotente. Ejecutar en GESTIONRRHH / Oracle 19c+.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
    v_ts VARCHAR2(30);

    PROCEDURE add_table_if_missing(p_table VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_table || ' -> creada en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_table || ' ya existe. Sin cambios.');
        END IF;
    END;

    PROCEDURE add_index_if_missing(p_idx VARCHAR2, p_ddl VARCHAR2) IS
        v NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v FROM USER_INDEXES WHERE INDEX_NAME = p_idx;
        IF v = 0 THEN
            EXECUTE IMMEDIATE p_ddl || ' TABLESPACE ' || v_ts;
            DBMS_OUTPUT.PUT_LINE(p_idx || ' -> creado en TBS ' || v_ts);
        ELSE
            DBMS_OUTPUT.PUT_LINE(p_idx || ' ya existe. Sin cambios.');
        END IF;
    END;

BEGIN
    SELECT TABLESPACE_NAME INTO v_ts
      FROM USER_TABLES WHERE TABLE_NAME = 'INDECI_VACACIONES';

    add_table_if_missing(
        'INDECI_VACACION_ACUM_DECISION',
        'CREATE TABLE INDECI_VACACION_ACUM_DECISION ('
        || 'ID                              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'
        || 'EMPLEADO_ID                     NUMBER NOT NULL,'
        -- Snapshot de cuántos períodos sin gozar tenía el empleado AL MOMENTO de la
        -- decisión (trazabilidad — no se recalcula después).
        || 'PERIODOS_PENDIENTES_AL_MOMENTO  NUMBER NOT NULL,'
        || 'MOTIVO_DECISION                 VARCHAR2(1000 CHAR) NOT NULL,'
        || 'DOCUMENTO_SUSTENTO              VARCHAR2(500 CHAR),'
        || 'USUARIO_REGISTRO                VARCHAR2(100 CHAR),'
        || 'ACTIVO                          NUMBER(1) DEFAULT 1 NOT NULL,'
        || 'CREATED_AT                      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,'
        || 'CONSTRAINT INDECI_VAC_ACUM_DEC_PK PRIMARY KEY (ID),'
        || 'CONSTRAINT INDECI_VAC_ACUM_DEC_ACT_CK CHECK (ACTIVO IN (0, 1))'
        || ')'
    );

    add_index_if_missing(
        'INDECI_VAC_ACUM_DEC_EMP_IDX',
        'CREATE INDEX INDECI_VAC_ACUM_DEC_EMP_IDX '
        || 'ON INDECI_VACACION_ACUM_DECISION (EMPLEADO_ID, ACTIVO)'
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('V012_31 finalizado correctamente.');
END;
/
